#!/usr/bin/env bash
set -u -o pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/VERIFICATION.md"
FAILED=0
TMP="$(mktemp -d)"

# ---------------------------------------------------------------------------
# Mathlib probe.
#
# This block replaces a hand-written environment note that asserted Mathlib was
# "unreachable here (its build cache is blocked and building from source is
# infeasible)".  That claim was FALSE on at least one machine the bundle is run
# on, and being prose it could not be caught by any check.  It is now measured
# on every run and the finding is written into VERIFICATION.md, so the recorded
# environment cannot drift from the actual one.
#
# Not using Mathlib is a scoping DECISION, not an impossibility: keeping the
# development on core Lean is what makes every theorem axiom-auditable by
# `#print axioms`.  That reason holds whether or not Mathlib is installed.
# ---------------------------------------------------------------------------
mathlib_probe () {
  local root oleans proj tc lp rc
  # depth 12: a Lake project puts Mathlib.olean 11 levels below $HOME as
  # <proj>/.lake/packages/mathlib/.lake/build/lib/lean/.  A shallower search
  # silently reports NOT FOUND, which is how the wrong note survived before.
  root="$(timeout 120 find "$HOME" -maxdepth 12 -type f -name 'Mathlib.olean' \
           -path '*/build/lib/lean/*' 2>/dev/null | head -1)"
  if [ -z "$root" ]; then
    echo "Mathlib probe (measured by verify.sh on this run): NOT FOUND under \$HOME."
    echo "No measure-theoretic content is formalised in Lean. Note that this is a"
    echo "scoping decision and not a consequence of the probe: the development is"
    echo "kept on core Lean so that every theorem is axiom-auditable."
    return 0
  fi
  proj="${root%%/.lake/packages/*}"
  oleans="$(find "$(dirname "$root")/Mathlib" -name '*.olean' 2>/dev/null | wc -l)"
  tc="$(cat "$proj/lean-toolchain" 2>/dev/null || echo unknown)"
  cat > "$TMP/mlprobe.lean" <<'LEANEOF'
import Mathlib.MeasureTheory.Integral.IntervalIntegral
import Mathlib.MeasureTheory.Integral.IntegrationByParts
#check @intervalIntegral.integral_deriv_mul_eq_sub
#check @MeasureTheory.integral_nonneg
LEANEOF
  lp="$(ls -d "$proj"/.lake/packages/*/.lake/build/lib/lean 2>/dev/null | tr '\n' ':')"
  lp="$proj/.lake/build/lib/lean:$lp"
  # cd into the project so elan dispatches to the toolchain Mathlib was built
  # with; running the ambient `lean` against foreign oleans would fail.
  if ( cd "$proj" && timeout 900 env LEAN_PATH="$lp" lean "$TMP/mlprobe.lean" ) \
       > "$TMP/mlprobe.out" 2>&1; then rc=PASS; else rc=FAIL; fi
  echo "Mathlib probe (measured by verify.sh on this run, not asserted by hand):"
  echo "  found      : $proj"
  echo "  built      : $oleans compiled modules (.olean)"
  echo "  toolchain  : $tc   (the Lean suite itself runs on $(lean --version 2>/dev/null | sed 's/.*version \([0-9.]*\).*/\1/'))"
  echo "  import test: $rc -- compiled a file importing Mathlib and resolving"
  echo "               intervalIntegral.integral_deriv_mul_eq_sub (integration by"
  echo "               parts) and MeasureTheory.integral_nonneg, the two"
  echo "               facilities a Lean proof of \`step_nonpos\` would need."
  echo
  echo "So Mathlib is AVAILABLE here. No measure-theoretic content is formalised"
  echo "in Lean regardless, and that is a scoping decision rather than a"
  echo "limitation: keeping the development on core Lean is what lets"
  echo "\`#print axioms\` audit every theorem. The analytic step therefore enters"
  echo "as an explicit hypothesis (\`step_nonpos\`), discharged at tier S; see"
  echo "PROOFS.tex, section on the evidence tiers, for what that does and does"
  echo "not establish."
}

{
echo "# Verification status (generated)"
echo
echo "Generated by \`verify.sh\` on $(date -u '+%Y-%m-%d %H:%M UTC'). Do not edit"
echo "by hand: this file is overwritten on every run, so it cannot drift from"
echo "the suites it reports. The canonical statement of the results is"
echo "\`PROOFS.tex\`; this file records only what the checks actually printed."
echo
mathlib_probe
} > "$OUT"

run_py () {
  local title="$1" script="$2"
  echo "======================================================================"
  echo " $title"
  echo "======================================================================"
  { echo; echo "## $title (\`$script\`)"; echo; echo '```'; } >> "$OUT"
  if python3 "$HERE/$script" 2>&1 | tee -a "$OUT"; then :; fi
  if ! grep -q "0 failures" "$OUT"; then :; fi
  echo '```' >> "$OUT"
  echo
}

echo "======================================================================"
echo " NUMERICAL CHECKS  (scipy)"
echo "======================================================================"
{ echo; echo '## Suite 1 - numerical (`checks/run_all.py`)'; echo; echo '```'; } >> "$OUT"
python3 "$HERE/checks/run_all.py" 2>&1 | tee -a "$OUT" || FAILED=1
echo '```' >> "$OUT"

echo
echo "======================================================================"
echo " SYMBOLIC CHECKS  (sympy)"
echo "======================================================================"
{ echo; echo '## Suite 2 - symbolic (`checks/verify_sympy.py`)'; echo; echo '```'; } >> "$OUT"
python3 "$HERE/checks/verify_sympy.py" 2>&1 | tee -a "$OUT" || FAILED=1
echo '```' >> "$OUT"

echo
echo "======================================================================"
echo " P6 / P7 / P9-PARTIAL PROOF CHECKS"
echo "======================================================================"
{ echo; echo '## Suite 3 - P6, P7, P9 partial (`checks/verify_p679.py`)'; echo; echo '```'; } >> "$OUT"
python3 "$HERE/checks/verify_p679.py" 2>&1 | tee -a "$OUT" || FAILED=1
echo '```' >> "$OUT"

echo
echo "======================================================================"
echo " P8 / P9-FULL / UNIQUENESS / MU-CROSSOVER CHECKS"
echo "======================================================================"
{ echo; echo '## Suite 4 - P8, P9 full, uniqueness, mu-crossover (`checks/verify_p89.py`)'; echo; echo '```'; } >> "$OUT"
python3 "$HERE/checks/verify_p89.py" 2>&1 | tee -a "$OUT" || FAILED=1
echo '```' >> "$OUT"

echo
echo "======================================================================"
echo " P9 GENERAL PIVOT-SPREAD / STRICTNESS CHECKS"
echo "======================================================================"
{ echo; echo '## Suite 5 - P9 general pivot-spreads, strictness (`checks/verify_p9gen.py`)'; echo; echo '```'; } >> "$OUT"
python3 "$HERE/checks/verify_p9gen.py" 2>&1 | tee -a "$OUT" || FAILED=1
echo '```' >> "$OUT"

echo
echo "======================================================================"
echo " EQUILIBRIUM ENUMERATION  (P5-inv: count uniqueness, identity sets)"
echo "======================================================================"
{ echo; echo '## Suite 6 - equilibrium enumeration (`checks/verify_equilibria.py`)'; echo; echo '```'; } >> "$OUT"
python3 "$HERE/checks/verify_equilibria.py" 2>&1 | tee -a "$OUT" || FAILED=1
echo '```' >> "$OUT"

echo
echo "======================================================================"
echo " ANONYMITY BOUNDARY  (A1: prop:anon on model-induced primitives)"
echo "======================================================================"
{ echo; echo '## Suite 7 - anonymity boundary (`checks/verify_anonymity.py`)'; echo; echo '```'; } >> "$OUT"
python3 "$HERE/checks/verify_anonymity.py" 2>&1 | tee -a "$OUT" || FAILED=1
echo '```' >> "$OUT"

echo
echo "======================================================================"
echo " TAIL-CONDITION BAND  (open item 3: coverage criterion and sharpness)"
echo "======================================================================"
{ echo; echo '## Suite 8 - tail-condition band (`checks/verify_tailband.py`)'; echo; echo '```'; } >> "$OUT"
python3 "$HERE/checks/verify_tailband.py" 2>&1 | tee -a "$OUT" || FAILED=1
echo '```' >> "$OUT"

echo
echo "======================================================================"
echo " MEASUREMENT MAP  (mathematics the companion note adds of its own)"
echo "======================================================================"
{ echo; echo '## Suite 9 - measurement map (`checks/verify_measurement_map.py`)'; echo; echo '```'; } >> "$OUT"
python3 "$HERE/checks/verify_measurement_map.py" 2>&1 | tee -a "$OUT" || FAILED=1
echo '```' >> "$OUT"

echo
echo "======================================================================"
echo " MANUSCRIPT SKELETON  (row links, Lean names, quotes, prose share)"
echo "======================================================================"
{ echo; echo '## Suite 10 - manuscript skeleton (`checks/verify_manuscript.py`)'; echo; echo '```'; } >> "$OUT"
python3 "$HERE/checks/verify_manuscript.py" 2>&1 | tee -a "$OUT" || FAILED=1
echo '```' >> "$OUT"

echo
echo "======================================================================"
echo " PROOF CHECKS  (Lean 4, core only)"
echo "======================================================================"
{ echo; echo '## Suite 11 - Lean 4 (`lean/EntryContest.lean`)'; echo; echo '```'; } >> "$OUT"

if command -v lean >/dev/null 2>&1; then
  cd "$HERE/lean"
  if lean EntryContest.lean; then
    echo "[PASS] EntryContest.lean compiles with no errors" | tee -a "$OUT"
  else
    echo "[FAIL] EntryContest.lean does not compile" | tee -a "$OUT"
    FAILED=1
  fi

  NTHM=$(grep -c '^theorem' EntryContest.lean)
  NSORRY=$(grep -c '\bsorry\b' EntryContest.lean || true)
  echo "theorems declared: $NTHM" | tee -a "$OUT"
  echo "occurrences of sorry: $NSORRY" | tee -a "$OUT"

  cp EntryContest.lean "$TMP/audit.lean"
  {
    echo ""
    echo "open EntryContest"
    grep '^theorem' EntryContest.lean \
      | sed "s/theorem \([A-Za-z0-9_']*\).*/#print axioms EntryContest.\1/"
  } >> "$TMP/audit.lean"

  echo "--- axiom audit (every declared theorem) ---" | tee -a "$OUT"
  lean "$TMP/audit.lean" > "$TMP/axioms.txt" 2>&1
  cat "$TMP/axioms.txt" | tee -a "$OUT"
  NFREE=$(grep -c 'does not depend on any axioms' "$TMP/axioms.txt" || true)
  NAUD=$(grep -c "^'EntryContest" "$TMP/axioms.txt" || true)
  echo "audited: $NAUD of $NTHM declared; axiom-free: $NFREE" | tee -a "$OUT"
  if [ "$NAUD" -ne "$NTHM" ]; then
    echo "[FAIL] audit does not cover every declared theorem" | tee -a "$OUT"
    FAILED=1
  fi
  if [ "$NSORRY" -ne 0 ]; then
    echo "[FAIL] sorry present in EntryContest.lean" | tee -a "$OUT"
    FAILED=1
  fi
  BADAX=$(grep -oE "depends on axioms: \[[^]]*\]" "$TMP/axioms.txt" \
    | sed 's/.*\[//; s/\]//' | tr ',' '\n' | sed 's/^ *//' \
    | grep -vxE 'propext|Quot\.sound' | sort -u | tr '\n' ' ')
  if [ -n "$BADAX" ]; then
    echo "[FAIL] axioms outside propext/Quot.sound: $BADAX" | tee -a "$OUT"
    FAILED=1
  else
    echo "axioms outside propext/Quot.sound: none" | tee -a "$OUT"
  fi
else
  echo "[FAIL] lean not on PATH - the Lean suite did NOT run" | tee -a "$OUT"
  echo "install: elan toolchain install leanprover/lean4:v4.33.1" | tee -a "$OUT"
  echo "         core only, no Mathlib, no lakefile; verified on v4.14.0 and v4.33.1" | tee -a "$OUT"
  echo "if elan cannot resolve release.lean-lang.org, the direct tarball works:" | tee -a "$OUT"
  echo "  curl -sL -o lean.tar.zst \\" | tee -a "$OUT"
  echo "    https://github.com/leanprover/lean4/releases/download/v4.33.1/lean-4.33.1-linux.tar.zst" | tee -a "$OUT"
  echo "  tar --zstd -xf lean.tar.zst && export PATH=\$PWD/lean-4.33.1-linux/bin:\$PATH" | tee -a "$OUT"
  FAILED=1
fi
echo '```' >> "$OUT"

echo
echo "======================================================================"
echo " DOC CONSISTENCY  (PROOFS.tex prose vs this run's generated evidence)"
echo "======================================================================"
{ echo; echo '## Suite 12 - doc consistency (`checks/verify_docs.py`)'; echo; echo '```'; } >> "$OUT"
python3 "$HERE/checks/verify_docs.py" "$OUT" 2>&1 | tee -a "$OUT" || FAILED=1
echo '```' >> "$OUT"

echo
if [ "$FAILED" -eq 0 ]; then
  echo "ALL SUITES COMPLETED"
  { echo; echo '## Result'; echo; echo 'All suites completed with no failures.'; } >> "$OUT"
else
  echo "SOME SUITES REPORTED FAILURES"
  { echo; echo '## Result'; echo; echo '**Some suites reported failures.** See the blocks above.'; } >> "$OUT"
fi

rm -rf "$TMP"
exit "$FAILED"
