#!/usr/bin/env bash
set -u -o pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/VERIFICATION.md"
FAILED=0

{
echo "# Verification status (generated)"
echo
echo "Generated by \`verify.sh\` on $(date -u '+%Y-%m-%d %H:%M UTC'). Do not edit"
echo "by hand. The canonical statement of the results is \`MANUSCRIPT.tex\`; this"
echo "file records only what the checks printed."
} > "$OUT"

suite () {
  local n="$1" title="$2" script="$3"; shift 3
  echo "======================================================================"
  echo " $title"
  echo "======================================================================"
  { echo; echo "## Suite $n - $title (\`$script\`)"; echo; echo '```'; } >> "$OUT"
  python3 "$HERE/$script" "$@" 2>&1 | tee -a "$OUT" || FAILED=1
  echo '```' >> "$OUT"
  echo
}

suite 1 "manuscript skeleton" checks/verify_manuscript.py
suite 2 "measurement map" checks/verify_measurement.py
suite 3 "Lean 4 with Mathlib" checks/verify_mathlib.py
suite 4 "retirement of PROOFS_v2" checks/verify_retirement.py
suite 5 "doc consistency" checks/verify_docs.py "$OUT"

if [ "$FAILED" -eq 0 ]; then
  echo "ALL SUITES COMPLETED"
  { echo; echo '## Result'; echo; echo 'All suites completed with no failures.'; } >> "$OUT"
else
  echo "SOME SUITES REPORTED FAILURES"
  { echo; echo '## Result'; echo; echo '**Some suites reported failures.** See the blocks above.'; } >> "$OUT"
fi
exit "$FAILED"
