# attempted matching artifical hhid, age(increasing order), gender, popgroup, total income

setwd('c:/local_files/research/consumption/sa/')

# There is no point matching based on age signature of family
# since two families of same age signature and race can exist in a very small area
age_signature<-function(age,gender,popgroup){
  return(toString(sort(age)));
}

############# hh columns ###############
diary_info_columns_1995 <-function () {
  icols1995 <- c("hhid",
                 "gender_household_head",
                 "age_household_head",
                 "age_member2",
                 "age_member3",
                 "age_member4",
                 "age_member5",
                 "age_member6",
                 "age_member7",
                 "age_member8",
                 "age_member9",
                 "age_member10",
                 "total_income_of_household_head",
                 "total_income",
                 "total_expenditure",
                 "race_household_head")
  visible_categories<-visible_categories_1995();
  icols1995<-c(icols1995,visible_categories)
  return(icols1995);
}

diary_info_columns_2010<-function(){
  #each of these are relative to the household head
  icols2010 <-c("hhid", # unique ID
                "gender_household_head",
                "total_expenditure",
                "race_household_head",
                "n_members",
                "area_type")
  # must also include visible categories
  return(icols2010)
}

diary_info_columns_2005<-function(){
  #each of these are relative to the household head
  icols2005 <-c("hhid", # unique ID
                "gender_household_head",
                "total_expenditure",
                "race_household_head",
                "n_members",
                "area_type")
  # must also include visible categories
  return(icols2005)
}
##############<end hh columns>############

########### hh columns mapping ##########
hh_mapping_2010 <-function () {
  # in 2010 survey, the OHS is equivalent to person-info and hh (this function) is equivalent to house-info 
  s = data.frame(iesname=NULL,name=NULL)
  s= rbind(s,data.frame(iesname="UQNO",name="hhid"))
  s= rbind(s,data.frame(iesname="GenderOfHead",name="gender_household_head"))
  s= rbind(s,data.frame(iesname="PopGrpOfHead",name="race_household_head"))
  s= rbind(s,data.frame(iesname="Consumptions",name="total_expenditure"))
  s= rbind(s,data.frame(iesname="Hsize",name="n_members"))
  s= rbind(s,data.frame(iesname="Settlement_type",name="area_type"))
  s= rbind(s,data.frame(iesname="Q21HIGHESTLEVEL",name="highest_education"))
  return(s)
}

hh_mapping_2005<-function(){
  s = data.frame(iesname=NULL,name=NULL)
  s=rbind(s,data.frame(iesname="uqno",name="hhid"))
  s=rbind(s,data.frame(iesname="genderofhead",name="gender_household_head"))
  s=rbind(s,data.frame(iesname="consumptions",name="total_expenditure"))
  s=rbind(s,data.frame(iesname="popgrpofhead",name="race_household_head"))
  s=rbind(s,data.frame(iesname="n_members",name="hsize"))
  s=rbind(s,data.frame(iesname="settlement",name="area_type"))
  return(s)
}

hh_mapping_1995 <-function(){
  s = data.frame(iesname=NULL,name=NULL)
  s= rbind(s,data.frame(iesname="hhid",name="hhid"))
  s= rbind(s,data.frame(iesname="b01f001",name="gender_household_head"))
  s= rbind(s,data.frame(iesname="b02f001",name="age_household_head"))
  s= rbind(s,data.frame(iesname="b03f001",name="race_household_head"))
  s=rbind(s,data.frame(iesname="b02f002",name="age_member2"))
  s=rbind(s,data.frame(iesname="b02f003",name="age_member3"))
  s=rbind(s,data.frame(iesname="b02f004",name="age_member4"))
  s=rbind(s,data.frame(iesname="b02f005",name="age_member5"))
  s=rbind(s,data.frame(iesname="b02f006",name="age_member6"))
  s=rbind(s,data.frame(iesname="b02f007",name="age_member7"))
  s=rbind(s,data.frame(iesname="b02f008",name="age_member8"))
  s=rbind(s,data.frame(iesname="b02f009",name="age_member9"))
  s=rbind(s,data.frame(iesname="b02f010",name="age_member10"))
  
  
  s= rbind(s,data.frame(iesname="b15f001",name="flour_cake"))
  s= rbind(s,data.frame(iesname="b15f002",name="flour_bread"))
  s= rbind(s,data.frame(iesname="b15f003",name="flour_maize"))
  s= rbind(s,data.frame(iesname="b15f004",name="sorghum"))
  s= rbind(s,data.frame(iesname="b15f005",name="flour_other"))
  s= rbind(s,data.frame(iesname="b15f006",name="cereals"))
  s= rbind(s,data.frame(iesname="b15f007",name="rice"))
  s= rbind(s,data.frame(iesname="b15f008",name="rice_mealie"))
  s= rbind(s,data.frame(iesname="b15f009",name="pasta"))
  s= rbind(s,data.frame(iesname="b15f010",name="bread_white"))
  s= rbind(s,data.frame(iesname="b15f011",name="bread_brown"))
  s= rbind(s,data.frame(iesname="b15f012",name="breadroll"))
  s= rbind(s,data.frame(iesname="b15f013",name="bakedproducts"))
  s= rbind(s,data.frame(iesname="b15f014",name="babyfood"))
  s= rbind(s,data.frame(iesname="b15f015",name="cereals_other"))
  s= rbind(s,data.frame(iesname="b15f100",name="total_cereals"))
  s= rbind(s,data.frame(iesname="b16f001",name="beef_bulk"))
  s= rbind(s,data.frame(iesname="b16f002",name="lamb_mutton_bulk"))
  s= rbind(s,data.frame(iesname="b16f003",name="pork_bulk"))
  s= rbind(s,data.frame(iesname="b16f004",name="poultry_bulk"))
  s= rbind(s,data.frame(iesname="b16f005",name="meat_other_bulk"))
  s= rbind(s,data.frame(iesname="b16f006",name="beef"))
  s= rbind(s,data.frame(iesname="b16f007",name="lamb_mutton"))
  s= rbind(s,data.frame(iesname="b16f008",name="pork"))
  s= rbind(s,data.frame(iesname="b16f009",name="poultry"))
  s= rbind(s,data.frame(iesname="b16f010",name="boerewors"))
  s= rbind(s,data.frame(iesname="b16f011",name="sausage_other"))
  s= rbind(s,data.frame(iesname="b16f012",name="coldmeat"))
  s= rbind(s,data.frame(iesname="b16f013",name="sausage_dried"))
  s= rbind(s,data.frame(iesname="b16f014",name="bacon"))
  s= rbind(s,data.frame(iesname="b16f015",name="meat_paste"))
  s= rbind(s,data.frame(iesname="b16f016",name="meat_babyfood"))
  s= rbind(s,data.frame(iesname="b16f017",name="meat_other"))
  s= rbind(s,data.frame(iesname="b16f100",name="total_meat"))
  s= rbind(s,data.frame(iesname="b18f001",name="fish_fresh"))
  s= rbind(s,data.frame(iesname="b18f002" ,name="fish_frozen"))
  s= rbind(s,data.frame(iesname="b18f003" ,name="fish_canned"))
  s= rbind(s,data.frame(iesname="b18f004" ,name="fish_other"))
  s= rbind(s,data.frame(iesname="b18f005" ,name="seafood"))
  s= rbind(s,data.frame(iesname="b18f100" ,name="total_seafood"))
  s= rbind(s,data.frame(iesname="b19f002" ,name="margarine"))
  s= rbind(s,data.frame(iesname="b19f003" ,name="oil_cooking"))
  s= rbind(s,data.frame(iesname="b19f004" ,name="peanut_butter"))
  s= rbind(s,data.frame(iesname="b19f005" ,name="oil_other")) 
  s= rbind(s,data.frame(iesname="b19f100" ,name="total_oil"))
  s= rbind(s,data.frame(iesname="b20f001" ,name="milk"))
  s= rbind(s,data.frame(iesname="b20f002" ,name="buttermilk"))
  s= rbind(s,data.frame(iesname="b20f003" ,name="cream_yoghurt"))
  s= rbind(s,data.frame(iesname="b20f004" ,name="icecream"))
  s= rbind(s,data.frame(iesname="b20f005" ,name="milkpowder"))
  s= rbind(s,data.frame(iesname="b20f006" ,name="milk_condensed"))
  s= rbind(s,data.frame(iesname="b20f007" ,name="milk_longlife"))
  s= rbind(s,data.frame(iesname="b20f008" ,name="cheese"))
  s= rbind(s,data.frame(iesname="b20f009" ,name="milk_babyfood"))
  s= rbind(s,data.frame(iesname="b20f010" ,name="milk_other"))
  s= rbind(s,data.frame(iesname="b20f011" ,name="eggs"))
  s= rbind(s,data.frame(iesname="b20f100" ,name="total_milkeggs"))
  s=rbind(s,data.frame(iesname="b21f001",name="potatoes"))
  s=rbind(s,data.frame(iesname="b21f002",name="sweet_potatoes"))
  s=rbind(s,data.frame(iesname="b21f003",name="green_mielies"))
  s=rbind(s,data.frame(iesname="b21f004",name="onions"))
  s=rbind(s,data.frame(iesname="b21f005",name="tomatoes"))
  s=rbind(s,data.frame(iesname="b21f006",name="green_beans"))
  s=rbind(s,data.frame(iesname="b21f007",name="cabbage"))
  s=rbind(s,data.frame(iesname="b21f008",name="carrots"))
  s=rbind(s,data.frame(iesname="b21f009",name="marrows"))
  s=rbind(s,data.frame(iesname="b21f010",name="beetroot"))
  s=rbind(s,data.frame(iesname="b21f011",name="lettuce"))
  s=rbind(s,data.frame(iesname="b21f012",name="marogo"))
  s=rbind(s,data.frame(iesname="b21f013",name="other_fresh_vegetables"))
  s=rbind(s,data.frame(iesname="b21f014",name="frozen_beans"))
  s=rbind(s,data.frame(iesname="b21f015",name="frozen_peas"))
  s= rbind(s,data.frame(iesname="b19f001" ,name="butter"))
  s=rbind(s,data.frame(iesname="b21f016",name="frozen_carrots"))
  s=rbind(s,data.frame(iesname="b21f017",name="other_frozen_vegetables"))
  s=rbind(s,data.frame(iesname="b21f018",name="canned_vegetables"))
  s=rbind(s,data.frame(iesname="b21f019",name="dried_peas_beans_lentils"))
  s=rbind(s,data.frame(iesname="b21f020",name="vegetable_baby_food"))
  s=rbind(s,data.frame(iesname="b21f021",name="vegetable_others"))
  s=rbind(s,data.frame(iesname="b21f100",name="total_vegetable"))
  s=rbind(s,data.frame(iesname="b22f001",name="apples"))
  s=rbind(s,data.frame(iesname="b22f002",name="fruit_other_deciduous"))
  s=rbind(s,data.frame(iesname="b22f003",name="bananas"))
  s=rbind(s,data.frame(iesname="b22f004",name="fruit_other_subtropical"))
  s=rbind(s,data.frame(iesname="b22f005",name="oranges"))
  s=rbind(s,data.frame(iesname="b22f006",name="fruit_other_citric"))
  s=rbind(s,data.frame(iesname="b22f007",name="fruit_other"))
  s=rbind(s,data.frame(iesname="b22f008",name="fruit_canned"))
  s=rbind(s,data.frame(iesname="b22f009",name="fruit_crystallized"))
  s=rbind(s,data.frame(iesname="b22f010",name="fruit_juices"))
  s=rbind(s,data.frame(iesname="b22f011",name="nuts"))
  s=rbind(s,data.frame(iesname="b22f012",name="fruit_babyfood"))
  s=rbind(s,data.frame(iesname="b22f013",name="other_fruit_nu"))
  s=rbind(s,data.frame(iesname="b22f100",name="total_fruit_nuts"))
  s=rbind(s,data.frame(iesname="b23f001",name="white_sugar"))
  s=rbind(s,data.frame(iesname="b23f002",name="brown_sugar"))
  s=rbind(s,data.frame(iesname="b23f003",name="sweeteners"))
  s=rbind(s,data.frame(iesname="b23f004",name="other_sugar"))
  s=rbind(s,data.frame(iesname="b23f100",name="total_sugar"))
  s=rbind(s,data.frame(iesname="b24f001",name="syrup_honey"))
  s=rbind(s,data.frame(iesname="b24f002",name="jam"))
  s=rbind(s,data.frame(iesname="b24f003",name="jelly_powders"))
  s=rbind(s,data.frame(iesname="b24f004",name="chocolates"))
  s=rbind(s,data.frame(iesname="b24f005",name="sweets_other"))
  s=rbind(s,data.frame(iesname="b24f006",name="sugar_products_other"))
  s=rbind(s,data.frame(iesname="b24f100",name="total_other_sugar_products"))
  s=rbind(s,data.frame(iesname="b25f001",name="coffee_instant"))
  s=rbind(s,data.frame(iesname="b25f002",name="coffee_beans"))
  s=rbind(s,data.frame(iesname="b25f003",name="tea_ceylon"))
  s=rbind(s,data.frame(iesname="b25f004",name="tea_herbal"))
  s=rbind(s,data.frame(iesname="b25f005",name="cocoa"))
  s=rbind(s,data.frame(iesname="b25f100",name="total_coffee_tea"))
  s=rbind(s,data.frame(iesname="b26f001",name="meal_oven_ready"))
  s=rbind(s,data.frame(iesname="b26f002",name="custard_powder_puddings"))
  s=rbind(s,data.frame(iesname="b26f003",name="baking_powder"))
  s=rbind(s,data.frame(iesname="b26f004",name="salt_pepper"))
  s=rbind(s,data.frame(iesname="b26f005",name="vinegar"))
  s=rbind(s,data.frame(iesname="b26f006",name="herbs_and_spices"))
  s=rbind(s,data.frame(iesname="b26f007",name="pickles"))
  s=rbind(s,data.frame(iesname="b26f008",name="soups_canned"))
  s=rbind(s,data.frame(iesname="b26f009",name="potatocrisps"))
  s=rbind(s,data.frame(iesname="b26f010",name="popcorn"))
  s=rbind(s,data.frame(iesname="b26f011",name="other_food_products"))
  s=rbind(s,data.frame(iesname="b26f100",name="total_other_food_products"))
  s=rbind(s,data.frame(iesname="b27f001",name="food_consumed_away_from_home"))
  s=rbind(s,data.frame(iesname="b27f002",name="meals_takeaway"))
  s=rbind(s,data.frame(iesname="b27f003",name="meals_snacks_in_staff_cafetarias"))
  s=rbind(s,data.frame(iesname="b27f100",name="total_food_consumed_away_from_home"))
  s=rbind(s,data.frame(iesname="b27f200",name="total_food"))
  s=rbind(s,data.frame(iesname="b28f001",name="soft_drinks_consumed_away_from_home"))
  s=rbind(s,data.frame(iesname="b28f002",name="mineral_water_consumed_away_from_home"))
  s=rbind(s,data.frame(iesname="b28f003",name="fruit_squashes_consumed_away_from_home"))
  s=rbind(s,data.frame(iesname="b28f004",name="other_cool_drinks_consumed_away_from_home"))
  s=rbind(s,data.frame(iesname="b28f100",name="total_cool_drinks_consumed_away_from_home"))
  s=rbind(s,data.frame(iesname="b29f001",name="soft_drinks"))
  s=rbind(s,data.frame(iesname="b29f002",name="mineral_water"))
  s=rbind(s,data.frame(iesname="b29f003",name="fruit_squashes"))
  s=rbind(s,data.frame(iesname="b29f004",name="other_cool_drinks"))
  s=rbind(s,data.frame(iesname="b29f100",name="total_cool_drinks"))
  s=rbind(s,data.frame(iesname="b30f001",name="liquor_consumed_away_from_home"))
  s=rbind(s,data.frame(iesname="b30f002",name="other_spirits_consumed_away_from_home"))
  s=rbind(s,data.frame(iesname="b30f003",name="beercider_consumed_away_from_home"))
  s=rbind(s,data.frame(iesname="b30f004",name="sorghumbeer_consumed_away_from_home"))
  s=rbind(s,data.frame(iesname="b30f005",name="tablewine_consumed_away_from_home"))
  s=rbind(s,data.frame(iesname="b30f006",name="fortifiedwine_consumed_away_from_home"))
  s=rbind(s,data.frame(iesname="b30f007",name="other_alcohol_consumed_away_from_home"))
  s=rbind(s,data.frame(iesname="b30f100",name="total_alcohol_consumed_away_from_home"))
  s=rbind(s,data.frame(iesname="b31f001",name="brandy_whiskey_gin"))
  s=rbind(s,data.frame(iesname="b31f002",name="other_spirits"))
  s=rbind(s,data.frame(iesname="b31f003",name="beercider"))
  s=rbind(s,data.frame(iesname="b31f004",name="sorghumbeer"))
  s=rbind(s,data.frame(iesname="b31f005",name="tablewine"))
  s=rbind(s,data.frame(iesname="b31f006",name="fortifiedwine"))
  s=rbind(s,data.frame(iesname="b31f007",name="other_alcohol"))
  s=rbind(s,data.frame(iesname="b31f100",name="total_alcohol"))
  s=rbind(s,data.frame(iesname="b32f001",name="cigarette"))
  s=rbind(s,data.frame(iesname="b32f002",name="cigarcigarello"))
  s=rbind(s,data.frame(iesname="b32f003",name="pipe"))
  s=rbind(s,data.frame(iesname="b32f004",name="smokers_requisites"))
  s=rbind(s,data.frame(iesname="b32f100",name="total_tobacco_products"))
  s=rbind(s,data.frame(iesname="b33f001",name="men_personal_care"))
  s=rbind(s,data.frame(iesname="b33f002",name="women_personal_care"))
  s=rbind(s,data.frame(iesname="b33f003",name="electrical_appliances"))
  s=rbind(s,data.frame(iesname="b33f004",name="hair_pieces"))
  s=rbind(s,data.frame(iesname="b33f005",name="shampoo"))
  s=rbind(s,data.frame(iesname="b33f006",name="sprays"))
  s=rbind(s,data.frame(iesname="b33f007",name="other_hair_preparations"))
  s=rbind(s,data.frame(iesname="b33f008",name="soap"))
  s=rbind(s,data.frame(iesname="b33f009",name="toothcare_products"))
  s=rbind(s,data.frame(iesname="b33f010",name="shaving_products"))
  s=rbind(s,data.frame(iesname="b33f011",name="skin_cream"))
  s=rbind(s,data.frame(iesname="b33f012",name="lipsticks_nailcare"))
  s=rbind(s,data.frame(iesname="b33f013",name="deodorants"))
  s=rbind(s,data.frame(iesname="b33f014",name="other_makeup"))
  s=rbind(s,data.frame(iesname="b33f015",name="nappies"))
  s=rbind(s,data.frame(iesname="b33f016",name="tissues"))
  s=rbind(s,data.frame(iesname="b33f017",name="sanitary_towels"))
  s=rbind(s,data.frame(iesname="b33f018",name="other_personal_care"))
  s=rbind(s,data.frame(iesname="b33f100",name="total_personal_care"))
  s=rbind(s,data.frame(iesname="b34f001",name="washing_detergent"))
  s=rbind(s,data.frame(iesname="b34f002",name="polish"))
  s=rbind(s,data.frame(iesname="b34f003",name="scourer"))
  s=rbind(s,data.frame(iesname="b34f004",name="cleaner"))
  s=rbind(s,data.frame(iesname="b34f005",name="matches"))
  s=rbind(s,data.frame(iesname="b34f006",name="broombrush"))
  s=rbind(s,data.frame(iesname="b34f007",name="packaging_material"))
  s=rbind(s,data.frame(iesname="b34f008",name="toilet_paper"))
  s=rbind(s,data.frame(iesname="b34f009",name="dinnerware_disposable"))
  s=rbind(s,data.frame(iesname="b34f010",name="other_cleaning_items"))
  s=rbind(s,data.frame(iesname="b34f100",name="total_cleaning_items"))
  s=rbind(s,data.frame(iesname="b35f001",name="laundrynappy_services"))
  s=rbind(s,data.frame(iesname="b35f002",name="dry_cleaning_services"))
  s=rbind(s,data.frame(iesname="b35f003",name="fumigation_and_cleaning_services"))
  s=rbind(s,data.frame(iesname="b35f004",name="hiring_of_furniture"))
  s=rbind(s,data.frame(iesname="b35f005",name="graingrinding"))
  s=rbind(s,data.frame(iesname="b35f006",name="other_household_services"))
  s=rbind(s,data.frame(iesname="b35f100",name="total_household_services"))
  s=rbind(s,data.frame(iesname="b36f001",name="firewood"))
  s=rbind(s,data.frame(iesname="b36f002",name="charcoal"))
  s=rbind(s,data.frame(iesname="b36f003",name="paraffin"))
  s=rbind(s,data.frame(iesname="b36f004",name="gas_in_cylinders"))
  s=rbind(s,data.frame(iesname="b36f005",name="candles"))
  s=rbind(s,data.frame(iesname="b36f006",name="coal"))
  s=rbind(s,data.frame(iesname="b36f007",name="lawnmower_heating"))
  s=rbind(s,data.frame(iesname="b36f008",name="recharging_wet_cells"))
  s=rbind(s,data.frame(iesname="b36f009",name="dry_cells"))
  s=rbind(s,data.frame(iesname="b36f010",name="dung"))
  s=rbind(s,data.frame(iesname="b36f011",name="crop_waste"))
  s=rbind(s,data.frame(iesname="b36f012",name="other_household_fuel"))
  s=rbind(s,data.frame(iesname="b36f100",name="total_household_fuel"))
  s=rbind(s,data.frame(iesname="b37f001",name="womens_dress"))
  s=rbind(s,data.frame(iesname="b37f002",name="womens_blouse"))
  s=rbind(s,data.frame(iesname="b37f003",name="womens_jacket"))
  s=rbind(s,data.frame(iesname="b37f004",name="womens_sports_clothing"))
  s=rbind(s,data.frame(iesname="b37f005",name="womens_sweater"))
  s=rbind(s,data.frame(iesname="b37f006",name="womens_sleepwear"))
  s=rbind(s,data.frame(iesname="b37f007",name="womens_underwear"))
  s=rbind(s,data.frame(iesname="b37f008",name="womens_stockings"))
  s=rbind(s,data.frame(iesname="b37f009",name="other_unknown"))
  s=rbind(s,data.frame(iesname="b37f010",name="other_womens_clothing"))
  s=rbind(s,data.frame(iesname="b37f100",name="total_womens_clothing"))
  s=rbind(s,data.frame(iesname="b38f001",name="girls_dress"))
  s=rbind(s,data.frame(iesname="b38f002",name="girls_blouse"))
  s=rbind(s,data.frame(iesname="b38f003",name="girls_jacket"))
  s=rbind(s,data.frame(iesname="b38f004",name="girls_sports_clothing"))
  s=rbind(s,data.frame(iesname="b38f005",name="girls_sweater"))
  s=rbind(s,data.frame(iesname="b38f006",name="girls_sleepwear"))
  s=rbind(s,data.frame(iesname="b38f007",name="girls_underwear"))
  s=rbind(s,data.frame(iesname="b38f008",name="girls_stockings"))
  s=rbind(s,data.frame(iesname="b38f009",name="girls_schoolwear"))
  s=rbind(s,data.frame(iesname="b38f010",name="other_girls_clothing"))
  s=rbind(s,data.frame(iesname="b38f100",name="total_girls_clothing"))
  s=rbind(s,data.frame(iesname="b39f001",name="mens_trouser"))
  s=rbind(s,data.frame(iesname="b39f002",name="mens_shirt"))
  s=rbind(s,data.frame(iesname="b39f003",name="mens_jacket"))
  s=rbind(s,data.frame(iesname="b39f004",name="mens_sports_clothing"))
  s=rbind(s,data.frame(iesname="b39f005",name="mens_sweater"))
  s=rbind(s,data.frame(iesname="b39f006",name="mens_pyjama"))
  s=rbind(s,data.frame(iesname="b39f007",name="mens_sock"))
  s=rbind(s,data.frame(iesname="b39f008",name="mens_underwear"))
  s=rbind(s,data.frame(iesname="b39f009",name="other_unknown"))
  s=rbind(s,data.frame(iesname="b39f010",name="other_mens_clothing"))
  s=rbind(s,data.frame(iesname="b39f100",name="total_mens_clothing"))
  s=rbind(s,data.frame(iesname="b40f001",name="boys_trouser"))
  s=rbind(s,data.frame(iesname="b40f002",name="boys_shirt"))
  s=rbind(s,data.frame(iesname="b40f003",name="boys_jacket"))
  s=rbind(s,data.frame(iesname="b40f004",name="boys_sports_clothing"))
  s=rbind(s,data.frame(iesname="b40f005",name="boys_sweater"))
  s=rbind(s,data.frame(iesname="b40f006",name="boys_pyjama"))
  s=rbind(s,data.frame(iesname="b40f007",name="boys_sock"))
  s=rbind(s,data.frame(iesname="b40f008",name="boys_underwear"))
  s=rbind(s,data.frame(iesname="b40f009",name="boys_schoolwear"))
  s=rbind(s,data.frame(iesname="b40f010",name="other_boys_clothing"))
  s=rbind(s,data.frame(iesname="b40f100",name="total_boys_clothing"))
  s=rbind(s,data.frame(iesname="b41f001",name="nappies_infant"))
  s=rbind(s,data.frame(iesname="b41f002",name="nappies_babygrows"))
  s=rbind(s,data.frame(iesname="b41f003",name="other_infants_clothing"))
  s=rbind(s,data.frame(iesname="b41f100",name="total_infants_clothing"))
  s=rbind(s,data.frame(iesname="b42f001",name="womens_boots"))
  s=rbind(s,data.frame(iesname="b42f002",name="womens_leather_shoes"))
  s=rbind(s,data.frame(iesname="b42f003",name="other_womens_shoes_and_sandals"))
  s=rbind(s,data.frame(iesname="b42f004",name="womens_joggers"))
  s=rbind(s,data.frame(iesname="b42f005",name="other_womens_footwear"))
  s=rbind(s,data.frame(iesname="b42f006",name="womens_footwear_repairs"))
  s=rbind(s,data.frame(iesname="b42f100",name="total_womens_footwear"))
  s=rbind(s,data.frame(iesname="b42f200",name="total_infants_footwear"))
  s=rbind(s,data.frame(iesname="b43f001",name="girls_boots"))
  s=rbind(s,data.frame(iesname="b43f002",name="girls_leather_shoes"))
  s=rbind(s,data.frame(iesname="b43f003",name="other_girls_shoes"))
  s=rbind(s,data.frame(iesname="b43f004",name="girls_joggers"))
  s=rbind(s,data.frame(iesname="b43f005",name="other_girls_footwear"))
  s=rbind(s,data.frame(iesname="b43f006",name="girls_footwear_repairs"))
  s=rbind(s,data.frame(iesname="b43f100",name="total_girls_footwear"))
  s=rbind(s,data.frame(iesname="b44f001",name="mens_boots"))
  s=rbind(s,data.frame(iesname="b44f002",name="mens_leather_shoes"))
  s=rbind(s,data.frame(iesname="b44f003",name="other_mens_shoes"))
  s=rbind(s,data.frame(iesname="b44f004",name="mens_joggers"))
  s=rbind(s,data.frame(iesname="b44f005",name="other_mens_footwear"))
  s=rbind(s,data.frame(iesname="b44f006",name="mens_footwear_repairs"))
  s=rbind(s,data.frame(iesname="b44f100",name="total_mens_footwear"))
  s=rbind(s,data.frame(iesname="b45f001",name="boys_boots"))
  s=rbind(s,data.frame(iesname="b45f002",name="boys_leather_shoes"))
  s=rbind(s,data.frame(iesname="b45f003",name="other_boys_shoes"))
  s=rbind(s,data.frame(iesname="b45f004",name="boys_joggers"))
  s=rbind(s,data.frame(iesname="b45f005",name="other_boys_footwear"))
  s=rbind(s,data.frame(iesname="b45f006",name="boys_footwear_repairs"))
  s=rbind(s,data.frame(iesname="b45f100",name="total_boys_footwear"))
  s=rbind(s,data.frame(iesname="b46f001",name="material_for_clothing"))
  s=rbind(s,data.frame(iesname="b46f002",name="wool"))
  s=rbind(s,data.frame(iesname="b46f003",name="patterns_sewing_cotton"))
  s=rbind(s,data.frame(iesname="b46f004",name="madeclothes_repairs"))
  s=rbind(s,data.frame(iesname="b46f005",name="hire_of_clothing"))
  s=rbind(s,data.frame(iesname="b46f100",name="total_madeclothes_repairs"))
  s=rbind(s,data.frame(iesname="b47f001",name="bed_bases_matresses"))
  s=rbind(s,data.frame(iesname="b47f002",name="other_bedroom_furniture"))
  s=rbind(s,data.frame(iesname="b47f003",name="diningroom_furniture"))
  s=rbind(s,data.frame(iesname="b47f004",name="lounge_furniture"))
  s=rbind(s,data.frame(iesname="b47f005",name="kitchen_furniture_units"))
  s=rbind(s,data.frame(iesname="b47f006",name="garden_furniture"))
  s=rbind(s,data.frame(iesname="b47f007",name="other_furniture"))
  s=rbind(s,data.frame(iesname="b47f008",name="loose_carpetsrugs"))
  s=rbind(s,data.frame(iesname="b47f009",name="floor_coverings_other"))
  s=rbind(s,data.frame(iesname="b47f010",name="furniture_other"))
  s=rbind(s,data.frame(iesname="b47f011",name="upholsteringrepair_costs"))
  s=rbind(s,data.frame(iesname="b47f100",name="total_furniture_costs"))
  s=rbind(s,data.frame(iesname="b48f001",name="blankets"))
  s=rbind(s,data.frame(iesname="b48f002",name="sheets"))
  s=rbind(s,data.frame(iesname="b48f003",name="duvet"))
  s=rbind(s,data.frame(iesname="b48f004",name="tablecloths"))
  s=rbind(s,data.frame(iesname="b48f005",name="towels"))
  s=rbind(s,data.frame(iesname="b48f006",name="curtain"))
  s=rbind(s,data.frame(iesname="b48f007",name="pillow"))
  s=rbind(s,data.frame(iesname="b48f008",name="other_household_textiles"))
  s=rbind(s,data.frame(iesname="b48f100",name="total_household_textiles"))
  s=rbind(s,data.frame(iesname="b49f001",name="refrigerator"))
  s=rbind(s,data.frame(iesname="b49f002",name="oven"))
  s=rbind(s,data.frame(iesname="b49f003",name="hotplate"))
  s=rbind(s,data.frame(iesname="b49f004",name="washingmachine_dishwasher"))
  s=rbind(s,data.frame(iesname="b49f005",name="vaccuum_cleaner"))
  s=rbind(s,data.frame(iesname="b49f006",name="iron"))
  s=rbind(s,data.frame(iesname="b49f007",name="kettle"))
  s=rbind(s,data.frame(iesname="b49f008",name="sewing_machine"))
  s=rbind(s,data.frame(iesname="b49f009",name="food_processor"))
  s=rbind(s,data.frame(iesname="b49f010",name="frying_pan"))
  s=rbind(s,data.frame(iesname="b49f011",name="toaster"))
  s=rbind(s,data.frame(iesname="b49f012",name="electric_lawnmower"))
  s=rbind(s,data.frame(iesname="b49f013",name="other_electrical_appliances"))
  s=rbind(s,data.frame(iesname="b49f014",name="gas_stove"))
  s=rbind(s,data.frame(iesname="b49f015",name="paraffin_stove"))
  s=rbind(s,data.frame(iesname="b49f016",name="nonelectrical_sewing"))
  s=rbind(s,data.frame(iesname="b49f017",name="petrol_lawn_mower"))
  s=rbind(s,data.frame(iesname="b49f018",name="other_nonelectrical_appliances"))
  s=rbind(s,data.frame(iesname="b49f019",name="repairs_to_appliances"))
  s=rbind(s,data.frame(iesname="b49f100",name="total_appliances"))
  s=rbind(s,data.frame(iesname="b50f001",name="kitchen_tableware"))
  s=rbind(s,data.frame(iesname="b50f002",name="lighting_household"))
  s=rbind(s,data.frame(iesname="b50f003",name="laundrygoods"))
  s=rbind(s,data.frame(iesname="b50f004",name="gardening"))
  s=rbind(s,data.frame(iesname="b50f005",name="other_household_equipment"))
  s=rbind(s,data.frame(iesname="b50f100",name="total_other_household_equipment"))
  s=rbind(s,data.frame(iesname="b51f001",name="medical_aid_paid_by_respondent"))
  s=rbind(s,data.frame(iesname="b51f002",name="medical_aid_paid_by_employer"))
  s=rbind(s,data.frame(iesname="b51f003",name="medical_services_member"))
  s=rbind(s,data.frame(iesname="b51f004",name="medicine_member"))
  s=rbind(s,data.frame(iesname="b51f005",name="health_services_medicine_member"))
  s=rbind(s,data.frame(iesname="b51f006",name="therapeutic_appliances_member"))
  s=rbind(s,data.frame(iesname="b51f007",name="medicine_without_prescription_member"))
  s=rbind(s,data.frame(iesname="b51f100",name="total_health_services_medical_requisites_member"))
  s=rbind(s,data.frame(iesname="b52f001",name="hospital_services_medicine_non_member"))
  s=rbind(s,data.frame(iesname="b52f002",name="health_practitioners_non_member"))
  s=rbind(s,data.frame(iesname="b52f003",name="traditional_healers_non_member"))
  s=rbind(s,data.frame(iesname="b52f004",name="hospitals"))
  s=rbind(s,data.frame(iesname="b52f005",name="therapists_non_member"))
  s=rbind(s,data.frame(iesname="b52f006",name="prescription_medicine_non_member"))
  s=rbind(s,data.frame(iesname="b52f007",name="non_prescription_medicine_non_member"))
  s=rbind(s,data.frame(iesname="b52f008",name="therapeutic_applicances_non_member"))
  s=rbind(s,data.frame(iesname="b52f100",name="totalmedical_expenditure_non_member"))
  s=rbind(s,data.frame(iesname="b53f001",name="motor_cars_new"))
  s=rbind(s,data.frame(iesname="b53f002",name="bakkies_new"))
  s=rbind(s,data.frame(iesname="b53f003",name="motor_cycles_new"))
  s=rbind(s,data.frame(iesname="b53f004",name="bicycles_new"))
  s=rbind(s,data.frame(iesname="b53f005",name="caravantrailers_new"))
  s=rbind(s,data.frame(iesname="b53f100",name="total_new_vehicles"))
  s=rbind(s,data.frame(iesname="b54f001",name="motor_cars_used"))
  s=rbind(s,data.frame(iesname="b54f002",name="bakkies_used"))
  s=rbind(s,data.frame(iesname="b54f003",name="motor_cycles_used"))
  s=rbind(s,data.frame(iesname="b54f004",name="bicycles_used"))
  s=rbind(s,data.frame(iesname="b54f005",name="caravanstrailers_used"))
  s=rbind(s,data.frame(iesname="b54f100",name="total_used_vehicles"))
  s=rbind(s,data.frame(iesname="b55f001",name="company_vehicle"))
  s=rbind(s,data.frame(iesname="b55f002",name="motor_car_fuel"))
  s=rbind(s,data.frame(iesname="b55f003",name="parking_fees"))
  s=rbind(s,data.frame(iesname="b55f004",name="traffic_fines"))
  s=rbind(s,data.frame(iesname="b55f005",name="toll_fees"))
  s=rbind(s,data.frame(iesname="b55f006",name="lubricant"))
  s=rbind(s,data.frame(iesname="b55f007",name="tyres_new"))
  s=rbind(s,data.frame(iesname="b55f008",name="tyres_retreaded"))
  s=rbind(s,data.frame(iesname="b55f009",name="batteries"))
  s=rbind(s,data.frame(iesname="b55f010",name="spareparts"))
  s=rbind(s,data.frame(iesname="b55f011",name="maintenance"))
  s=rbind(s,data.frame(iesname="b55f012",name="airconditioning_security"))
  s=rbind(s,data.frame(iesname="b55f013",name="panel_beating_paid_by_respondent"))
  s=rbind(s,data.frame(iesname="b55f014",name="panel_beating_paid_by_insurance_company"))
  s=rbind(s,data.frame(iesname="b55f015",name="other_repairs_paid_by_respondent"))
  s=rbind(s,data.frame(iesname="b55f016",name="other_repairs_paid_by_insurance_company"))
  s=rbind(s,data.frame(iesname="b55f017",name="licenseregistration"))
  s=rbind(s,data.frame(iesname="b55f018",name="driving_lessons"))
  s=rbind(s,data.frame(iesname="b55f019",name="other_transport_costs"))
  s=rbind(s,data.frame(iesname="b55f100",name="total_transport_costs"))
  s=rbind(s,data.frame(iesname="b56f001",name="bus_transport"))
  s=rbind(s,data.frame(iesname="b56f002",name="train_transport"))
  s=rbind(s,data.frame(iesname="b56f003",name="metred_taxi_transport"))
  s=rbind(s,data.frame(iesname="b56f004",name="other_rented_vehicles"))
  s=rbind(s,data.frame(iesname="b56f005",name="transport_tariffs"))
  s=rbind(s,data.frame(iesname="b56f006",name="transport_of_goods"))
  s=rbind(s,data.frame(iesname="b56f007",name="other_public_transport"))
  s=rbind(s,data.frame(iesname="b56f100",name="total_public_transport"))
  s=rbind(s,data.frame(iesname="b57f001",name="bus_transport_for_holidays"))
  s=rbind(s,data.frame(iesname="b57f002",name="train_transport_for_holidays"))
  s=rbind(s,data.frame(iesname="b57f003",name="boat_transport_for_holidays"))
  s=rbind(s,data.frame(iesname="b57f004",name="air_transport_for_holidays"))
  s=rbind(s,data.frame(iesname="b57f005",name="taxi_transport_for_holidays"))
  s=rbind(s,data.frame(iesname="b57f006",name="other_holiday_transport"))
  s=rbind(s,data.frame(iesname="b57f007",name="rented_holiday_transport"))
  s=rbind(s,data.frame(iesname="b57f100",name="total_holiday_transport"))
  s=rbind(s,data.frame(iesname="b58f001",name="computers"))
  s=rbind(s,data.frame(iesname="b58f002",name="communication_equipment"))
  s=rbind(s,data.frame(iesname="b58f003",name="two_way_radios"))
  s=rbind(s,data.frame(iesname="b58f100",name="total_computer"))
  s=rbind(s,data.frame(iesname="b59f001",name="telephonerental"))
  s=rbind(s,data.frame(iesname="b59f002",name="private_telephone_calls"))
  s=rbind(s,data.frame(iesname="b59f003",name="public_telephone_calls"))
  s=rbind(s,data.frame(iesname="b59f004",name="vat_telephone_fees"))
  s=rbind(s,data.frame(iesname="b59f005",name="cellular_network_link"))
  s=rbind(s,data.frame(iesname="b59f006",name="internet_subscription"))
  s=rbind(s,data.frame(iesname="b59f007",name="postage"))
  s=rbind(s,data.frame(iesname="b59f008",name="other_household_communication"))
  s=rbind(s,data.frame(iesname="b59f100",name="total_household_communication"))
  s=rbind(s,data.frame(iesname="b60f001",name="day_care_respondent"))
  s=rbind(s,data.frame(iesname="b60f002",name="pre_and_after_school_care_respondent"))
  s=rbind(s,data.frame(iesname="b60f003",name="schooltuition_respondent"))
  s=rbind(s,data.frame(iesname="b60f004",name="trainingcollege_costs_respondent"))
  s=rbind(s,data.frame(iesname="b60f005",name="universityfees_respondent"))
  s=rbind(s,data.frame(iesname="b60f006",name="privatetuition_fees_respondent"))
  s=rbind(s,data.frame(iesname="b60f007",name="school_boarding_fees_respondent"))
  s=rbind(s,data.frame(iesname="b60f008",name="other_educational_institutions_respondent"))
  s=rbind(s,data.frame(iesname="b60f009",name="textbooks_respondent"))
  s=rbind(s,data.frame(iesname="b60f010",name="stationery_respondent"))
  s=rbind(s,data.frame(iesname="b60f011",name="othereducation_expenses_paid_by_respondent"))
  s=rbind(s,data.frame(iesname="b60f100",name="totaleducation_expenses_paid_by_respondent"))
  s=rbind(s,data.frame(iesname="b61f001",name="daycare_paid_by_grants"))
  s=rbind(s,data.frame(iesname="b61f002",name="pre_and_after_school_care_paid_by_grants"))
  s=rbind(s,data.frame(iesname="b61f003",name="schooltuition_paid_by_grants"))
  s=rbind(s,data.frame(iesname="b61f004",name="trainingcollege_costs_paid_by_grants"))
  s=rbind(s,data.frame(iesname="b61f005",name="universityfees_paid_by_grants"))
  s=rbind(s,data.frame(iesname="b61f006",name="privatetuition_paid_by_grants"))
  s=rbind(s,data.frame(iesname="b61f007",name="schoolboarding_fees_paid_by_grants"))
  s=rbind(s,data.frame(iesname="b61f008",name="othercosts_of_educational_institutions_grants"))
  s=rbind(s,data.frame(iesname="b61f009",name="textbooks_grants"))
  s=rbind(s,data.frame(iesname="b61f010",name="stationery_grants"))
  s=rbind(s,data.frame(iesname="b61f011",name="other_education_expenses_paid_by_grants"))
  s=rbind(s,data.frame(iesname="b61f100",name="total_education_expenses_paid_by_grants"))
  s=rbind(s,data.frame(iesname="b62f001",name="newspapers"))
  s=rbind(s,data.frame(iesname="b62f002",name="magazines_periodicals"))
  s=rbind(s,data.frame(iesname="b62f003",name="books"))
  s=rbind(s,data.frame(iesname="b62f004",name="libraryfees"))
  s=rbind(s,data.frame(iesname="b62f005",name="stationery"))
  s=rbind(s,data.frame(iesname="b62f100",name="total_reading_matter"))
  s=rbind(s,data.frame(iesname="b63f001",name="musical_instruments"))
  s=rbind(s,data.frame(iesname="b63f002",name="television_video_equipment"))
  s=rbind(s,data.frame(iesname="b63f003",name="radios_tape_recorders"))
  s=rbind(s,data.frame(iesname="b63f004",name="tapes_compact_disks"))
  s=rbind(s,data.frame(iesname="b63f005",name="photographic_equipment"))
  s=rbind(s,data.frame(iesname="b63f006",name="aircraft_boats"))
  s=rbind(s,data.frame(iesname="b63f007",name="sports_equipment"))
  s=rbind(s,data.frame(iesname="b63f008",name="camping_equipment"))
  s=rbind(s,data.frame(iesname="b63f009",name="tools"))
  s=rbind(s,data.frame(iesname="b63f010",name="repairs_recreational_equipment"))
  s=rbind(s,data.frame(iesname="b63f100",name="total_recreational_equipment"))
  s=rbind(s,data.frame(iesname="b64f001",name="pool_equipment"))
  s=rbind(s,data.frame(iesname="b64f002",name="gardening_requirements"))
  s=rbind(s,data.frame(iesname="b64f003",name="pet"))
  s=rbind(s,data.frame(iesname="b64f004",name="cut_flowers"))
  s=rbind(s,data.frame(iesname="b64f005",name="hobbietoys"))
  s=rbind(s,data.frame(iesname="b64f006",name="other_recreational_items"))
  s=rbind(s,data.frame(iesname="b64f100",name="total_recreational_items"))
  s=rbind(s,data.frame(iesname="b65f001",name="television_licenses"))
  s=rbind(s,data.frame(iesname="b65f002",name="televisionrental"))
  s=rbind(s,data.frame(iesname="b65f003",name="paytv_subscription"))
  s=rbind(s,data.frame(iesname="b65f004",name="rentfor_video"))
  s=rbind(s,data.frame(iesname="b65f005",name="admissioncharges"))
  s=rbind(s,data.frame(iesname="b65f006",name="pet_licenses"))
  s=rbind(s,data.frame(iesname="b65f007",name="pet_care"))
  s=rbind(s,data.frame(iesname="b65f008",name="garden_pool_maintenance"))
  s=rbind(s,data.frame(iesname="b65f009",name="film_development"))
  s=rbind(s,data.frame(iesname="b65f010",name="fees_recreational_lessons"))
  s=rbind(s,data.frame(iesname="b65f011",name="other_recreational_expenses"))
  s=rbind(s,data.frame(iesname="b65f100",name="total_recreational_expenses"))
  s=rbind(s,data.frame(iesname="b66f001",name="jewelry"))
  s=rbind(s,data.frame(iesname="b66f002",name="handbags"))
  s=rbind(s,data.frame(iesname="b66f003",name="pram"))
  s=rbind(s,data.frame(iesname="b66f004",name="other_items"))
  s=rbind(s,data.frame(iesname="b66f100",name="total_miscellaneous_expenditure"))
  s=rbind(s,data.frame(iesname="b67f001",name="maintenance_alimony"))
  s=rbind(s,data.frame(iesname="b67f002",name="gifts"))
  s=rbind(s,data.frame(iesname="b67f003",name="tribal_levies"))
  s=rbind(s,data.frame(iesname="b67f004",name="membership_fees_for_trade_unions"))
  s=rbind(s,data.frame(iesname="b67f005",name="membership_fees_of_health_clubs"))
  s=rbind(s,data.frame(iesname="b67f006",name="pocket_money"))
  s=rbind(s,data.frame(iesname="b67f007",name="donations_churches"))
  s=rbind(s,data.frame(iesname="b67f008",name="other_donations"))
  s=rbind(s,data.frame(iesname="b67f100",name="total_membership_fees_donations"))
  s=rbind(s,data.frame(iesname="b68f001",name="paye_site"))
  s=rbind(s,data.frame(iesname="b68f002",name="othertax_payments"))
  s=rbind(s,data.frame(iesname="b68f003",name="taxrefunds"))
  s=rbind(s,data.frame(iesname="b68f100",name="nettaxation"))
  s=rbind(s,data.frame(iesname="b69f001",name="bankcharges"))
  s=rbind(s,data.frame(iesname="b69f002",name="financecharges"))
  s=rbind(s,data.frame(iesname="b69f003",name="loanrepayments"))
  s=rbind(s,data.frame(iesname="b69f004",name="life_endowmentpolicies"))
  s=rbind(s,data.frame(iesname="b69f005",name="funeral_policies"))
  s=rbind(s,data.frame(iesname="b69f006",name="accident_policies"))
  s=rbind(s,data.frame(iesname="b69f007",name="medical_insurance"))
  s=rbind(s,data.frame(iesname="b69f008",name="insurance_of_buildings"))
  s=rbind(s,data.frame(iesname="b69f009",name="insurance_mortgage_debt"))
  s=rbind(s,data.frame(iesname="b69f010",name="insurance_contents"))
  s=rbind(s,data.frame(iesname="b69f011",name="insurance_motor_vehicle"))
  s=rbind(s,data.frame(iesname="b69f012",name="insurance_comprehensive"))
  s=rbind(s,data.frame(iesname="b69f013",name="pf_contributionto_paid_by_respondent"))
  s=rbind(s,data.frame(iesname="b69f014",name="employer_contribution_to_pf"))
  s=rbind(s,data.frame(iesname="b69f015",name="stokvel_contribution"))
  s=rbind(s,data.frame(iesname="b69f016",name="sharesunit_trusts"))
  s=rbind(s,data.frame(iesname="b69f017",name="investment_plans"))
  s=rbind(s,data.frame(iesname="b69f018",name="savings"))
  s=rbind(s,data.frame(iesname="b69f100",name="total_finance_and_insurance_costs"))
  s=rbind(s,data.frame(iesname="b70f001",name="professionalfees"))
  s=rbind(s,data.frame(iesname="b70f002",name="lobola_dowry_paid"))
  s=rbind(s,data.frame(iesname="b70f003",name="funeral"))
  s=rbind(s,data.frame(iesname="b70f004",name="grave"))
  s=rbind(s,data.frame(iesname="b70f005",name="religious_traditional_ceremonies"))
  s=rbind(s,data.frame(iesname="b70f006",name="fines_excluding_traffic_and_library_fines"))
  s=rbind(s,data.frame(iesname="b70f007",name="other_miscellaneous_expenditure"))
  s=rbind(s,data.frame(iesname="b70f008",name="other_expenditure_not_elsewhere_shown"))
  s=rbind(s,data.frame(iesname="b70f100",name="total_other_miscellaneous_expenditure"))
  s=rbind(s,data.frame(iesname="b71f001",name="expenditure_working_for_own_account"))
  s=rbind(s,data.frame(iesname="b72f001",name="maizeproduction"))
  s=rbind(s,data.frame(iesname="b72f002",name="othergrain_production"))
  s=rbind(s,data.frame(iesname="b72f003",name="milkproduction"))
  s=rbind(s,data.frame(iesname="b72f004",name="eggproduction"))
  s=rbind(s,data.frame(iesname="b72f005",name="deciduousfruit_production"))
  s=rbind(s,data.frame(iesname="b72f006",name="bananaproduction"))
  s=rbind(s,data.frame(iesname="b72f007",name="productionof_other_subtropical_fruit"))
  s=rbind(s,data.frame(iesname="b72f008",name="citrusfruit_production"))
  s=rbind(s,data.frame(iesname="b72f009",name="productionof_other_fruit"))
  s=rbind(s,data.frame(iesname="b72f010",name="productionof_potatoes"))
  s=rbind(s,data.frame(iesname="b72f011",name="productionof_sweet_potatoes"))
  s=rbind(s,data.frame(iesname="b72f012",name="productionof_green_mielies"))
  s=rbind(s,data.frame(iesname="b72f013",name="productionof_onions"))
  s=rbind(s,data.frame(iesname="b72f014",name="productionof_tomatoes"))
  s=rbind(s,data.frame(iesname="b72f015",name="productionof_cabbages"))
  s=rbind(s,data.frame(iesname="b72f016",name="productionof_marrows"))
  s=rbind(s,data.frame(iesname="b72f017",name="productionof_marogo"))
  s=rbind(s,data.frame(iesname="b72f018",name="productionof_other_vegetables"))
  s=rbind(s,data.frame(iesname="b72f100",name="totalfood_production"))
  s=rbind(s,data.frame(iesname="b73f001",name="consumption_maize"))
  s=rbind(s,data.frame(iesname="b73f002",name="consumption_other_grains"))
  s=rbind(s,data.frame(iesname="b73f003",name="consumption_milk"))
  s=rbind(s,data.frame(iesname="b73f004",name="consumption_eggs"))
  s=rbind(s,data.frame(iesname="b73f005",name="consumption_deciduous_fruit"))
  s=rbind(s,data.frame(iesname="b73f006",name="consumption_bananas"))
  s=rbind(s,data.frame(iesname="b73f007",name="consumption_other_subtropical_fruit"))
  s=rbind(s,data.frame(iesname="b73f008",name="consumption_citrus_fruit"))
  s=rbind(s,data.frame(iesname="b73f009",name="consumption_other_fruit"))
  s=rbind(s,data.frame(iesname="b73f010",name="consumption_potatoes"))
  s=rbind(s,data.frame(iesname="b73f011",name="consumption_sweet_potatoes"))
  s=rbind(s,data.frame(iesname="b73f012",name="consumption_green_mielies"))
  s=rbind(s,data.frame(iesname="b73f013",name="consumption_onions"))
  s=rbind(s,data.frame(iesname="b73f014",name="consumption_tomatoes"))
  s=rbind(s,data.frame(iesname="b73f015",name="consumption_cabbage"))
  s=rbind(s,data.frame(iesname="b73f016",name="consumption_marrows"))
  s=rbind(s,data.frame(iesname="b73f017",name="consumption_marogo"))
  s=rbind(s,data.frame(iesname="b73f018",name="consumption_other_vegetables"))
  s=rbind(s,data.frame(iesname="b73f100",name="total_consumption_of_food_produced"))
  s=rbind(s,data.frame(iesname="b74f001",name="maize_sold"))
  s=rbind(s,data.frame(iesname="b74f002",name="othergrains_sold"))
  s=rbind(s,data.frame(iesname="b74f003",name="milk_sold"))
  s=rbind(s,data.frame(iesname="b74f004",name="eggs_sold"))
  s=rbind(s,data.frame(iesname="b74f005",name="deciduousfruit_sold"))
  s=rbind(s,data.frame(iesname="b74f006",name="bananas_sold"))
  s=rbind(s,data.frame(iesname="b74f007",name="othersubtropical_fruit_sold"))
  s=rbind(s,data.frame(iesname="b74f008",name="citrusfruit_sold"))
  s=rbind(s,data.frame(iesname="b74f009",name="otherfruit_sold"))
  s=rbind(s,data.frame(iesname="b74f010",name="potatoes_sold"))
  s=rbind(s,data.frame(iesname="b74f011",name="sweetpotatoes_sold"))
  s=rbind(s,data.frame(iesname="b74f012",name="greenmielies_sold"))
  s=rbind(s,data.frame(iesname="b74f013",name="onions_sold"))
  s=rbind(s,data.frame(iesname="b74f014",name="tomatoes_sold"))
  s=rbind(s,data.frame(iesname="b74f015",name="cabbage_sold"))
  s=rbind(s,data.frame(iesname="b74f016",name="marrows_sold"))
  s=rbind(s,data.frame(iesname="b74f017",name="marogo_spinach_imifino_sold"))
  s=rbind(s,data.frame(iesname="b74f018",name="other_vegetables_sold"))
  s=rbind(s,data.frame(iesname="b74f100",name="total_food_products_sold"))
  s=rbind(s,data.frame(iesname="b75f001",name="value_maize_sales"))
  s=rbind(s,data.frame(iesname="b75f002",name="value_other_grain_sales"))
  s=rbind(s,data.frame(iesname="b75f003",name="value_milk_sales"))
  s=rbind(s,data.frame(iesname="b75f004",name="value_egg_sales"))
  s=rbind(s,data.frame(iesname="b75f005",name="value_deciduous_fruit_sales"))
  s=rbind(s,data.frame(iesname="b75f006",name="value_banana_sales"))
  s=rbind(s,data.frame(iesname="b75f007",name="value_other_subtropical_fruit_sales"))
  s=rbind(s,data.frame(iesname="b75f008",name="value_citrus_fruit_sales"))
  s=rbind(s,data.frame(iesname="b75f009",name="value_other_fruit_sales"))
  s=rbind(s,data.frame(iesname="b75f010",name="value_potato_sales"))
  s=rbind(s,data.frame(iesname="b75f011",name="value_sweet_potato_sales"))
  s=rbind(s,data.frame(iesname="b75f012",name="value_green_mielie_sales"))
  s=rbind(s,data.frame(iesname="b75f013",name="value_onion_sales"))
  s=rbind(s,data.frame(iesname="b75f014",name="value_tomato_sales"))
  s=rbind(s,data.frame(iesname="b75f015",name="value_cabbage_sales"))
  s=rbind(s,data.frame(iesname="b75f016",name="value_marrow_sales"))
  s=rbind(s,data.frame(iesname="b75f017",name="value_spinach"))
  s=rbind(s,data.frame(iesname="b75f018",name="value_other_vegetable_sales"))
  s=rbind(s,data.frame(iesname="b75f100",name="totalvalue_of_food_sales"))
  s=rbind(s,data.frame(iesname="b76f001",name="cattle_produced"))
  s=rbind(s,data.frame(iesname="b76f002",name="sheep_produced"))
  s=rbind(s,data.frame(iesname="b76f003",name="goats_produced"))
  s=rbind(s,data.frame(iesname="b76f004",name="chickens_produced"))
  s=rbind(s,data.frame(iesname="b77f001",name="cattle_owned_now"))
  s=rbind(s,data.frame(iesname="b77f002",name="sheep_owned_now"))
  s=rbind(s,data.frame(iesname="b77f003",name="goats_owned_now"))
  s=rbind(s,data.frame(iesname="b77f004",name="chickens_owned_now"))
  s=rbind(s,data.frame(iesname="b78f001",name="cattle_slaughtered"))
  s=rbind(s,data.frame(iesname="b78f002",name="sheep_slaughtered"))
  s=rbind(s,data.frame(iesname="b78f003",name="goats_slaughtered"))
  s=rbind(s,data.frame(iesname="b78f004",name="chickens_slaughtered"))
  s=rbind(s,data.frame(iesname="b79f001",name="cattle_sold"))
  s=rbind(s,data.frame(iesname="b79f002",name="sheep_sold"))
  s=rbind(s,data.frame(iesname="b79f003",name="goats_sold"))
  s=rbind(s,data.frame(iesname="b79f004",name="chickens_sold"))
  s=rbind(s,data.frame(iesname="b80f001",name="value_cattle_sold"))
  s=rbind(s,data.frame(iesname="b80f002",name="value_sheep_sold"))
  s=rbind(s,data.frame(iesname="b80f003",name="value_goats_sold"))
  s=rbind(s,data.frame(iesname="b80f004",name="value_chickens_sold"))
  s=rbind(s,data.frame(iesname="b80f100",name="total_value_of_livestock_sales"))
  s=rbind(s,data.frame(iesname="b81f001",name="seeds_and_feed_costs"))
  s=rbind(s,data.frame(iesname="b81f002",name="cost_of_services"))
  s=rbind(s,data.frame(iesname="b81f003",name="processing_costs"))
  s=rbind(s,data.frame(iesname="b81f004",name="other_input_costs_of_production"))
  s=rbind(s,data.frame(iesname="b81f100",name="total_input_costs_of_production"))
  s=rbind(s,data.frame(iesname="b82f001",name="bond_repayments"))
  s=rbind(s,data.frame(iesname="b82f002",name="car_repayments"))
  s=rbind(s,data.frame(iesname="b82f003",name="hire_purchase_on_furniture"))
  s=rbind(s,data.frame(iesname="b82f004",name="bankoverdraft_ccpayments"))
  s=rbind(s,data.frame(iesname="b82f005",name="accountsat_retail_stores"))
  s=rbind(s,data.frame(iesname="b82f006",name="loansfrom_friends_or_family"))
  s=rbind(s,data.frame(iesname="b82f100",name="total_debts"))
  s=rbind(s,data.frame(iesname="b83f001",name="wage_household_head"))
  s=rbind(s,data.frame(iesname="b83f002",name="bonuses_overtime_of_household_head"))
  s=rbind(s,data.frame(iesname="b83f003",name="commission_directors_fees_of_household_head"))
  s=rbind(s,data.frame(iesname="b83f004",name="cash_allowances_of_household_head"))
  s=rbind(s,data.frame(iesname="b83f005",name="profit_business_farming_of_household_head"))
  s=rbind(s,data.frame(iesname="b83f006",name="profit_letting_of_property_of_household_head"))
  s=rbind(s,data.frame(iesname="b83f007",name="royalties_household_head"))
  s=rbind(s,data.frame(iesname="b83f008",name="interest_received_by_household_head"))
  s=rbind(s,data.frame(iesname="b83f009",name="dividends_on_shares_of_household_head"))
  s=rbind(s,data.frame(iesname="b83f010",name="pensions_grants_of_household_head"))
  s=rbind(s,data.frame(iesname="b83f011",name="retirement_annuity_of_household_head"))
  s=rbind(s,data.frame(iesname="b83f012",name="oldage_pension_of_household_head"))
  s=rbind(s,data.frame(iesname="b83f013",name="disabilitygrants_of_household_head"))
  s=rbind(s,data.frame(iesname="b83f014",name="other_allowances_of_household_head"))
  s=rbind(s,data.frame(iesname="b83f015",name="workmens_compensation_of_household_head"))
  s=rbind(s,data.frame(iesname="b83f016",name="alimony"))
  s=rbind(s,data.frame(iesname="b83f017",name="allowances_from_family_members_of_household_head"))
  s=rbind(s,data.frame(iesname="b83f100",name="total_income_of_household_head"))
  s=rbind(s,data.frame(iesname="b83f200",name="number_of_household_head"))
  s=rbind(s,data.frame(iesname="b84f001",name="wages_of_spouse"))
  s=rbind(s,data.frame(iesname="b84f002",name="bonuses_of_spouse"))
  s=rbind(s,data.frame(iesname="b84f003",name="commission_directors_fees_of_spouse"))
  s=rbind(s,data.frame(iesname="b84f004",name="cash_allowances_of_spouse"))
  s=rbind(s,data.frame(iesname="b84f005",name="profit_from_business_farming_of_spouse"))
  s=rbind(s,data.frame(iesname="b84f006",name="profit_from_letting_of_property_of_spouse"))
  s=rbind(s,data.frame(iesname="b84f007",name="royalties_of_spouse"))
  s=rbind(s,data.frame(iesname="b84f008",name="interest_received_by_spouse"))
  s=rbind(s,data.frame(iesname="b84f009",name="dividends_on_shares_of_spouse"))
  s=rbind(s,data.frame(iesname="b84f010",name="pensions_of_spouse"))
  s=rbind(s,data.frame(iesname="b84f011",name="retirement_annuity_of_spouse"))
  s=rbind(s,data.frame(iesname="b84f012",name="oldage_pension_of_spouse"))
  s=rbind(s,data.frame(iesname="b84f013",name="disability_of_spouse"))
  s=rbind(s,data.frame(iesname="b84f014",name="family_maintenance_of_spouse"))
  s=rbind(s,data.frame(iesname="b84f015",name="workmens_compensation_of_spouse"))
  s=rbind(s,data.frame(iesname="b84f016",name="alimony_maintenance_of_spouse"))
  s=rbind(s,data.frame(iesname="b84f017",name="allowances_from_family_members_of_spouse"))
  s=rbind(s,data.frame(iesname="b84f100",name="total_income_of_spouse"))
  s=rbind(s,data.frame(iesname="b84f200",name="number_of_spouse"))
  s=rbind(s,data.frame(iesname="b85f001",name="wages_of_member_1"))
  s=rbind(s,data.frame(iesname="b85f002",name="bonuses_overtime_of_member_1"))
  s=rbind(s,data.frame(iesname="b85f003",name="commission_directors_fees_of_member_1"))
  s=rbind(s,data.frame(iesname="b85f004",name="cash_allowances_of_member_1"))
  s=rbind(s,data.frame(iesname="b85f005",name="profit_from_business_farming_of_member_1"))
  s=rbind(s,data.frame(iesname="b85f006",name="profit_from_letting_of_property_of_member_1"))
  s=rbind(s,data.frame(iesname="b85f007",name="royalties_of_member_1"))
  s=rbind(s,data.frame(iesname="b85f008",name="interest_received_by_member_1"))
  s=rbind(s,data.frame(iesname="b85f009",name="dividends_on_shares_of_member_1"))
  s=rbind(s,data.frame(iesname="b85f010",name="pensions_of_member_1"))
  s=rbind(s,data.frame(iesname="b85f011",name="retirement_annuity_of_member_1"))
  s=rbind(s,data.frame(iesname="b85f012",name="oldage_pension_of_member_1"))
  s=rbind(s,data.frame(iesname="b85f013",name="disability_grants_of_member_1"))
  s=rbind(s,data.frame(iesname="b85f014",name="other_allowances_of_member_1"))
  s=rbind(s,data.frame(iesname="b85f015",name="workmens_compensation_of_member_1"))
  s=rbind(s,data.frame(iesname="b85f016",name="alimony_maintenance_of_member_1"))
  s=rbind(s,data.frame(iesname="b85f017",name="allowances_from_family_members_of_member_1"))
  s=rbind(s,data.frame(iesname="b85f100",name="total_income_of_member_1"))
  s=rbind(s,data.frame(iesname="b85f200",name="number_of_member_1"))
  s=rbind(s,data.frame(iesname="b86f001",name="wages_of_member_2"))
  s=rbind(s,data.frame(iesname="b86f002",name="bonuses_of_member_2"))
  s=rbind(s,data.frame(iesname="b86f003",name="commission_directors_fees_of_member_2"))
  s=rbind(s,data.frame(iesname="b86f004",name="cash_allowances_of_member_2"))
  s=rbind(s,data.frame(iesname="b86f005",name="profit_from_business_farming_of_member_2"))
  s=rbind(s,data.frame(iesname="b86f006",name="profit_from_letting_of_property_of_member_2"))
  s=rbind(s,data.frame(iesname="b86f007",name="royalties_of_member_2"))
  s=rbind(s,data.frame(iesname="b86f008",name="interest_received_by_member_2"))
  s=rbind(s,data.frame(iesname="b86f009",name="dividends_on_shares_of_member_2"))
  s=rbind(s,data.frame(iesname="b86f010",name="pensions_of_member_2"))
  s=rbind(s,data.frame(iesname="b86f011",name="retirement_annuity_of_member_2"))
  s=rbind(s,data.frame(iesname="b86f012",name="oldage_pension_of_member_2"))
  s=rbind(s,data.frame(iesname="b86f013",name="disability_of_member_2"))
  s=rbind(s,data.frame(iesname="b86f014",name="other_allowances_of_member_2"))
  s=rbind(s,data.frame(iesname="b86f015",name="workmens_compensation_of_member_2"))
  s=rbind(s,data.frame(iesname="b86f016",name="alimony_maintenance_of_member_2"))
  s=rbind(s,data.frame(iesname="b86f017",name="allowances_from_family_members_of_member_2"))
  s=rbind(s,data.frame(iesname="b86f100",name="total_income_of_member_2"))
  s=rbind(s,data.frame(iesname="b86f200",name="number_of_member_2"))
  s=rbind(s,data.frame(iesname="b87f001",name="wages_of_member_3"))
  s=rbind(s,data.frame(iesname="b87f002",name="bonuses_of_member_3"))
  s=rbind(s,data.frame(iesname="b87f003",name="commission_directors_fees_of_member_3"))
  s=rbind(s,data.frame(iesname="b87f004",name="cash_allowances_of_member_3"))
  s=rbind(s,data.frame(iesname="b87f005",name="profit_from_business_farming_of_member_3"))
  s=rbind(s,data.frame(iesname="b87f006",name="profit_from_letting_of_property_of_member_3"))
  s=rbind(s,data.frame(iesname="b87f007",name="royalties_of_member_3"))
  s=rbind(s,data.frame(iesname="b87f008",name="interest_received_by_member_3"))
  s=rbind(s,data.frame(iesname="b87f009",name="dividends_on_shares_of_member_3"))
  s=rbind(s,data.frame(iesname="b87f010",name="pensions_of_member_3"))
  s=rbind(s,data.frame(iesname="b87f011",name="retirement_annuity_of_member_3"))
  s=rbind(s,data.frame(iesname="b87f012",name="pension_of_member_3"))
  s=rbind(s,data.frame(iesname="b87f013",name="disability_grants_of_member_3"))
  s=rbind(s,data.frame(iesname="b87f014",name="other_allowances_of_member_3"))
  s=rbind(s,data.frame(iesname="b87f015",name="workmenscompensation_of_member_3_discrete_numeric"))
  s=rbind(s,data.frame(iesname="b87f016",name="alimony_maintenance_of_member_3"))
  s=rbind(s,data.frame(iesname="b87f017",name="allowances_from_family_members_of_member_3"))
  s=rbind(s,data.frame(iesname="b87f100",name="total_income_of_member_3"))
  s=rbind(s,data.frame(iesname="b87f200",name="number_of_member_3"))
  s=rbind(s,data.frame(iesname="b88f001",name="income_from_sidelines"))
  s=rbind(s,data.frame(iesname="b88f002",name="income_from_sale_of_vehicles"))
  s=rbind(s,data.frame(iesname="b88f003",name="income_from_sale_of_property"))
  s=rbind(s,data.frame(iesname="b88f004",name="income_from_sale_of_goods"))
  s=rbind(s,data.frame(iesname="b88f005",name="payments_from_boarders"))
  s=rbind(s,data.frame(iesname="b88f006",name="value_of_company_housing"))
  s=rbind(s,data.frame(iesname="b88f007",name="value_of_company_transport"))
  s=rbind(s,data.frame(iesname="b88f008",name="value_of_pension_funds"))
  s=rbind(s,data.frame(iesname="b88f009",name="value_of_other_company_benefits"))
  s=rbind(s,data.frame(iesname="b88f010",name="value_of_lump_sum_payments_from_employer"))
  s=rbind(s,data.frame(iesname="b88f011",name="value_of_endowment_policies"))
  s=rbind(s,data.frame(iesname="b88f012",name="workmenscompensation_payouts"))
  s=rbind(s,data.frame(iesname="b88f013",name="life_insurance_payouts_inheritances"))
  s=rbind(s,data.frame(iesname="b88f014",name="funeralfund_claims"))
  s=rbind(s,data.frame(iesname="b88f015",name="claims_from_property_damage"))
  s=rbind(s,data.frame(iesname="b88f016",name="claims_from_road_accident_funds"))
  s=rbind(s,data.frame(iesname="b88f017",name="income_from_other_gratuities"))
  s=rbind(s,data.frame(iesname="b88f018",name="stokvel_claims"))
  s=rbind(s,data.frame(iesname="b88f019",name="withdrawal_from_savings"))
  s=rbind(s,data.frame(iesname="b88f020",name="income_from_bursaries"))
  s=rbind(s,data.frame(iesname="b88f021",name="income_from_cash_donations"))
  s=rbind(s,data.frame(iesname="b88f022",name="value_food_received"))
  s=rbind(s,data.frame(iesname="b88f023",name="value_housing_received"))
  s=rbind(s,data.frame(iesname="b88f024",name="value_clothing_received"))
  s=rbind(s,data.frame(iesname="b88f025",name="value_other_donations_received"))
  s=rbind(s,data.frame(iesname="b88f026",name="lobola_dowry_received"))
  s=rbind(s,data.frame(iesname="b88f027",name="all_other_income"))
  s=rbind(s,data.frame(iesname="b88f028",name="all_other_income_not_elsewhere_shown"))
  s=rbind(s,data.frame(iesname="b88f100",name="total_income2"))
  s=rbind(s,data.frame(iesname="b89f001",name="cost_housing_monthly"))
  s=rbind(s,data.frame(iesname="b89f002",name="cost_housing_annual"))
  s=rbind(s,data.frame(iesname="b89f003",name="domestic_workers_wages"))
  s=rbind(s,data.frame(iesname="b89f004",name="cereals"))
  s=rbind(s,data.frame(iesname="b89f005",name="meat"))
  s=rbind(s,data.frame(iesname="b89f006",name="fish"))
  s=rbind(s,data.frame(iesname="b89f007",name="fats"))
  s=rbind(s,data.frame(iesname="b89f008",name="milk_eggs"))
  s=rbind(s,data.frame(iesname="b89f009",name="vegetables"))
  s=rbind(s,data.frame(iesname="b89f010",name="fruit_nuts"))
  s=rbind(s,data.frame(iesname="b89f011",name="sugar_products"))
  s=rbind(s,data.frame(iesname="b89f012",name="syrup_jam"))
  s=rbind(s,data.frame(iesname="b89f013",name="beverages"))
  s=rbind(s,data.frame(iesname="b89f014",name="other_food"))
  s=rbind(s,data.frame(iesname="b89f015",name="snacks_consumed_away_from_home"))
  s=rbind(s,data.frame(iesname="b89f016",name="beverages_consumed_away_from_home"))
  s=rbind(s,data.frame(iesname="b89f017",name="beverages"))
  s=rbind(s,data.frame(iesname="b89f018",name="alcohol_consumed_away_from_home"))
  s=rbind(s,data.frame(iesname="b89f019",name="alcohol"))
  s=rbind(s,data.frame(iesname="b89f020",name="tobacco_products"))
  s=rbind(s,data.frame(iesname="b89f021",name="personal_care"))
  s=rbind(s,data.frame(iesname="b89f022",name="household_consumer_goods"))
  s=rbind(s,data.frame(iesname="b89f023",name="household_services"))
  s=rbind(s,data.frame(iesname="b89f024",name="subtotal_expenditure"))
  s=rbind(s,data.frame(iesname="b89f033",name="girls_footwear"))
  s=rbind(s,data.frame(iesname="b89f025",name="subtotal_annual"))
  s=rbind(s,data.frame(iesname="b89f026",name="household_fuel"))
  s=rbind(s,data.frame(iesname="b89f027",name="womens_clothing"))
  s=rbind(s,data.frame(iesname="b89f028",name="girls_clothing"))
  s=rbind(s,data.frame(iesname="b89f029",name="mens_clothing"))
  s=rbind(s,data.frame(iesname="b89f030",name="boys_clothing"))
  s=rbind(s,data.frame(iesname="b89f031",name="infants_clothing"))
  s=rbind(s,data.frame(iesname="b89f032",name="womens_footwear"))
  s=rbind(s,data.frame(iesname="b89f034",name="mens_footwear"))
  s=rbind(s,data.frame(iesname="b89f035",name="boys_footwear"))
  s=rbind(s,data.frame(iesname="b89f036",name="infants_footwear"))
  s=rbind(s,data.frame(iesname="b89f037",name="home_made_clothing_and_repairs"))
  s=rbind(s,data.frame(iesname="b89f038",name="furniture_and_floor_coverings"))
  s=rbind(s,data.frame(iesname="b89f039",name="household_textiles"))
  s=rbind(s,data.frame(iesname="b89f040",name="appliances"))
  s=rbind(s,data.frame(iesname="b89f041",name="other_household_equipment"))
  s=rbind(s,data.frame(iesname="b89f042",name="health_services_member"))
  s=rbind(s,data.frame(iesname="b89f043",name="health_services_non_member"))
  s=rbind(s,data.frame(iesname="b89f044",name="vehicles_purchased"))
  s=rbind(s,data.frame(iesname="b89f045",name="runningcosts_of_vehicles"))
  s=rbind(s,data.frame(iesname="b89f046",name="public_transport"))
  s=rbind(s,data.frame(iesname="b89f047",name="public_transport_away_from_home"))
  s=rbind(s,data.frame(iesname="b89f048",name="telecommunication_equipment"))
  s=rbind(s,data.frame(iesname="b89f049",name="household_communication"))
  s=rbind(s,data.frame(iesname="b89f050",name="cost_education_paid_by_respondent"))
  s=rbind(s,data.frame(iesname="b89f051",name="cost_education_paid_by_grants"))
  s=rbind(s,data.frame(iesname="b89f052",name="stationery"))
  s=rbind(s,data.frame(iesname="b89f053",name="recreational_equipment"))
  s=rbind(s,data.frame(iesname="b89f054",name="other_recreational_goods"))
  s=rbind(s,data.frame(iesname="b89f055",name="servicecharges_for_recreation"))
  s=rbind(s,data.frame(iesname="b89f056",name="subtotalcarried_forward"))
  s=rbind(s,data.frame(iesname="b89f057",name="goods"))
  s=rbind(s,data.frame(iesname="b89f058",name="membershipfees_and_donations"))
  s=rbind(s,data.frame(iesname="b89f059",name="incometax"))
  s=rbind(s,data.frame(iesname="b89f060",name="finance_and_insurance"))
  s=rbind(s,data.frame(iesname="b89f061",name="other_expenditure"))
  s=rbind(s,data.frame(iesname="b89f062",name="netloss"))
  s=rbind(s,data.frame(iesname="b89f063",name="harvest"))
  s=rbind(s,data.frame(iesname="b89f064",name="raising_of_livestock"))
  s=rbind(s,data.frame(iesname="b89f065",name="total_expenditure"))
  s=rbind(s,data.frame(iesname="b89f066",name="direct_income"))
  s=rbind(s,data.frame(iesname="b89f067",name="indirect_income"))
  s=rbind(s,data.frame(iesname="b89f068",name="total_income"))
  s=rbind(s,data.frame(iesname="weight",name="weight"))
  return(s)
}

########### <end hh columns mapping> ##########

######### ohs info columns ##############
ohs_info_columns_2010<-function(){
  #each of these are relative to the household head
  icols2010 <-c("hhid",
                "age",
                "highest_education",
                "relationship_to_head"
  )
  # must also include visible categories
  return(icols2010)
}

ohs_info_columns_2005<-function(){
  #each of these are relative to the household head
  icols2005 <-c("hhid",
                "age",
                "highest_education",
                "relationship_to_head"
  )
  # must also include visible categories
  return(icols2005)
}

ohs_info_columns_1995<-function(){
  return(c("hhid","age","gender","highest_education","area_type"));
}

######### <end ohs info columns> ##############

############# ohs mapping #################
ohs_mapping_1995 <-function(){
  s = data.frame(iesname="hhid",name="hhid")
  s= rbind(s,data.frame(iesname="AGE",name="age"))
  s= rbind(s,data.frame(iesname="GENDER",name="gender"))
  s= rbind(s,data.frame(iesname="Q216",name="highest_education"))
  s= rbind(s,data.frame(iesname="TYPE",name="area_type"))
  return(s)
}

ohs_mapping_2005 <-function(){
  s = data.frame(iesname="uqno",name="hhid")
  s= rbind(s,data.frame(iesname="personno",name="persno"))
  s= rbind(s,data.frame(iesname="q15higheduc",name="highest_education"))
  s= rbind(s,data.frame(iesname="agegrp",name="age_group"))
  return(s)
}

ohs_mapping_2010 <-function(){
  s = data.frame(iesname="UQNO",name="hhid")
  s= rbind(s,data.frame(iesname="PERSONNO",name="persno"))
  s= rbind(s,data.frame(iesname="Q21HIGHESTLEVEL",name="highest_education"))
  s= rbind(s,data.frame(iesname="Q15RELATIONSHIP",name="relationship_to_head"))
  s= rbind(s,data.frame(iesname="Q14AGE",name="age"))
  return(s)
}


############# <end ohs mapping> #################

########### income info columns ############
income_info_columns_2010<-function(){
  #each of these are relative to the household head
  icols2010 <-c("hhid",
                "total_income"
  )
  # must also include visible categories
  return(icols2010)
}

income_info_columns_2005<-function(){
  #each of these are relative to the household head
  icols2005 <-c("hhid",
                "total_income"
  )
  # must also include visible categories
  return(icols2005)
}


###########<end income info columns > ############

########### income mapping############

income_mapping_2010<-function(){
  s = data.frame(iesname="UQNO",name="hhid")
  s= rbind(s,data.frame(iesname="Personno",name="persno"))
  s= rbind(s,data.frame(iesname="Value",name="total_income"))
  return(s)
}


income_mapping_2005<-function(){
  s = data.frame(iesname="uqno",name="hhid")
  s= rbind(s,data.frame(iesname="personno",name="persno"))
  s= rbind(s,data.frame(iesname="value",name="total_income"))
  return(s)
}

###########<end income mapping ############

######## visible categories ############

# Notice that these are defined in terms of mapping fields
visible_categories_1995<-function(){
  # personal care, clothing and apparel (including footwear),jewelry, cars
  return (c("motor_cars_new","bakkies_new","caravantrailers_new",
            "motor_cars_used","bakkies_used","caravantrailers_new","hire_of_clothing",
            "jewelry","handbags","total_boys_footwear",
            "total_mens_footwear","total_girls_footwear","total_infants_footwear",
            "total_womens_footwear","total_infants_clothing",
            "total_boys_clothing","total_mens_clothing","total_girls_clothing",
            "total_womens_clothing","total_personal_care"))
}

visible_categories_2010<-function(){
  stop("Unimplemented")
}


visible_categories_2005<-function(){
  stop("Unimplemented")  
}
#####<end visible categories>##############
