#!/usr/bin/env bash
set -u -o pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"
OUT="$HERE/VERIFICATION.md"
LEDGER_LOG="$(mktemp)"
LIT_LOG="$(mktemp)"

(cd lean && lake build) > /dev/null 2>&1
BUILD=$?
python3 check.py --lean > "$LEDGER_LOG" 2>&1
LEDGER=$?
lit/verify_lit.sh > "$LIT_LOG" 2>&1
LIT=$?

{
  echo "# Verification"
  echo
  echo "Generated by \`verify.sh\` on $(date -u +%Y-%m-%dT%H:%MZ). Do not edit by hand."
  echo
  echo "Toolchain: $(cat lean/lean-toolchain); Mathlib $(python3 -c "import json;m=json.load(open('lean/lake-manifest.json'));print(next(p['rev'] for p in m['packages'] if p['name']=='mathlib'))")."
  echo
  echo "| Step | Result |"
  echo "|---|---|"
  echo "| lake build (IscLean, Lit) | $([ $BUILD -eq 0 ] && echo PASS || echo FAIL) |"
  echo "| check.py --lean | $([ $LEDGER -eq 0 ] && echo PASS || echo FAIL) |"
  echo "| lit/verify_lit.sh | $([ $LIT -eq 0 ] && echo PASS || echo FAIL) |"
  echo
  echo "## Ledger"
  echo
  echo '```'
  grep -E "^(status counts|map support|NOTE IscLean|ERROR|RESULT)" "$LEDGER_LOG"
  echo '```'
  echo
  echo "## Literature"
  echo
  echo '```'
  grep -E "SUMMARY|papers verified|\[FAIL\]|ALL LITERATURE|SOME LITERATURE" "$LIT_LOG"
  echo '```'
} > "$OUT"

rm -f "$LEDGER_LOG" "$LIT_LOG"
cat "$OUT"
[ $BUILD -eq 0 ] && [ $LEDGER -eq 0 ] && [ $LIT -eq 0 ]
