/-
Axiom audit: every headline theorem of the formalisation should depend only on
Lean's three standard axioms (`propext`, `Classical.choice`, `Quot.sound`) --
in particular on no `sorry`.

    lake env lean check_axioms.lean
-/
import JeffreyOrder
import AssocLocality
import AssocLocalityStructural
import Literature
open JeffreyOrder

-- Proposition IMM
#print axioms propIMM_single_cue
#print axioms propIMM_single_cue_B
#print axioms propIMM_indep
#print axioms propIMM_no_gap
#print axioms propIMM_no_sequence_effect

-- Proposition DIV (i), (ii) and Appendix A.1
#print axioms propDIV_gap_AB_a00
#print axioms propDIV_gap_AB_a01
#print axioms propDIV_gap_AB_a10
#print axioms propDIV_gap_AB_a11
#print axioms propDIV_gap_BA_a00
#print axioms propDIV_gap_BA_a01
#print axioms propDIV_gap_BA_a10
#print axioms propDIV_gap_BA_a11
#print axioms propDIV_seq_a00
#print axioms propDIV_seq_a01
#print axioms propDIV_seq_a10
#print axioms propDIV_seq_a11
#print axioms kappa_eq_zero_iff
#print axioms kappa'_eq_zero_iff

-- Lemma ASC
#print axioms inner_gradAssoc_R1
#print axioms inner_gradAssoc_R2
#print axioms lemmaASC_first_order_vanishes
#print axioms lemmaASC_first_order_vanishes_BA

-- Lemma SEP (arbitrary N)
#print axioms isSeparable_applySteps
#print axioms sep_no_pair_interaction
#print axioms applySteps_no_pair_interaction
#print axioms sep_rescales_association

-- Lemma SCR
#print axioms lemmaSCR_gap_AB
#print axioms lemmaSCR_gap_BA
#print axioms lemmaSCR_protected_weight

-- Proposition DEC
#print axioms sep_assoc
#print axioms sep_oddsRatio
#print axioms PJab_sep
#print axioms PJba_sep
#print axioms PB_sep
#print axioms oddsRatio_PJab_eq_prior
#print axioms oddsRatio_gap_eq_zero

-- Proposition DRF
#print axioms jeffreyA_pins_mA1
#print axioms PJba_mA1
#print axioms propDRF_route_AB
#print axioms propDRF_route_BA
#print axioms propDRF
#print axioms propDRF_B_at_one
#print axioms Kdrift_pos
#print axioms Kdrift_neg

-- Proposition PRO
#print axioms R1_R2_indep
#print axioms Jmat_gradAssoc_indep
#print axioms propPRO_protection
#print axioms propPRO_protection_each
#print axioms annihilator_eq_span
#print axioms propPRO_uniqueness
#print axioms margA_not_in_span

-- Section 4.4, Theorem LOS, Proposition SHR
#print axioms flips_iff
#print axioms abs_le_of_flips
#print axioms not_flips_of_lt_cstar
#print axioms not_flips_of_pointing_away
#print axioms flipSet_eq_Ico_of_pos
#print axioms volume_flipSet
#print axioms lintegral_stake_le
#print axioms lintegral_stake_le_volume

-- Association-locality (general prior, arbitrary target marginals): the
-- association order-gap numerator is divisible by c^2, i.e. second order.
#print axioms assoc_gap_second_order
#print axioms assoc_gap_has_c_sq_factor

-- Structural version: the Jeffrey updates are DEFINED and the association
-- order-gap is DERIVED (not supplied) to equal c^2*gapQuot/(D1 D2 D3 D4).
#print axioms PaperB.assoc_order_gap_structural

-- Anchoring family (adoption weight δ): endpoints, factorisation, order effect
#print axioms dampedB_deviation
#print axioms dampedB_deviation_c_scaled
#print axioms dampedB_at_one
#print axioms dampedB_at_zero
#print axioms routeDamped_at_zero_pins_A
#print axioms dampedB_mA1_mix
#print axioms routeDamped_mA1_deviation
#print axioms orderEffect_damped_mA1
#print axioms orderEffect_damped_at_indep

-- Literature formalizations (lean/Literature/*.lean): each paper's own claims,
-- generated from the theorem declarations. Three use a strict subset of the
-- standard axioms (BHW.regimes, ShmayaYariv.agreeBelow_refl, alpha_depends_on_nu).
#print axioms Literature.Arrow.wage_gap
#print axioms Literature.Arrow.profit_change
#print axioms Literature.Arrow.ratio_utility_euler
#print axioms Literature.Arrow.eq7_of_ratio_utility
#print axioms Literature.Arrow.segregation_shares
#print axioms Literature.Arrow.mixed_costlier
#print axioms Literature.Arrow.appendix_nonconvex
#print axioms Literature.Arrow.eq14
#print axioms Literature.Arrow.wage_differential
#print axioms Literature.Arrow.exists_symmetric
#print axioms Literature.Arrow.desired_hasDerivAt
#print axioms Literature.Arrow.stability_iff
#print axioms Literature.Arrow.example_two_fixed_points
#print axioms Literature.Arrow.example_only_fixed_points
#print axioms Literature.Arrow.example_discriminatory
#print axioms Literature.Arrow.example_stability
#print axioms Literature.AugenblickRabin.excess_step
#print axioms Literature.AugenblickRabin.reduction_telescope
#print axioms Literature.AugenblickRabin.movement_sub_reduction
#print axioms Literature.AugenblickRabin.prop1_of_orthogonal
#print axioms Literature.AugenblickRabin.orthogonal_of_martingale
#print axioms Literature.AugenblickRabin.resolving
#print axioms Literature.BCGS.repr_eq_lr
#print axioms Literature.BCGS.repr_le_iff
#print axioms Literature.BCGS.lr_complement
#print axioms Literature.BCGS.stereo_sum_one
#print axioms Literature.BCGS.stereo_odds
#print axioms Literature.BCGS.prop1_i_degenerate
#print axioms Literature.BCGS.truncation_raises_mean
#print axioms Literature.BCGS.mlr_mean_order
#print axioms Literature.BCGS.prop2_kernel_of_truth
#print axioms Literature.BCGS.prop2_strict_needs_mass
#print axioms Literature.BCGS.prop4_i
#print axioms Literature.BCGS.prop5_threshold
#print axioms Literature.BCGS.repr2_factor
#print axioms Literature.BCGS.lemma1_i
#print axioms Literature.BCGS.irish_europeans
#print axioms Literature.BCGS.irish_scots
#print axioms Literature.BCGS.welfare_ranking
#print axioms Literature.BCGS.welfare_correlation_true
#print axioms Literature.BCGS.welfare_correlation_stereo_d1
#print axioms Literature.BCGS.welfare_correlation_stereo_d2
#print axioms Literature.BCGS.welfare_within_group
#print axioms Literature.BHW.sigLik_tt
#print axioms Literature.BHW.sigLik_tf
#print axioms Literature.BHW.sigLik_ft
#print axioms Literature.BHW.sigLik_ff
#print axioms Literature.BHW.actProb_up
#print axioms Literature.BHW.actProb_down
#print axioms Literature.BHW.actProb_zero
#print axioms Literature.BHW.actProb_one
#print axioms Literature.BHW.actProb_negOne
#print axioms Literature.BHW.regimes
#print axioms Literature.BHW.lik_ratio
#print axioms Literature.BHW.sigLik_nonneg
#print axioms Literature.BHW.adoptProb_mem
#print axioms Literature.BHW.actProb_nonneg
#print axioms Literature.BHW.lik_nonneg
#print axioms Literature.BHW.half_cmp
#print axioms Literature.BHW.counting_rule_is_bayes
#print axioms Literature.BHW.cascade_ignores_signal
#print axioms Literature.BHW.cascade_uninformative
#print axioms Literature.BHW.cascade_uninformative_down
#print axioms Literature.BHW.cascade_forever
#print axioms Literature.BHW.informative_outside_cascade
#print axioms Literature.BHW.den_pos
#print axioms Literature.BHW.step_step
#print axioms Literature.BHW.eq3
#print axioms Literature.BHW.eq1
#print axioms Literature.BHW.no_cascade_after_ten
#print axioms Literature.BHW.tendsto_correct_cascade
#print axioms Literature.BHW.A6_posterior_up
#print axioms Literature.BHW.A10_closed_form
#print axioms Literature.BHW.A10_value
#print axioms Literature.BHW.A11_simplify
#print axioms Literature.BHW.A11_value
#print axioms Literature.Banerjee.lemma1_weights
#print axioms Literature.Banerjee.lemma1
#print axioms Literature.Banerjee.printed_second_weight_lt
#print axioms Literature.Banerjee.herd_follow_uninformative
#print axioms Literature.Banerjee.den_pos
#print axioms Literature.Banerjee.pi_hasSum
#print axioms Literature.Banerjee.chain_nonneg
#print axioms Literature.Banerjee.chain_total
#print axioms Literature.Banerjee.value_invariant
#print axioms Literature.Banerjee.no_one_correct_ge_Pi
#print axioms Literature.Banerjee.transient_le
#print axioms Literature.Banerjee.tendsto_no_one_correct
#print axioms Literature.Banerjee.Pi_antitone_beta
#print axioms Literature.Banerjee.Pi_antitone_alpha
#print axioms Literature.Banerjee.Pi_beta_zero
#print axioms Literature.Banerjee.independent_tendsto_zero
#print axioms Literature.Banerjee.dstar_formula
#print axioms Literature.BohrenImasRosenberg.complete_square
#print axioms Literature.BohrenImasRosenberg.posterior_kernel
#print axioms Literature.BohrenImasRosenberg.eval_strictMono_prior
#print axioms Literature.BohrenImasRosenberg.disc_initial
#print axioms Literature.BohrenImasRosenberg.prop1_decreasing
#print axioms Literature.BohrenImasRosenberg.prop1_constant
#print axioms Literature.BohrenImasRosenberg.prop1_limit
#print axioms Literature.BohrenImasRosenberg.fn9_equivalent
#print axioms Literature.BohrenImasRosenberg.disc_aggregate
#print axioms Literature.BohrenImasRosenberg.disc_eq7
#print axioms Literature.BohrenImasRosenberg.reqSignal_inverts
#print axioms Literature.BohrenImasRosenberg.reqSignal_anti
#print axioms Literature.BohrenImasRosenberg.tauEE_pos
#print axioms Literature.BohrenImasRosenberg.tauQ_pos
#print axioms Literature.BohrenImasRosenberg.exo_gap
#print axioms Literature.BohrenImasRosenberg.endo_gap_eq12
#print axioms Literature.BohrenImasRosenberg.endo_gap
#print axioms Literature.BohrenImasRosenberg.channels
#print axioms Literature.BohrenImasRosenberg.endo_strictMono
#print axioms Literature.BohrenImasRosenberg.endo_faster
#print axioms Literature.BohrenImasRosenberg.precA_pos
#print axioms Literature.BohrenImasRosenberg.belief_gap
#print axioms Literature.BohrenImasRosenberg.discAt_eq
#print axioms Literature.BohrenImasRosenberg.prop2_no_reversal
#print axioms Literature.BohrenImasRosenberg.decr_core
#print axioms Literature.BohrenImasRosenberg.prop2_decreasing
#print axioms Literature.BohrenImasRosenberg.impartial_favors_female
#print axioms Literature.BohrenImasRosenberg.m1_gt_m2
#print axioms Literature.BohrenImasRosenberg.disc2_factor
#print axioms Literature.BohrenImasRosenberg.disc2_endpoints
#print axioms Literature.BohrenImasRosenberg.prop3_sign
#print axioms Literature.BohrenImasRosenberg.prop3_cutoff
#print axioms Literature.BohrenImasRosenberg.prop3_condition_iff
#print axioms Literature.CoateLoury.posterior_eq_odds
#print axioms Literature.CoateLoury.posterior_strictMono
#print axioms Literature.CoateLoury.assign_iff
#print axioms Literature.CoateLoury.assign_iff_threshold
#print axioms Literature.CoateLoury.acceptSet_mono
#print axioms Literature.CoateLoury.threshold_antitone
#print axioms Literature.CoateLoury.acceptSet_upper
#print axioms Literature.CoateLoury.isLeast_of_EE
#print axioms Literature.CoateLoury.cov_group_qualified
#print axioms Literature.CoateLoury.negativeStereotype_iff_cov_pos
#print axioms Literature.CoateLoury.prop1_two_equilibria
#print axioms Literature.CoateLoury.exφ_strictAntiOn
#print axioms Literature.CoateLoury.exφ_pos
#print axioms Literature.CoateLoury.smooth_example
#print axioms Literature.CoateLoury.prop2_homogeneous
#print axioms Literature.CoateLoury.pihat_eq6
#print axioms Literature.CoateLoury.example_selfConfirming
#print axioms Literature.CoateLoury.alpha_eq7
#print axioms Literature.CoateLoury.eq8_solutions
#print axioms Literature.CoateLoury.lambdaHat_iff
#print axioms Literature.CoateLoury.patronStep_sub
#print axioms Literature.CoateLoury.patronSeq_tendsto
#print axioms Literature.CoateLoury.colorBlind_unstable
#print axioms Literature.CoateLoury.stereotype_worsens
#print axioms Literature.CoateLoury.fn21_instance
#print axioms Literature.Cripps.bayes_sum_pos
#print axioms Literature.Cripps.bayes_isBelief
#print axioms Literature.Cripps.bayes_const
#print axioms Literature.Cripps.bayes_bayes
#print axioms Literature.Cripps.bayes_uniform
#print axioms Literature.Cripps.uniform_isBelief
#print axioms Literature.Cripps.divRule_seq
#print axioms Literature.Cripps.divRule_comm
#print axioms Literature.Cripps.binExp_isExperiment
#print axioms Literature.Cripps.exp_lt_one
#print axioms Literature.Cripps.residual_isExperiment
#print axioms Literature.Cripps.belief_lt_one
#print axioms Literature.Cripps.prop1_if
#print axioms Literature.Cripps.bayes_isDivisible
#print axioms Literature.Cripps.lemma1_i
#print axioms Literature.Cripps.seq_eq_product
#print axioms Literature.Cripps.order_invariance
#print axioms Literature.Cripps.margA_jeffreyA
#print axioms Literature.Cripps.jeffreyA_jeffreyA
#print axioms Literature.Cripps.jeffreyA_cond
#print axioms Literature.Cripps.margA_pos
#print axioms Literature.Cripps.jeffreyA_eq_bayes_matched
#print axioms Literature.Cripps.jeffreyB_eq_bayes_matched
#print axioms Literature.Cripps.composite_AB_eq_bayes
#print axioms Literature.Cripps.rigid_symmetry
#print axioms Literature.Cripps.rigid_divisible_imp_evidence_blind
#print axioms Literature.Cripps.rigid_divisible_imp_const
#print axioms Literature.Cripps.mu1_isBelief
#print axioms Literature.Cripps.mu2_isBelief
#print axioms Literature.Cripps.rigid_not_uninformative
#print axioms Literature.Cripps.rigid_not_nonDogmatic
#print axioms Literature.Dietrich.normalize_smul
#print axioms Literature.Dietrich.normalize_of_sum_one
#print axioms Literature.Dietrich.restrict_smul
#print axioms Literature.Dietrich.cond_normalize
#print axioms Literature.Dietrich.sum_restrict
#print axioms Literature.Dietrich.geoW_nonneg
#print axioms Literature.Dietrich.geoW_pos
#print axioms Literature.Dietrich.sum_geoW_pos
#print axioms Literature.Dietrich.geoW_cond
#print axioms Literature.Dietrich.geoPool_dynRational
#print axioms Literature.Dietrich.geoPool_unanimous
#print axioms Literature.Dietrich.geoPool_externallyBayesian
#print axioms Literature.Dietrich.linPool_cond_sub
#print axioms Literature.Dietrich.linPool_comm_iff
#print axioms Literature.Dietrich.duel_linear_not_dynRational
#print axioms Literature.Dietrich.premise_forces_unanimity
#print axioms Literature.Dietrich.eb_premise_forces_unanimity
#print axioms Literature.Dietrich.dynRational_on_common_prior
#print axioms Literature.Dietrich.eb_on_common_prior
#print axioms Literature.Dietrich.linPool_unanimous
#print axioms Literature.Dietrich.linPool_dynRational_on_common_prior
#print axioms Literature.Dietrich.linPool_eb_on_common_prior
#print axioms Literature.Dietrich.cond_eq_self_of_pos
#print axioms Literature.Dietrich.not_cond_of_fullSupport
#print axioms Literature.Domotor.mass_nonneg
#print axioms Literature.Domotor.mass_mono
#print axioms Literature.Domotor.le_mass
#print axioms Literature.Domotor.mass_cond
#print axioms Literature.Domotor.cond_nonneg
#print axioms Literature.Domotor.cond_cond
#print axioms Literature.Domotor.cond_univ
#print axioms Literature.Domotor.cond_zero
#print axioms Literature.Domotor.cond_empty
#print axioms Literature.Domotor.cond_state
#print axioms Literature.Domotor.cond_disjoint
#print axioms Literature.Domotor.cond_dominated_of_subset
#print axioms Literature.Domotor.cond_orth_of_disjoint
#print axioms Literature.Domotor.mass_mix
#print axioms Literature.Domotor.cond_mix
#print axioms Literature.Domotor.cellMass_nonneg
#print axioms Literature.Domotor.le_cellMass
#print axioms Literature.Domotor.cellMass_jeffrey
#print axioms Literature.Domotor.sum_by_cell
#print axioms Literature.Domotor.jeffrey_dominated
#print axioms Literature.Domotor.jeffrey_irrelevant
#print axioms Literature.Domotor.jeffrey_unit
#print axioms Literature.Domotor.jeffrey_markov
#print axioms Literature.Domotor.jeffrey_of_cellwise
#print axioms Literature.Domotor.jeffrey_seq_on_meet
#print axioms Literature.Domotor.jeffrey_not_comm
#print axioms Literature.Domotor.fieldZ_pos
#print axioms Literature.Domotor.field_comp
#print axioms Literature.Domotor.field_comm
#print axioms Literature.Domotor.field_zero_iff
#print axioms Literature.Domotor.field_not_convex
#print axioms Literature.Domotor.field_mix
#print axioms Literature.Domotor.field_eq_jeffrey_embed
#print axioms Literature.Domotor.embed_unit
#print axioms Literature.Domotor.embed_depends_on_state
#print axioms Literature.Domotor.embed_surjective
#print axioms Literature.Doring.cellMass_jeffrey
#print axioms Literature.Doring.jeffrey_rigid
#print axioms Literature.Doring.jeffrey_certain
#print axioms Literature.Doring.jeffrey_reversible
#print axioms Literature.Doring.jeffrey_same_partition
#print axioms Literature.Doring.cond_comm
#print axioms Literature.Doring.field_comm
#print axioms Literature.Doring.cellMass_fieldUpdate
#print axioms Literature.Doring.field_odds
#print axioms Literature.Doring.fig1_step1
#print axioms Literature.Doring.fig1_step1'
#print axioms Literature.Doring.fig1_seq1
#print axioms Literature.Doring.fig1_seq2
#print axioms Literature.Doring.order_effect_condA_notB
#print axioms Literature.Doring.condA_notB_seq1_approx
#print axioms Literature.Doring.ratio_seq1
#print axioms Literature.Doring.order_effect_margA
#print axioms Literature.Doring.jeffrey_not_comm
#print axioms Literature.Doring.third_step
#print axioms Literature.Doring.fam_nine_halves
#print axioms Literature.Doring.jeffrey_cueOr
#print axioms Literature.Doring.jeffrey_cueNotAOr
#print axioms Literature.Doring.fam_seq1
#print axioms Literature.Doring.fam_seq2
#print axioms Literature.Doring.fam_gap
#print axioms Literature.Doring.gap_tends_to_one
#print axioms Literature.Doring.fig2
#print axioms Literature.Doring.dempster_masses
#print axioms Literature.Doring.dempster_result
#print axioms Literature.Doring.dempster_gap
#print axioms Literature.Doring.fig3_row1
#print axioms Literature.Doring.fig3_row2
#print axioms Literature.FGT.sum_contrib
#print axioms Literature.FGT.P0_eq_H
#print axioms Literature.FGT.P1_eq_H_mul_I
#print axioms Literature.FGT.P1_eq_popMean_normGap
#print axioms Literature.FGT.I_eq_meanGapPoor_div_z
#print axioms Literature.FGT.P1_eq_H_mul_meanGapPoor
#print axioms Literature.FGT.P2_alg
#print axioms Literature.FGT.P2_formula
#print axioms Literature.FGT.card_mul_P
#print axioms Literature.FGT.P_decomp
#print axioms Literature.FGT.P_decomp_shares
#print axioms Literature.FGT.subgroup_monotone
#print axioms Literature.FGT.sum_update
#print axioms Literature.FGT.P_monotone
#print axioms Literature.FGT.P0_not_monotone
#print axioms Literature.FGT.strictConvex_spread
#print axioms Literature.FGT.P_transfer
#print axioms Literature.FGT.P_transfer_to_nonpoor
#print axioms Literature.FGT.P1_transfer_neutral
#print axioms Literature.FGT.I_not_decomposable
#print axioms Literature.FGT.P1_decomposes_on_example
#print axioms Literature.GoodMittal.paradox_iff_max_min
#print axioms Literature.GoodMittal.mediant_between
#print axioms Literature.GoodMittal.not_paradox_of_weighted
#print axioms Literature.GoodMittal.piR_amalg_general
#print axioms Literature.GoodMittal.N_mul_piR_of_row
#print axioms Literature.GoodMittal.amalg_row
#print axioms Literature.GoodMittal.amalg_cd_pos
#print axioms Literature.GoodMittal.piR_weighted_rowUniform
#print axioms Literature.GoodMittal.yule_eq_of_row
#print axioms Literature.GoodMittal.amalg_pos
#print axioms Literature.GoodMittal.yule_weighted_rowUniform
#print axioms Literature.GoodMittal.N_pos
#print axioms Literature.GoodMittal.amalg_N
#print axioms Literature.GoodMittal.no_paradox_piR
#print axioms Literature.GoodMittal.no_paradox_yule
#print axioms Literature.GoodMittal.piC_eq_piR_tr
#print axioms Literature.GoodMittal.amalg_tr
#print axioms Literature.GoodMittal.no_paradox_piC
#print axioms Literature.GoodMittal.expQR_weighted_rowUniform
#print axioms Literature.GoodMittal.expWR_weighted_rowUniform
#print axioms Literature.GoodMittal.not_paradox_log
#print axioms Literature.GoodMittal.expQR_pos
#print axioms Literature.GoodMittal.expWR_pos
#print axioms Literature.GoodMittal.no_paradox_QR
#print axioms Literature.GoodMittal.no_paradox_WR
#print axioms Literature.GoodMittal.kappa_between_of_ratios
#print axioms Literature.GoodMittal.kappa_between_of_uniform
#print axioms Literature.GoodMittal.note_p702_kappa_paradox
#print axioms Literature.GoodMittal.equalSize_reversal
#print axioms Literature.GoodMittal.equalSize_not_rowUniform
#print axioms Literature.GoodMittal.yule_case_paradox
#print axioms Literature.GoodMittal.kappa_homogeneous_iff
#print axioms Literature.Heckman.audit_diff_linear
#print axioms Literature.Heckman.audit_mean_linear
#print axioms Literature.Heckman.audit_unbiased_iff
#print axioms Literature.Heckman.two_component_bias
#print axioms Literature.Heckman.no_disc_finds_disc
#print axioms Literature.Heckman.no_disc_finds_reverse
#print axioms Literature.Heckman.no_disc_finds_equal
#print axioms Literature.Heckman.disc_disguised
#print axioms Literature.Heckman.disc_reversed
#print axioms Literature.Heckman.disc_shown
#print axioms Literature.Heckman.phase_high
#print axioms Literature.Heckman.phase_low
#print axioms Literature.Heckman.equal_means_not_enough
#print axioms Literature.HogarthEinhorn.evalStep_eq
#print axioms Literature.HogarthEinhorn.estStep_averaging
#print axioms Literature.HogarthEinhorn.contrastWeight_mem_Icc
#print axioms Literature.HogarthEinhorn.estContrast_le
#print axioms Literature.HogarthEinhorn.estContrast_gt
#print axioms Literature.HogarthEinhorn.evalContrast_le
#print axioms Literature.HogarthEinhorn.evalContrast_gt
#print axioms Literature.HogarthEinhorn.appB_orderEffect
#print axioms Literature.HogarthEinhorn.appB_recency
#print axioms Literature.HogarthEinhorn.appB_recency_pos
#print axioms Literature.HogarthEinhorn.positional_orderEffect
#print axioms Literature.HogarthEinhorn.positional_primacy_iff
#print axioms Literature.HogarthEinhorn.contrast_mixed_orderEffect
#print axioms Literature.HogarthEinhorn.contrast_mixed_recency
#print axioms Literature.HogarthEinhorn.contrast_consistent_pos_nocross
#print axioms Literature.HogarthEinhorn.contrast_consistent_primacy_asym
#print axioms Literature.HogarthEinhorn.contrast_consistent_primacy_equal
#print axioms Literature.HogarthEinhorn.appC_consistent_neg
#print axioms Literature.HogarthEinhorn.appC_consistent_pos
#print axioms Literature.HogarthEinhorn.appC_mixed_orderEffect
#print axioms Literature.HogarthEinhorn.appC_mixed_recency
#print axioms Literature.HogarthEinhorn.variant_constant_noEffect
#print axioms Literature.HogarthEinhorn.variant_reversed_mixed_primacy
#print axioms Literature.HogarthEinhorn.eos_symmetric_noEffect
#print axioms Literature.HogarthEinhorn.eq8_estimation
#print axioms Literature.HogarthEinhorn.eq8_evaluation
#print axioms Literature.HogarthEinhorn.weight_le_one
#print axioms Literature.HogarthEinhorn.eq8_estimation_first_dominates
#print axioms Literature.HogarthEinhorn.eq8_evaluation_first_dominates
#print axioms Literature.HogarthEinhorn.eq8_estimation_uniform_iff
#print axioms Literature.HogarthEinhorn.eq8_estimation_not_always
#print axioms Literature.HogarthEinhorn.eos2_est_orderEffect
#print axioms Literature.HogarthEinhorn.eos2_eval_orderEffect
#print axioms Literature.HogarthEinhorn.oneSided_eq_eq8
#print axioms Literature.HogarthEinhorn.oneSided_eq_positional
#print axioms Literature.HogarthEinhorn.oneSided_orderEffect
#print axioms Literature.HogarthEinhorn.oneSided_primacy_iff
#print axioms Literature.HogarthEinhorn.twoSided_orderEffect
#print axioms Literature.HogarthEinhorn.twoSided_recency
#print axioms Literature.HogarthEinhorn.sided_gap
#print axioms Literature.HogarthEinhorn.sided_disagree
#print axioms Literature.HogarthEinhorn.twoAttr_twoSided_noEffect
#print axioms Literature.HogarthEinhorn.twoAttr_oneSided_orderEffect
#print axioms Literature.Phelps.relRatio_pos
#print axioms Literature.Phelps.relRatio_lt_one
#print axioms Literature.Phelps.one_sub_relRatio
#print axioms Literature.Phelps.mse_sub_mse_opt
#print axioms Literature.Phelps.relRatio_minimizes_mse
#print axioms Literature.Phelps.ssr_expand
#print axioms Literature.Phelps.ssr_sub_ssr_ols
#print axioms Literature.Phelps.predict_eq5
#print axioms Literature.Phelps.predict_eq5'
#print axioms Literature.Phelps.gap_identity
#print axioms Literature.Phelps.case1_parallel
#print axioms Literature.Phelps.case2_slope_gt
#print axioms Literature.Phelps.case2_slope_tendsto_one
#print axioms Literature.Phelps.case2_crossing
#print axioms Literature.Phelps.further_slope_lt
#print axioms Literature.Phelps.further_crossing
#print axioms Literature.Phelps.relRatio_lt_iff
#print axioms Literature.Phelps.no_mean_gap_still_differential
#print axioms Literature.ShmayaYariv.agreeBelow_refl
#print axioms Literature.ShmayaYariv.self_mem_event
#print axioms Literature.ShmayaYariv.alpha_const_on_event
#print axioms Literature.ShmayaYariv.jointWt_of_ne
#print axioms Literature.ShmayaYariv.jointWt_self
#print axioms Literature.ShmayaYariv.anythingGoes
#print axioms Literature.ShmayaYariv.alpha_depends_on_nu
#print axioms Literature.ShmayaYariv.argmax_of_convex_combination
#print axioms Literature.ShmayaYariv.no_reversal_of_restricted
#print axioms Literature.Weisberg.mass_nonneg
#print axioms Literature.Weisberg.mass_cond
#print axioms Literature.Weisberg.cond_cond
#print axioms Literature.Weisberg.strict_dilemma
#print axioms Literature.Weisberg.mass_jeffrey2_inter
#print axioms Literature.Weisberg.mass_jeffrey2_sdiff
#print axioms Literature.Weisberg.mass_jeffrey2_E
#print axioms Literature.Weisberg.jeffrey2_rigid
#print axioms Literature.Weisberg.mass_split
#print axioms Literature.Weisberg.rpi_qF
#print axioms Literature.Weisberg.rigidity_preserves_independence
#print axioms Literature.Weisberg.no_undercutting
#print axioms Literature.Weisberg.rpi_jeffrey2
#print axioms Literature.Weisberg.jeffrey2_twice
#print axioms Literature.Weisberg.jeffrey2_not_comm_inputs
#print axioms Literature.Weisberg.jeffrey_finest
#print axioms Literature.Weisberg.bf_oddsUpdate
#print axioms Literature.Weisberg.oddsUpdate_comm
#print axioms Literature.Weisberg.lange_jellybean
#print axioms Literature.Weisberg.jellybean_81
#print axioms Literature.Weisberg.margE_jeffE
#print axioms Literature.Weisberg.margF_jeffF
#print axioms Literature.Weisberg.margE_pos
#print axioms Literature.Weisberg.margF_pos
#print axioms Literature.Weisberg.jeffE_pos
#print axioms Literature.Weisberg.jeffF_pos
#print axioms Literature.Weisberg.appendix26
#print axioms Literature.Weisberg.appendix27
#print axioms Literature.Weisberg.wagner_E
#print axioms Literature.Weisberg.appendix26F
#print axioms Literature.Weisberg.appendix27F
#print axioms Literature.Weisberg.wagner_F
#print axioms Literature.Weisberg.jellybean_wagner

-- BEGIN Literature.Jeffrey
#print axioms Literature.Jeffrey.relevance_identity
#print axioms Literature.Jeffrey.mudrunner
#print axioms Literature.Jeffrey.sum_fiber
#print axioms Literature.Jeffrey.cellMass_kin
#print axioms Literature.Jeffrey.total_kin
#print axioms Literature.Jeffrey.Indep.symm
#print axioms Literature.Jeffrey.cellMass_kin_of_indep
#print axioms Literature.Jeffrey.kin_comm_of_indep
#print axioms Literature.Jeffrey.fac_fac_eq_product
#print axioms Literature.Jeffrey.fac_comm
#print axioms Literature.Jeffrey.fac_smul
#print axioms Literature.Jeffrey.fac_eq_kin
#print axioms Literature.Jeffrey.kin_eq_fac
#print axioms Literature.Jeffrey.skyrms_three
#print axioms Literature.Jeffrey.expansion
#print axioms Literature.Jeffrey.example4
#print axioms Literature.Jeffrey.example5_printed
#print axioms Literature.Jeffrey.example5_normalized
-- END Literature.Jeffrey

-- BEGIN Literature.BenjaminBodohCreedRabin
#print axioms Literature.BenjaminBodohCreedRabin.sum_pos_of_pos
#print axioms Literature.BenjaminBodohCreedRabin.normalize_pos
#print axioms Literature.BenjaminBodohCreedRabin.normalize_sum
#print axioms Literature.BenjaminBodohCreedRabin.normalize_smul
#print axioms Literature.BenjaminBodohCreedRabin.normalize_ratio
#print axioms Literature.BenjaminBodohCreedRabin.brnWeight_pos
#print axioms Literature.BenjaminBodohCreedRabin.brn_pos
#print axioms Literature.BenjaminBodohCreedRabin.brn_smul
#print axioms Literature.BenjaminBodohCreedRabin.brn_normalize
#print axioms Literature.BenjaminBodohCreedRabin.brnIter_pos
#print axioms Literature.BenjaminBodohCreedRabin.closedWeight_pos
#print axioms Literature.BenjaminBodohCreedRabin.brnWeight_closedWeight
#print axioms Literature.BenjaminBodohCreedRabin.brnIter_closedForm
#print axioms Literature.BenjaminBodohCreedRabin.logOdds_brn
#print axioms Literature.BenjaminBodohCreedRabin.logOdds_brnIter
#print axioms Literature.BenjaminBodohCreedRabin.ratio_brnIter
#print axioms Literature.BenjaminBodohCreedRabin.logOdds_uninformative
#print axioms Literature.BenjaminBodohCreedRabin.logOdds_bounded
#print axioms Literature.BenjaminBodohCreedRabin.logOdds_brn2
#print axioms Literature.BenjaminBodohCreedRabin.twoSignal_logOdds_order
#print axioms Literature.BenjaminBodohCreedRabin.twoSignal_order_iff
#print axioms Literature.BenjaminBodohCreedRabin.recency_two_signals
#print axioms Literature.BenjaminBodohCreedRabin.brn_order_invariant_iff
#print axioms Literature.BenjaminBodohCreedRabin.extreme_moderation_iff
#print axioms Literature.BenjaminBodohCreedRabin.assoc_normalize
#print axioms Literature.BenjaminBodohCreedRabin.assoc_brn_product
#print axioms Literature.BenjaminBodohCreedRabin.cueA_eq
#print axioms Literature.BenjaminBodohCreedRabin.cueB_eq
#print axioms Literature.BenjaminBodohCreedRabin.assoc_brnAB
#print axioms Literature.BenjaminBodohCreedRabin.assoc_brnBA
#print axioms Literature.BenjaminBodohCreedRabin.assoc_brn_orders_eq
#print axioms Literature.BenjaminBodohCreedRabin.assoc_bayes
#print axioms Literature.BenjaminBodohCreedRabin.assoc_brnAB_vs_bayes
#print axioms Literature.BenjaminBodohCreedRabin.margA_ratio_product
#print axioms Literature.BenjaminBodohCreedRabin.brn2_eq
#print axioms Literature.BenjaminBodohCreedRabin.margOddsA_brnAB_indep
#print axioms Literature.BenjaminBodohCreedRabin.margOddsA_brnBA_indep
#print axioms Literature.BenjaminBodohCreedRabin.margOddsA_order_ratio
#print axioms Literature.BenjaminBodohCreedRabin.margOddsA_orders_ne
#print axioms Literature.BenjaminBodohCreedRabin.sq_rpow_half
#print axioms Literature.BenjaminBodohCreedRabin.example_marginal_gap
-- END Literature.BenjaminBodohCreedRabin

-- BEGIN Literature.Asch
#print axioms Literature.Asch.seriesB_eq_reverse
#print axioms Literature.Asch.seriesB_perm
#print axioms Literature.Asch.seriesA_length
#print axioms Literature.Asch.seriesA_nodup
#print axioms Literature.Asch.checkListI_length
#print axioms Literature.Asch.stimulus_disjoint_checklist
#print axioms Literature.Asch.stimulus_disjoint_checklist_B
#print axioms Literature.Asch.mem_allTraits
#print axioms Literature.Asch.allTraits_nodup
#print axioms Literature.Asch.allTraits_length
#print axioms Literature.Asch.table7_rows_are_checklist_pairs
#print axioms Literature.Asch.quoted_all
#print axioms Literature.Asch.restrained_64_9
#print axioms Literature.Asch.goodLooking_74_35
#print axioms Literature.Asch.serious_97_100
#print axioms Literature.Asch.persistent_82_87
#print axioms Literature.Asch.reliable_84_91
#print axioms Literature.Asch.humorous_52_21
#print axioms Literature.Asch.goodNatured_18_0
#print axioms Literature.Asch.important_85_90
#print axioms Literature.Asch.d_pos_count
#print axioms Literature.Asch.d_neg_count
#print axioms Literature.Asch.d_ne_zero
#print axioms Literature.Asch.d_neg_exactly
#print axioms Literature.Asch.d_neg_values
#print axioms Literature.Asch.d_sum
#print axioms Literature.Asch.d_abs_sum
#print axioms Literature.Asch.d_le_restrained
#print axioms Literature.Asch.d_restrained
#print axioms Literature.Asch.d_ge_reliable
#print axioms Literature.Asch.large_swings
#print axioms Literature.Asch.small_moves
#print axioms Literature.Asch.small_moves_lt_two_subjects
#print axioms Literature.Asch.exp7_pos_count
#print axioms Literature.Asch.exp7_neg_count
#print axioms Literature.Asch.exp7_zero
#print axioms Literature.Asch.exp7_sum
#print axioms Literature.Asch.exp7_serious
#print axioms Literature.Asch.table8_ie_sum
#print axioms Literature.Asch.table8_ei_sum
#print axioms Literature.Asch.envious_modal_rank_ie
#print axioms Literature.Asch.envious_modal_rank_ei
#print axioms Literature.Asch.envious_modal_share
#print axioms Literature.Asch.table8_ie_rounding
#print axioms Literature.Asch.table8_ei_rounding
#print axioms Literature.Asch.ei_unattainable_count
#print axioms Literature.Asch.ie_unattainable_count
#print axioms Literature.Asch.ei_unattainable_examples
#print axioms Literature.Asch.within_no_change
-- END Literature.Asch

-- BEGIN Literature.ZhaoOsherson
#print axioms Literature.ZhaoOsherson.prNB_eq
#print axioms Literature.ZhaoOsherson.total_probability
#print axioms Literature.ZhaoOsherson.jeffrey_true
#print axioms Literature.ZhaoOsherson.jeffrey_false
#print axioms Literature.ZhaoOsherson.jeffrey_prB
#print axioms Literature.ZhaoOsherson.jeffrey_prNB
#print axioms Literature.ZhaoOsherson.jeffrey_isDist
#print axioms Literature.ZhaoOsherson.jeffrey_invariance
#print axioms Literature.ZhaoOsherson.jeffrey_rule
#print axioms Literature.ZhaoOsherson.invariance_imp_jeffrey
#print axioms Literature.ZhaoOsherson.simple_updating
#print axioms Literature.ZhaoOsherson.jeffrey_converse_odds
#print axioms Literature.ZhaoOsherson.jeffrey_condBG
#print axioms Literature.ZhaoOsherson.condBG_eq
#print axioms Literature.ZhaoOsherson.converse_invariant_iff
#print axioms Literature.ZhaoOsherson.converse_moves
#print axioms Literature.ZhaoOsherson.converse_at_independence
#print axioms Literature.ZhaoOsherson.jeffrey_movement
#print axioms Literature.ZhaoOsherson.post_condGB
#print axioms Literature.ZhaoOsherson.post_condGNB
#print axioms Literature.ZhaoOsherson.pearl_invariance_iff
#print axioms Literature.ZhaoOsherson.post_sum
#print axioms Literature.ZhaoOsherson.pearl_jeffrey
#print axioms Literature.ZhaoOsherson.deck_isDist
#print axioms Literature.ZhaoOsherson.deck_exact
#print axioms Literature.ZhaoOsherson.deck_objective
#print axioms Literature.ZhaoOsherson.deck_jeffrey_instance
#print axioms Literature.ZhaoOsherson.rain_example
#print axioms Literature.ZhaoOsherson.exp1_design
#print axioms Literature.ZhaoOsherson.exp1_changed_GB
#print axioms Literature.ZhaoOsherson.exp1_changed_GNB
#print axioms Literature.ZhaoOsherson.exp1_changed_total
#print axioms Literature.ZhaoOsherson.exp1_changed_converse
#print axioms Literature.ZhaoOsherson.exp1_means_33_73
#print axioms Literature.ZhaoOsherson.exp1_mean_27_73
#print axioms Literature.ZhaoOsherson.exp1_outliers
#print axioms Literature.ZhaoOsherson.exp1_conditioning_check
#print axioms Literature.ZhaoOsherson.exp2_design
#print axioms Literature.ZhaoOsherson.exp2_lottery
#print axioms Literature.ZhaoOsherson.exp2_ultimatum_counts
#print axioms Literature.ZhaoOsherson.exp2_ultimatum_mean_slip
#print axioms Literature.ZhaoOsherson.exp2_ultimatum_weight
-- END Literature.ZhaoOsherson

-- BEGIN Literature.Zhao2012
#print axioms Literature.Zhao2012.learn_isDist
#print axioms Literature.Zhao2012.learn_prB
#print axioms Literature.Zhao2012.eq1
#print axioms Literature.Zhao2012.learn_invariance
#print axioms Literature.Zhao2012.cond_eq_marg_of_certain
#print axioms Literature.Zhao2012.fn1
#print axioms Literature.Zhao2012.five_per_participant
#print axioms Literature.Zhao2012.exp12_groups
#print axioms Literature.Zhao2012.exp3_groups_disjoint
#print axioms Literature.Zhao2012.swingStates_length
#print axioms Literature.Zhao2012.swingStates_nodup
#print axioms Literature.Zhao2012.exp3_order
#print axioms Literature.Zhao2012.exp3_gaps
#print axioms Literature.Zhao2012.exp3_suppose_near_control
#print axioms Literature.Zhao2012.exp3_between_group
#print axioms Literature.Zhao2012.exp3_interaction
#print axioms Literature.Zhao2012.brier_half
#print axioms Literature.Zhao2012.exp3_penalties
#print axioms Literature.Zhao2012.table1_decks
#print axioms Literature.Zhao2012.table3_decks
#print axioms Literature.Zhao2012.exp2_more_extreme
#print axioms Literature.Zhao2012.extremeness_rows
-- END Literature.Zhao2012

-- BEGIN Literature.Hawthorne
#print axioms Literature.Hawthorne.cellMass_nonneg
#print axioms Literature.Hawthorne.le_cellMass
#print axioms Literature.Hawthorne.le_jointMass
#print axioms Literature.Hawthorne.jointMass_le_cellMass_left
#print axioms Literature.Hawthorne.jointMass_le_cellMass_right
#print axioms Literature.Hawthorne.exists_pos_of_jointMass_pos
#print axioms Literature.Hawthorne.sum_cellMass
#print axioms Literature.Hawthorne.jeffrey_nonneg
#print axioms Literature.Hawthorne.jeffrey_apply
#print axioms Literature.Hawthorne.cellMass_jeffrey
#print axioms Literature.Hawthorne.cellMass_jeffrey_zero
#print axioms Literature.Hawthorne.jeffrey_rigid
#print axioms Literature.Hawthorne.NL_jeffrey
#print axioms Literature.Hawthorne.jeffrey_eq_NL_mul
#print axioms Literature.Hawthorne.basic_sequential
#print axioms Literature.Hawthorne.amnestic_basis_value
#print axioms Literature.Hawthorne.amnestic_thesis
#print axioms Literature.Hawthorne.amnestic_same_basis
#print axioms Literature.Hawthorne.commute_of_jeffreyIndep
#print axioms Literature.Hawthorne.jeffreyIndep_of_commute
#print axioms Literature.Hawthorne.commutation_criterion
#print axioms Literature.Hawthorne.factorUpdate_apply
#print axioms Literature.Hawthorne.cellMass_factorUpdate
#print axioms Literature.Hawthorne.NL_factorUpdate
#print axioms Literature.Hawthorne.LR_factorUpdate
#print axioms Literature.Hawthorne.LR_ratio
#print axioms Literature.Hawthorne.factorUpdate_smul
#print axioms Literature.Hawthorne.jeffrey_eq_factorUpdate
#print axioms Literature.Hawthorne.factorUpdate_seq
#print axioms Literature.Hawthorne.factorUpdate_comm
#print axioms Literature.Hawthorne.extendedRigidity_of_factor
#print axioms Literature.Hawthorne.erLR_iff_erNL
#print axioms Literature.Hawthorne.extendedRigidity_comm
#print axioms Literature.Hawthorne.extUpdate_suitable
#print axioms Literature.Hawthorne.extUpdate_basisOverwrite
#print axioms Literature.Hawthorne.extUpdate_basisCommuting
#print axioms Literature.Hawthorne.seqFactor_eq
#print axioms Literature.Hawthorne.seqFactor_perm
#print axioms Literature.Hawthorne.commutation_theorem
#print axioms Literature.Hawthorne.commutation_append
#print axioms Literature.Hawthorne.med_Qf_C
#print axioms Literature.Hawthorne.med_Qfe_C
#print axioms Literature.Hawthorne.med_Qe_C
#print axioms Literature.Hawthorne.med_Qef_C
#print axioms Literature.Hawthorne.med_order_effect
#print axioms Literature.Hawthorne.med_overwrite
#print axioms Literature.Hawthorne.med_crossBasis
#print axioms Literature.Hawthorne.med_note14
#print axioms Literature.Hawthorne.med_LR_factor
#print axioms Literature.Hawthorne.med_LR_Qf_C
#print axioms Literature.Hawthorne.med_LR_Qfe_Qef
#print axioms Literature.Hawthorne.med_bayesFactorReading
#print axioms Literature.Hawthorne.med_LR_ninths
#print axioms Literature.Hawthorne.med_NL_denominator
#print axioms Literature.Hawthorne.nl_denominator_indep
#print axioms Literature.Hawthorne.blk_commute
#print axioms Literature.Hawthorne.blk_r
#print axioms Literature.Hawthorne.blk_clause2
#print axioms Literature.Hawthorne.blk_not_extendedRigidity
#print axioms Literature.Hawthorne.criterion_needs_positive_cells
-- END Literature.Hawthorne

-- BEGIN Literature.DiaconisZabell
#print axioms Literature.DiaconisZabell.mem_cellSet
#print axioms Literature.DiaconisZabell.marg_pos
#print axioms Literature.DiaconisZabell.marg_pos_of_surj
#print axioms Literature.DiaconisZabell.marg_nonneg
#print axioms Literature.DiaconisZabell.mass_inter_cell_jeffrey
#print axioms Literature.DiaconisZabell.marg_jeffrey_eq
#print axioms Literature.DiaconisZabell.marg_jeffrey
#print axioms Literature.DiaconisZabell.exists_mem_of_marg_ne_zero
#print axioms Literature.DiaconisZabell.jeffrey_jcond
#print axioms Literature.DiaconisZabell.mass_eq_sum_cells
#print axioms Literature.DiaconisZabell.sum_eq_sum_marg
#print axioms Literature.DiaconisZabell.jeffrey_mass
#print axioms Literature.DiaconisZabell.jeffrey_self
#print axioms Literature.DiaconisZabell.thm22_factorization
#print axioms Literature.DiaconisZabell.jcond_iff_jeffrey
#print axioms Literature.DiaconisZabell.eq_jeffrey_of_jcond
#print axioms Literature.DiaconisZabell.jcond_iff_ratio_const
#print axioms Literature.DiaconisZabell.thm22_lr_sufficient
#print axioms Literature.DiaconisZabell.thm22_lr_minimal
#print axioms Literature.DiaconisZabell.jcond_of_refines
#print axioms Literature.DiaconisZabell.jcond_atoms
#print axioms Literature.DiaconisZabell.jcond_trivial_self
#print axioms Literature.DiaconisZabell.lr_jeffrey_iff
#print axioms Literature.DiaconisZabell.thm21
#print axioms Literature.DiaconisZabell.thm21_finite
#print axioms Literature.DiaconisZabell.jeffrey_feasible
#print axioms Literature.DiaconisZabell.fdiv_jeffrey
#print axioms Literature.DiaconisZabell.cell_jensen
#print axioms Literature.DiaconisZabell.thm61_le
#print axioms Literature.DiaconisZabell.thm61_unique
#print axioms Literature.DiaconisZabell.fdiv_mulLog_eq_KL
#print axioms Literature.DiaconisZabell.KL_jeffrey
#print axioms Literature.DiaconisZabell.thm51_KL_le
#print axioms Literature.DiaconisZabell.thm51_KL_eq_iff
#print axioms Literature.DiaconisZabell.strictConvexOn_fH
#print axioms Literature.DiaconisZabell.mul_fH
#print axioms Literature.DiaconisZabell.fdiv_fH_eq_hellinger
#print axioms Literature.DiaconisZabell.thm51_hellinger_le
#print axioms Literature.DiaconisZabell.thm51_hellinger_eq_iff
#print axioms Literature.DiaconisZabell.thm51_tv_le
#print axioms Literature.DiaconisZabell.tv_jeffrey
#print axioms Literature.DiaconisZabell.remark_a_tv_not_unique
#print axioms Literature.DiaconisZabell.example51
#print axioms Literature.DiaconisZabell.jeffrey_apply
#print axioms Literature.DiaconisZabell.jeffrey_pos
#print axioms Literature.DiaconisZabell.sum_jeffrey
#print axioms Literature.DiaconisZabell.thm32
#print axioms Literature.DiaconisZabell.thm32_needs_qualitative_independence
#print axioms Literature.DiaconisZabell.thm33_forward
#print axioms Literature.DiaconisZabell.P2_pos_iff
#print axioms Literature.DiaconisZabell.cellSet_fst
#print axioms Literature.DiaconisZabell.cellSet_snd
#print axioms Literature.DiaconisZabell.marg_fst
#print axioms Literature.DiaconisZabell.marg_snd
#print axioms Literature.DiaconisZabell.marg_P2_fst
#print axioms Literature.DiaconisZabell.marg_P2_snd
#print axioms Literature.DiaconisZabell.marg_jE_snd
#print axioms Literature.DiaconisZabell.marg_jF_fst
#print axioms Literature.DiaconisZabell.remark826
#print axioms Literature.DiaconisZabell.thm32_2x2
#print axioms Literature.DiaconisZabell.commute_of_indep
#print axioms Literature.DiaconisZabell.not_commute_of_corr
#print axioms Literature.DiaconisZabell.witness_gap
#print axioms Literature.DiaconisZabell.example32
#print axioms Literature.DiaconisZabell.example34
#print axioms Literature.DiaconisZabell.marg_prod_fst
#print axioms Literature.DiaconisZabell.marg_prod_snd
#print axioms Literature.DiaconisZabell.example33
-- END Literature.DiaconisZabell

-- BEGIN Literature.Field
#print axioms Literature.Field.oddsRatio_pos
#print axioms Literature.Field.exp_two_alphaOf
#print axioms Literature.Field.exp_alphaOf_sq
#print axioms Literature.Field.exp_two_alphaOf_bayes
#print axioms Literature.Field.qOf_eq_bayesPost
#print axioms Literature.Field.qOf_pos
#print axioms Literature.Field.qOf_lt_one
#print axioms Literature.Field.qOf_alphaOf
#print axioms Literature.Field.alphaOf_qOf
#print axioms Literature.Field.reweight_reweight
#print axioms Literature.Field.sum_tiltW_pos
#print axioms Literature.Field.tilt_zero
#print axioms Literature.Field.tilt_eq_jeffrey
#print axioms Literature.Field.field_eq7
#print axioms Literature.Field.field_eq7_comm
#print axioms Literature.Field.reweight_cells_eq_jeffrey
#print axioms Literature.Field.jeffrey_EE'
#print axioms Literature.Field.jeffrey_E'E
#print axioms Literature.Field.jeffrey_not_comm
#print axioms Literature.Field.tilt_comm_P₀
-- END Literature.Field

-- BEGIN Literature.Garber
#print axioms Literature.Garber.fieldStep_pos
#print axioms Literature.Garber.fieldStep_lt_one
#print axioms Literature.Garber.odds_fieldStep
#print axioms Literature.Garber.iterate_mem
#print axioms Literature.Garber.odds_iterate
#print axioms Literature.Garber.eq_of_odds
#print axioms Literature.Garber.odds_injOn
#print axioms Literature.Garber.fieldStep_iterate
#print axioms Literature.Garber.iterate_eq_of_lr
#print axioms Literature.Garber.garber_lr
#print axioms Literature.Garber.exp_near
#print axioms Literature.Garber.garber_alpha_4dp
#print axioms Literature.Garber.garberSeq_closed
#print axioms Literature.Garber.garber_table
#print axioms Literature.Garber.garber_prose_typo
#print axioms Literature.Garber.garber_nine
#print axioms Literature.Garber.richer_lr
#print axioms Literature.Garber.richerSeq_closed
#print axioms Literature.Garber.richer_five
#print axioms Literature.Garber.fieldStep_iterate_tendsto_one
-- END Literature.Garber

-- BEGIN Literature.Epstein
#print axioms Literature.Epstein.cond_sum
#print axioms Literature.Epstein.joint_eq_marg_mul_cond
#print axioms Literature.Epstein.sum_marg2
#print axioms Literature.Epstein.sum_marg1
#print axioms Literature.Epstein.tower
#print axioms Literature.Epstein.menuU_singleton
#print axioms Literature.Epstein.marg1_pstar
#print axioms Literature.Epstein.cond_pstar
#print axioms Literature.Epstein.cond_pstar_mix
#print axioms Literature.Epstein.compromise_objective
#print axioms Literature.Epstein.bayes_of_alpha_zero
#print axioms Literature.Epstein.priorBias_sum
#print axioms Literature.Epstein.priorBias_nonneg
#print axioms Literature.Epstein.cor3_case1
#print axioms Literature.Epstein.overreaction_form
#print axioms Literature.Epstein.cond_pstar_priorBias
#print axioms Literature.Epstein.pstar_deviation
#print axioms Literature.Epstein.gam_lt_one
#print axioms Literature.Epstein.gam_nonneg
#print axioms Literature.Epstein.gam_nonpos
#print axioms Literature.Epstein.gam_eq_zero_iff
#print axioms Literature.Epstein.bayes_of_lam_zero
#print axioms Literature.Epstein.cond_eq_marg2_of_product
#print axioms Literature.Epstein.priorBias_of_neutral
#print axioms Literature.Epstein.bayes_of_product
#print axioms Literature.Epstein.cond_eq_marg2_of_subsingleton
#print axioms Literature.Epstein.not_bayes_of_nonneutral
#print axioms Literature.Epstein.priorBias_absCont
#print axioms Literature.Epstein.sensitivity_scaled
#print axioms Literature.Epstein.confirm_marginal
#print axioms Literature.Epstein.confirm_iff
#print axioms Literature.Epstein.representativeness
#print axioms Literature.Epstein.sampleBias_nonneg_iff
#print axioms Literature.Epstein.pstar_average
#print axioms Literature.Epstein.pstar_average_const
#print axioms Literature.Epstein.priorBias_no_uniform_reversal
#print axioms Literature.Epstein.exP_marg1
#print axioms Literature.Epstein.exP_cond
#print axioms Literature.Epstein.exQ_sum
#print axioms Literature.Epstein.lie_violation_example
#print axioms Literature.Epstein.priorBias_eq_damped
#print axioms Literature.Epstein.compromise_eq_damped
#print axioms Literature.Epstein.omegaEff_eq
#print axioms Literature.Epstein.omegaEff_pos
#print axioms Literature.Epstein.omegaEff_positive
#print axioms Literature.Epstein.omegaEff_negative
#print axioms Literature.Epstein.omegaEff_surj
#print axioms Literature.Epstein.damped_deviation
#print axioms Literature.Epstein.omega_identified
#print axioms Literature.Epstein.dampedJeffrey_eq_mix
-- END Literature.Epstein

-- BEGIN Literature.Ortoleva
#print axioms Literature.Ortoleva.prob_nonneg
#print axioms Literature.Ortoleva.prob_mono
#print axioms Literature.Ortoleva.bayes_of_not_mem
#print axioms Literature.Ortoleva.prob_bayes
#print axioms Literature.Ortoleva.prob_bayes_self
#print axioms Literature.Ortoleva.bayes_isBelief
#print axioms Literature.Ortoleva.bayes_consAt
#print axioms Literature.Ortoleva.eu_splice_sub
#print axioms Literature.Ortoleva.eu_pt
#print axioms Literature.Ortoleva.thm1_if
#print axioms Literature.Ortoleva.thm1_only_if
#print axioms Literature.Ortoleva.thm1_iff
#print axioms Literature.Ortoleva.HT.score_nonneg
#print axioms Literature.Ortoleva.HT.denom_pos
#print axioms Literature.Ortoleva.HT.rhoBU_le_iff
#print axioms Literature.Ortoleva.HT.score_le_sel
#print axioms Literature.Ortoleva.HT.sel_unique_score
#print axioms Literature.Ortoleva.HT.score_sel_pos
#print axioms Literature.Ortoleva.HT.prob_sel_pos
#print axioms Literature.Ortoleva.HT.post_of_gt
#print axioms Literature.Ortoleva.HT.post_of_le
#print axioms Literature.Ortoleva.HT.ht_bayes_of_gt
#print axioms Literature.Ortoleva.HT.ht_consequentialism
#print axioms Literature.Ortoleva.HT.ht_prob_self
#print axioms Literature.Ortoleva.HT.post_isBelief
#print axioms Literature.Ortoleva.cycle_const
#print axioms Literature.Ortoleva.edge_support
#print axioms Literature.Ortoleva.edge_prob_le
#print axioms Literature.Ortoleva.bayes_cycle
#print axioms Literature.Ortoleva.HT.nonempty_of_edge
#print axioms Literature.Ortoleva.HT.edge_high
#print axioms Literature.Ortoleva.HT.edge_low
#print axioms Literature.Ortoleva.HT.ht_dynamicCoherence
#print axioms Literature.Ortoleva.HT.ht_eps_zero_bayes
#print axioms Literature.Ortoleva.HT.ht_eps_zero_dynCons
#print axioms Literature.Ortoleva.HT.ht_dynCons_same_as_eps_zero
#print axioms Literature.Ortoleva.HT.ht_minimal_dynCons_eps_zero
#print axioms Literature.Ortoleva.prob_eq_sum_ite
#print axioms Literature.Ortoleva.exP_nonneg
#print axioms Literature.Ortoleva.exρ_pos
#print axioms Literature.Ortoleva.ex_no_tie
#print axioms Literature.Ortoleva.ex_prob_A
#print axioms Literature.Ortoleva.ex_unexpected
#print axioms Literature.Ortoleva.ex_sel_A
#print axioms Literature.Ortoleva.ex_bayes_A
#print axioms Literature.Ortoleva.ex_ht_A
#print axioms Literature.Ortoleva.ex_departs
#print axioms Literature.Ortoleva.ex_likely
#print axioms Literature.Ortoleva.ex_not_dynCons
-- END Literature.Ortoleva

-- BEGIN Literature.Tao
#print axioms Literature.Tao.ex_1_4_23_ii
#print axioms Literature.Tao.ex_1_4_23_iii
#print axioms Literature.Tao.ex_1_4_23_iii_needs_finite
#print axioms Literature.Tao.thm_1_7_15
#print axioms Literature.Tao.thm_1_7_18
#print axioms Literature.Tao.tonelli_swap
#print axioms Literature.Tao.measure_band_tendsto_zero
#print axioms Literature.Tao.measurableSet_band
#print axioms Literature.Tao.band_mono
#print axioms Literature.Tao.band_iInter_empty
#print axioms Literature.Tao.los_step4
#print axioms Literature.Tao.los_step4_littleO
#print axioms Literature.Tao.los_step3_marginal
#print axioms Literature.Tao.los_step3_bound
-- END Literature.Tao

-- BEGIN Literature.Becker
#print axioms Literature.Becker.budgetLine_midpoint
#print axioms Literature.Becker.budgetLine_param
#print axioms Literature.Becker.impulsive_mean
#print axioms Literature.Becker.impulsive_integrable
#print axioms Literature.Becker.impulsive_market_average
#print axioms Literature.Becker.impulsive_demand_strictAnti
#print axioms Literature.Becker.impulsive_unit_elastic
#print axioms Literature.Becker.rotation_through_point
#print axioms Literature.Becker.compensated_midpoint_shift
#print axioms Literature.Becker.constraint_without_averaging
#print axioms Literature.Becker.averaging_without_constraint
#print axioms Literature.Becker.inert_outside_iff
#print axioms Literature.Becker.inert_decline_of_mean_gt
#print axioms Literature.Becker.inert_decline_not_necessary
#print axioms Literature.Becker.inert_fn14
#print axioms Literature.Becker.inert_fn14_change
#print axioms Literature.Becker.inert_fn14_elasticity
#print axioms Literature.Becker.inert_elasticity_formula
#print axioms Literature.Becker.inert_elasticity_smaller_change
#print axioms Literature.Becker.mixture_strictAnti
-- END Literature.Becker

-- BEGIN Literature.Wagner2002
#print axioms Literature.Wagner2002.eq13
#print axioms Literature.Wagner2002.mem_cell
#print axioms Literature.Wagner2002.pr_eq_mul_of_forall
#print axioms Literature.Wagner2002.pr_cell_of_mul
#print axioms Literature.Wagner2002.sum_pr_cell
#print axioms Literature.Wagner2002.pr_split
#print axioms Literature.Wagner2002.pr_pos_of_mul
#print axioms Literature.Wagner2002.kin_eq
#print axioms Literature.Wagner2002.pr_kin_cell
#print axioms Literature.Wagner2002.ComesByPK.p_pos
#print axioms Literature.Wagner2002.ComesByPK.cell_eq
#print axioms Literature.Wagner2002.ComesByPK.pos
#print axioms Literature.Wagner2002.ComesByPK.sum_cell
#print axioms Literature.Wagner2002.ComesByPK.pf_pos
#print axioms Literature.Wagner2002.ComesByPK.factor
#print axioms Literature.Wagner2002.ComesByPK.nonempty
#print axioms Literature.Wagner2002.ComesByPK.prob
#print axioms Literature.Wagner2002.eq21
#print axioms Literature.Wagner2002.eq23
#print axioms Literature.Wagner2002.ratio_iff_prop
#print axioms Literature.Wagner2002.eq_of_prop
#print axioms Literature.Wagner2002.eq_normalize
#print axioms Literature.Wagner2002.eq_of_ratio
#print axioms Literature.Wagner2002.common_numerator
#print axioms Literature.Wagner2002.two_step
#print axioms Literature.Wagner2002.two_step'
#print axioms Literature.Wagner2002.thm31
#print axioms Literature.Wagner2002.remark32
#print axioms Literature.Wagner2002.remark33
#print axioms Literature.Wagner2002.sum_cell_of_prob
#print axioms Literature.Wagner2002.thm32_E
#print axioms Literature.Wagner2002.thm32_F
#print axioms Literature.Wagner2002.remark34
#print axioms Literature.Wagner2002.remark34_indep
#print axioms Literature.Wagner2002.pos_pair
#print axioms Literature.Wagner2002.pr_nonneg
#print axioms Literature.Wagner2002.thm41
#print axioms Literature.Wagner2002.nonempty_of_prob
#print axioms Literature.Wagner2002.remark41_qi
#print axioms Literature.Wagner2002.remark41_FeqE
#print axioms Literature.Wagner2002.sec4_FeqE
#print axioms Literature.Wagner2002.remark43
#print axioms Literature.Wagner2002.remark42
#print axioms Literature.Wagner2002.eq35
#print axioms Literature.Wagner2002.sum_cells
#print axioms Literature.Wagner2002.eq37
#print axioms Literature.Wagner2002.remark31
#print axioms Literature.Wagner2002.pr_cond
#print axioms Literature.Wagner2002.bf_cond
#print axioms Literature.Wagner2002.cond_cond
#print axioms Literature.Wagner2002.note8
#print axioms Literature.Wagner2002.kin_kin
#print axioms Literature.Wagner2002.remark52
#print axioms Literature.Wagner2002.remark52_bf
#print axioms Literature.Wagner2002.note7
#print axioms Literature.Wagner2002.ratio_of_pf
#print axioms Literature.Wagner2002.eq55
#print axioms Literature.Wagner2002.eq55_exists
#print axioms Literature.Wagner2002.kin_isPK
#print axioms Literature.Wagner2002.pf_kin
#print axioms Literature.Wagner2002.PB_endpoint
#print axioms Literature.Wagner2002.pos_cross
#print axioms Literature.Wagner2002.PB_endpoint_exists
#print axioms Literature.Wagner2002.PB_unique
#print axioms Literature.Wagner2002.completion
#print axioms Literature.Wagner2002.pr_fst
#print axioms Literature.Wagner2002.pr_snd
#print axioms Literature.Wagner2002.grid_43_44
#print axioms Literature.Wagner2002.p₀_prob
#print axioms Literature.Wagner2002.p₀_fst
#print axioms Literature.Wagner2002.p₀_snd
#print axioms Literature.Wagner2002.benchmark_p₀
#print axioms Literature.Wagner2002.JAB_p₀
#print axioms Literature.Wagner2002.JBA_p₀
#print axioms Literature.Wagner2002.wagner_does_not_single_out_PB
#print axioms Literature.Wagner2002.sec4_example
-- END Literature.Wagner2002

-- BEGIN Literature.Wagner2003
#print axioms Literature.Wagner2003.mem_cell
#print axioms Literature.Wagner2003.eq14
#print axioms Literature.Wagner2003.eq_of_ratio
#print axioms Literature.Wagner2003.eq23_iff_eq24
#print axioms Literature.Wagner2003.thm21
#print axioms Literature.Wagner2003.remark21
#print axioms Literature.Wagner2003.eq27
#print axioms Literature.Wagner2003.eq27_exists
#print axioms Literature.Wagner2003.pr_eq_mul_of_forall
#print axioms Literature.Wagner2003.pr_pos
#print axioms Literature.Wagner2003.eq33
#print axioms Literature.Wagner2003.bfa_of_PK
#print axioms Literature.Wagner2003.thm31
#print axioms Literature.Wagner2003.thm32
#print axioms Literature.Wagner2003.remark32
#print axioms Literature.Wagner2003.condBF_atoms
#print axioms Literature.Wagner2003.bfa_eq_iff
#print axioms Literature.Wagner2003.thm41
#print axioms Literature.Wagner2003.DI_eq
#print axioms Literature.Wagner2003.critI_d
#print axioms Literature.Wagner2003.critI_pi
#print axioms Literature.Wagner2003.critII_pi
#print axioms Literature.Wagner2003.critIII_d
#print axioms Literature.Wagner2003.critIII_pi
#print axioms Literature.Wagner2003.pi_absurdity
#print axioms Literature.Wagner2003.absurdity_needs_learning
#print axioms Literature.Wagner2003.finite_never_materializes
#print axioms Literature.Wagner2003.pr_Epart
#print axioms Literature.Wagner2003.note4_q_PK
#print axioms Literature.Wagner2003.note4_same_d
#print axioms Literature.Wagner2003.note4_conditionals
#print axioms Literature.Wagner2003.note4_d_fails_critII
-- END Literature.Wagner2003

-- BEGIN Literature.PettigrewWeisberg
#print axioms Literature.PettigrewWeisberg.opening_example
#print axioms Literature.PettigrewWeisberg.eq3
#print axioms Literature.PettigrewWeisberg.no_prior_opinion
#print axioms Literature.PettigrewWeisberg.beta_is_bf
#print axioms Literature.PettigrewWeisberg.upco_eq_self_iff
#print axioms Literature.PettigrewWeisberg.naive_opinion
#print axioms Literature.PettigrewWeisberg.mem_cell
#print axioms Literature.PettigrewWeisberg.upcoV_binary
#print axioms Literature.PettigrewWeisberg.le_marg
#print axioms Literature.PettigrewWeisberg.sum_marg
#print axioms Literature.PettigrewWeisberg.sum_fiber_mul
#print axioms Literature.PettigrewWeisberg.jpool_upco
#print axioms Literature.PettigrewWeisberg.jpool_upco_nonneg
#print axioms Literature.PettigrewWeisberg.route
#print axioms Literature.PettigrewWeisberg.thm5
#print axioms Literature.PettigrewWeisberg.nonempty_of_prob
#print axioms Literature.PettigrewWeisberg.normalizer_pos
#print axioms Literature.PettigrewWeisberg.thm1
#print axioms Literature.PettigrewWeisberg.marg_fst
#print axioms Literature.PettigrewWeisberg.marg_snd
#print axioms Literature.PettigrewWeisberg.jpool_tbl_fst
#print axioms Literature.PettigrewWeisberg.example_P1
#print axioms Literature.PettigrewWeisberg.example_P2
#print axioms Literature.PettigrewWeisberg.example_other_order
#print axioms Literature.PettigrewWeisberg.n_pos_of
#print axioms Literature.PettigrewWeisberg.unif_posProb
#print axioms Literature.PettigrewWeisberg.reg_mE
#print axioms Literature.PettigrewWeisberg.reg_mF
#print axioms Literature.PettigrewWeisberg.mE_jE
#print axioms Literature.PettigrewWeisberg.mF_jF
#print axioms Literature.PettigrewWeisberg.jE_reg
#print axioms Literature.PettigrewWeisberg.jF_reg
#print axioms Literature.PettigrewWeisberg.wagner_grid
#print axioms Literature.PettigrewWeisberg.sum_Peps_row
#print axioms Literature.PettigrewWeisberg.Peps_facts
#print axioms Literature.PettigrewWeisberg.mE_jF_Peps
#print axioms Literature.PettigrewWeisberg.eps_seq
#print axioms Literature.PettigrewWeisberg.tendsto_w
#print axioms Literature.PettigrewWeisberg.posProb_eq_of_ratio
#print axioms Literature.PettigrewWeisberg.exists_lt_of_ne
#print axioms Literature.PettigrewWeisberg.lemma7
#print axioms Literature.PettigrewWeisberg.prop_to_upco
#print axioms Literature.PettigrewWeisberg.thm8_regular
#print axioms Literature.PettigrewWeisberg.upco_regPres
#print axioms Literature.PettigrewWeisberg.upco_UP
#print axioms Literature.PettigrewWeisberg.upco_unif
#print axioms Literature.PettigrewWeisberg.upco_mono
#print axioms Literature.PettigrewWeisberg.upco_symm
#print axioms Literature.PettigrewWeisberg.upco_cont
#print axioms Literature.PettigrewWeisberg.jE_upco
#print axioms Literature.PettigrewWeisberg.jF_upco
#print axioms Literature.PettigrewWeisberg.upco_commutes
#print axioms Literature.PettigrewWeisberg.upco_matched
#print axioms Literature.PettigrewWeisberg.PB_is_upco_pooling
#print axioms Literature.PettigrewWeisberg.PB_vs_example
-- END Literature.PettigrewWeisberg
