import Literature.Arrow
import Literature.Asch
import Literature.AugenblickRabin
import Literature.BCGS
import Literature.BHW
import Literature.Banerjee
import Literature.BenjaminBodohCreedRabin
import Literature.BohrenImasRosenberg
import Literature.CoateLoury
import Literature.Cripps
import Literature.Dietrich
import Literature.Domotor
import Literature.Doring
import Literature.FGT
import Literature.GoodMittal
import Literature.Heckman
import Literature.HogarthEinhorn
import Literature.Jeffrey
import Literature.Phelps
import Literature.ShmayaYariv
import Literature.Weisberg
import Literature.Zhao2012
import Literature.ZhaoOsherson
