import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def read(name):
    p = os.path.join(ROOT, name)
    return open(p).read() if os.path.exists(p) else ""


def cites(text, key):
    return sum(len(re.findall(rf"(?:^|,)\s*{re.escape(key)}\s*(?=,|$)", m))
               for m in re.findall(r"\\cite[a-zA-Z]*\*?(?:\[[^\]]*\])*\{([^}]*)\}", text))


bib = re.findall(r"^@\w+\{([^,]+),", read("refs.bib"), re.M)
mapsrc = read("MEASUREMENT_MAP.tex")
mapkeys = re.findall(r"\\bibitem(?:\[[^\]]*\])?\{([^}]+)\}", mapsrc)
keys = bib + [k for k in mapkeys if k not in bib]
docs = {"PROOFS": read("PROOFS.tex"), "LITERATURE": read("LITERATURE.tex"), "MAP": mapsrc}

owner = {}
for d in sorted(os.listdir(HERE)):
    kf = os.path.join(HERE, d, "KEYS")
    if os.path.isfile(kf):
        for k in open(kf).read().split():
            owner[k] = d


def lean_info(d):
    if d is None:
        return "", 0
    files = [f for f in os.listdir(os.path.join(HERE, d)) if f.endswith(".lean")]
    n = sum(len(re.findall(r"^theorem\s", open(os.path.join(HERE, d, f)).read(), re.M)) for f in files)
    return ", ".join(sorted(files)), n


rows = []
for k in keys:
    c = {n: cites(t, k) for n, t in docs.items()}
    d = owner.get(k)
    lf, nt = lean_info(d)
    rows.append((k, c["PROOFS"], c["LITERATURE"], c["MAP"], d or "", lf, nt))

tier = lambda r: (0 if r[1] else 1 if r[3] else 2, r[0])
rows.sort(key=tier)
with_lean = sum(1 for r in rows if r[5])
p_rows = [r for r in rows if r[1]]
lines = [
    "# Literature coverage",
    "",
    "Generated by `lit/coverage.py` from `refs.bib`, the citations in `PROOFS.tex`,",
    "`LITERATURE.tex` and `MEASUREMENT_MAP.tex`, and the `KEYS` file in each paper",
    "directory. Do not edit by hand.",
    "",
    f"Cited works {len(rows)}. With a Lean file {with_lean}. Cited in PROOFS.tex "
    f"{len(p_rows)}, of which with a Lean file {sum(1 for r in p_rows if r[5])}.",
    "",
    "| Key | PROOFS | LITERATURE | MAP | Directory | Lean | Theorems |",
    "|---|---|---|---|---|---|---|",
]
for r in rows:
    lines.append(f"| {r[0]} | {r[1]} | {r[2]} | {r[3]} | {r[4]} | {r[5]} | {r[6] or ''} |")
open(os.path.join(HERE, "COVERAGE.md"), "w").write("\n".join(lines) + "\n")
print(lines[6])
