/-
# Wagner (2003), "Commuting Probability Revisions: The Uniformity Rule"

*Erkenntnis* 59(3), 349-364 ("In Memoriam Richard Jeffrey, 1926-2002").  The copy is the
JSTOR scan (cover page plus journal pp. 349-364); page references are journal pages, and
every formula was read on the rendered page.  Notation `β^q_p`, `π^q_p` is the paper's
(`β_{q,p}`, `π_{q,p}` in Wagner 2002).  "It is assumed throughout this paper that all
probabilities are strictly coherent" (p. 350): here `SC p`, every atom positive.

## Setting

A *purely atomic* σ-algebra has countably many atoms that partition `Ω` (p. 349); every
finite algebra is purely atomic.  Here the algebra is finite and its atoms are the elements
of a finite type `α`; events are `Finset α`; a partition of the atoms is a labelling
`E : α → ι` with nonempty cells.

## What is proved

**Section 2.**
* `thm21`: **Theorem 2.1** (p. 351).  Schema (2.1), `p → Q → r` and `p → q → R`: the
  atomic identities (2.2) `β^r_Q(A:B) = β^q_p(A:B)` and (2.3) `β^R_q(A:B) = β^Q_p(A:B)` imply
  `r = R`.  `eq23_iff_eq24` is the proof's "trivially, (2.3) is equivalent to (2.4)".
* `remark21`: **Remark 2.1**, (2.6).  `eq27`: **Remark 2.2**, formula (2.7),
  `r(A) = R(A) = [q(A)Q(A)/p(A)] / Σ q(A')Q(A')/p(A')`.  `eq27_exists`: on a finite
  algebra the sum is finite, so (2.7) always defines `r = R`.

**Section 3.**
* `thm31`: **Theorem 3.1** (p. 353): with `q` from `p` by kinematics on `E`, `r` satisfies
  the atomic identities (3.5) iff `r` comes from `Q` by kinematics on `E` and (3.6) holds.
* `thm32`: **Theorem 3.2** (p. 354), the Field/Wagner two-partition theorem: the 2002 result
  restated for an arbitrary σ-algebra (Remark 3.1), derived as Wagner derives it, from
  Theorem 2.1 via Theorem 3.1.  Theorem 2.1 is not itself the 2002 result; Wagner calls it "the
  fundamental result" (Remark 3.2).  Wagner reduces the arbitrary σ-algebra to the purely
  atomic algebra generated by `E ∪ F ∪ {G}`; on a finite space that step is not needed.
  Unlike Wagner 2002's version it assumes strict coherence.
* `remark32`: **Remark 3.2**, any strictly coherent `q` comes from `p` by kinematics on the
  partition of all atoms.

**Section 4** (explanation-based revision; the old-evidence application is Section 4 only).
* `thm41`: **Theorem 4.1** (pp. 356-357): on the four atoms of `{H, E}`, (4.5) iff the three
  conditional Bayes factor identities (4.6)-(4.8).  (4.9)-(4.13) are not formalized.

**Section 5** (pp. 360-362): *three* indices, the difference `d = δ` (`dI`), the normalized
difference `D` (`DI`), and the probability factor `π` (`pia`); `DI_eq`: `D = π - 1`, so "`D`
and `π` stand or fall together".  Criteria: I (commutativity), II ("learning identical to
that prompting a probability-kinematical revision should prompt a probability-kinematical
revision **on the same partition**"), III (not unduly restricting priors).
* `critI_d`, `critI_pi`: both `d` and `π` satisfy I.
* `critII_pi`: `π` satisfies II.  `note4_d_fails_critII`: **note 4** (p. 363), `d` fails II,
  with Wagner's numbers exactly: `q` comes from `p` by kinematics on `{E, Ē}`, `q' - p' = q - p`
  on every atom, yet `q'` does not come from `p'` that way; `note4_conditionals`:
  `q'(H|E) = 22/35 ≈ .6286` against `p'(H|E) = .5`.
* `critIII_d`, `critIII_pi`: the Criterion III failures (an atom with `Q(A) > 1 - d^q_p(A)`,
  resp. `Q(A) > 1/π^q_p(A)`, precludes any `r`).
* `pi_absurdity`: "the point of absurdity" (p. 361, note 5): with two atoms, unless `Q = p`
  no `r` satisfies (5.1) for `ν = π`.  Note 5's algebra divides by a quantity that vanishes
  when `q = p`; the formal statement needs `q ≠ p` (some learning occurred), and
  `absurdity_needs_learning` shows `r = Q` works when `q = p`.
* `finite_never_materializes`: the finite case of (5.3)-(5.5) and Theorem 5.1: with
  finitely many atoms every positive Bayes factor vector is realizable from every prior.

Not formalized: the infinite purely atomic case (convergence of (2.7) and Theorem 5.1's
construction), (4.9)-(4.13).
-/
import Mathlib

namespace Literature.Wagner2003

set_option linter.unusedSectionVars false

open Finset

variable {α ι κ : Type*} [Fintype α] [DecidableEq α] [Fintype ι] [DecidableEq ι]
  [Fintype κ] [DecidableEq κ]

/-- Strict coherence (p. 350), on a finite purely atomic algebra whose atoms are the elements
of `α`: every atom has positive probability. -/
def SC (p : α → ℝ) : Prop := (∀ a, 0 < p a) ∧ ∑ a, p a = 1

noncomputable def pr (p : α → ℝ) (A : Finset α) : ℝ := ∑ a ∈ A, p a

def cell (E : α → ι) (i : ι) : Finset α := univ.filter (fun a => E a = i)

@[simp] theorem mem_cell {E : α → ι} {i : ι} {a : α} : a ∈ cell E i ↔ E a = i := by simp [cell]

/-- (1.2) the Bayes factor `β^q_p(A : B)` of events. -/
noncomputable def bf (q p : α → ℝ) (A B : Finset α) : ℝ := (pr q A / pr q B) / (pr p A / pr p B)

/-- (1.2) at atoms. -/
noncomputable def bfa (q p : α → ℝ) (a b : α) : ℝ := (q a / q b) / (p a / p b)

/-- (1.1) the probability factor `π^q_p` at atoms. -/
noncomputable def pia (q p : α → ℝ) (a : α) : ℝ := q a / p a

/-- (1.4) `β^q_p(A : B) = π^q_p(A) / π^q_p(B)`. -/
theorem eq14 (q p : α → ℝ) (a b : α) : bfa q p a b = pia q p a / pia q p b := by
  unfold bfa pia; rw [div_div_div_comm]

/-! ## Section 2: Theorem 2.1 and Remarks 2.1-2.2 -/

theorem eq_of_ratio {x y : α → ℝ} (hx : SC x) (hy : SC y) (h : ∀ a b, x a / x b = y a / y b) :
    x = y := by
  obtain ⟨b⟩ : Nonempty α := by
    by_contra h0; rw [not_nonempty_iff] at h0; have := hx.2; simp at this
  have hc : ∀ a, x a = (x b / y b) * y a := by
    intro a; have h1 := h a b; have := (hx.1 b).ne'; have := (hy.1 b).ne'
    field_simp at h1 ⊢; linarith
  have hs : ∑ a, x a = (x b / y b) * ∑ a, y a := by rw [mul_sum]; exact sum_congr rfl fun a _ => hc a
  rw [hx.2, hy.2, mul_one] at hs
  funext a; rw [hc a, ← hs, one_mul]

/-- "Trivially, (2.3) is equivalent to (2.4)." -/
theorem eq23_iff_eq24 {p q Q R : α → ℝ} (hp : SC p) (hq : SC q) (hQ : SC Q) (hR : SC R) :
    (∀ a b, bfa R q a b = bfa Q p a b) ↔ ∀ a b, bfa R Q a b = bfa q p a b := by
  have key : ∀ a b, bfa R q a b = bfa Q p a b ↔ bfa R Q a b = bfa q p a b := by
    intro a b; unfold bfa
    have := (hp.1 a).ne'; have := (hp.1 b).ne'; have := (hq.1 a).ne'; have := (hq.1 b).ne'
    have := (hQ.1 a).ne'; have := (hQ.1 b).ne'; have := (hR.1 a).ne'; have := (hR.1 b).ne'
    rw [div_eq_div_iff (by positivity) (by positivity), div_eq_div_iff (by positivity) (by positivity)]
    constructor <;> intro h <;> field_simp at h ⊢ <;> linarith
  exact ⟨fun h a b => (key a b).1 (h a b), fun h a b => (key a b).2 (h a b)⟩

/-- **Theorem 2.1** (p. 351).  In the revision schema (2.1) (`p → Q → r` and `p → q → R`) on a
purely atomic algebra, the atomic Bayes factor identities (2.2) `β^r_Q(A:B) = β^q_p(A:B)` and
(2.3) `β^R_q(A:B) = β^Q_p(A:B)` imply `r = R`.  Here the algebra is finite (every finite
σ-algebra is purely atomic) and, as throughout the paper, all probabilities are strictly
coherent. -/
theorem thm21 {p q Q r R : α → ℝ} (hp : SC p) (hq : SC q) (hQ : SC Q) (hr : SC r) (hR : SC R)
    (h22 : ∀ a b, bfa r Q a b = bfa q p a b) (h23 : ∀ a b, bfa R q a b = bfa Q p a b) :
    r = R := by
  have h24 := (eq23_iff_eq24 hp hq hQ hR).1 h23
  -- (2.5): the `r`-odds and the `R`-odds are the `Q`-odds times the same factor
  refine eq_of_ratio hr hR fun a b => ?_
  have h25 : bfa r Q a b = bfa R Q a b := by rw [h22, h24]
  unfold bfa at h25
  have := (hQ.1 a).ne'; have := (hQ.1 b).ne'
  exact (div_left_inj' (div_ne_zero (hQ.1 a).ne' (hQ.1 b).ne')).1 h25

/-- **Remark 2.1**, (2.6): (2.2) is equivalent to `π^r_Q(A) ∝ π^q_p(A)`, the constant being
`π^r_Q(B)/π^q_p(B)` for any atom `B`. -/
theorem remark21 {p q Q r : α → ℝ} (hp : SC p) (hq : SC q) (hQ : SC Q) (hr : SC r) (b : α) :
    (∀ a b, bfa r Q a b = bfa q p a b) ↔
      ∀ a, pia r Q a = (pia r Q b / pia q p b) * pia q p a := by
  have hpq : ∀ a, 0 < pia q p a := fun a => div_pos (hq.1 a) (hp.1 a)
  have hrQ : ∀ a, 0 < pia r Q a := fun a => div_pos (hr.1 a) (hQ.1 a)
  constructor
  · intro h a; have h1 := h a b; rw [eq14, eq14] at h1
    have := (hpq b).ne'; have := (hrQ b).ne'
    field_simp at h1 ⊢; linarith
  · intro h a a'; rw [eq14, eq14, h a, h a']
    have := (hpq b).ne'; have := (hrQ b).ne'; have := (hpq a').ne'
    field_simp

/-- **Remark 2.2**, formula (2.7): under (2.2)-(2.3),
`r(A) = R(A) = [q(A)Q(A)/p(A)] / Σ_{A'} q(A')Q(A')/p(A')`. -/
theorem eq27 {p q Q r R : α → ℝ} (hp : SC p) (hq : SC q) (hQ : SC Q) (hr : SC r) (hR : SC R)
    (h22 : ∀ a b, bfa r Q a b = bfa q p a b) (h23 : ∀ a b, bfa R q a b = bfa Q p a b) :
    ∀ a, r a = R a ∧ r a = (q a * Q a / p a) / ∑ a', q a' * Q a' / p a' := by
  have hrR := thm21 hp hq hQ hr hR h22 h23
  obtain ⟨b⟩ : Nonempty α := by
    by_contra h0; rw [not_nonempty_iff] at h0; have := hp.2; simp at this
  have h26 := (remark21 hp hq hQ hr b).1 h22
  set c := pia r Q b / pia q p b
  have hform : ∀ a, r a = c * (q a * Q a / p a) := by
    intro a; have h1 := h26 a; unfold pia at h1
    have := (hQ.1 a).ne'; have := (hp.1 a).ne'
    field_simp at h1 ⊢; linarith
  have hS : c * ∑ a', q a' * Q a' / p a' = 1 := by
    rw [← hr.2, mul_sum]; exact sum_congr rfl fun a _ => (hform a).symm
  have hne : ∑ a', q a' * Q a' / p a' ≠ 0 := by
    intro h0; rw [h0, mul_zero] at hS; exact zero_ne_one hS
  intro a; refine ⟨congrFun hrR a, ?_⟩
  rw [hform a, eq_div_iff hne, mul_right_comm, hS, one_mul]

/-- **Remark 2.2**, existence on a finite algebra: the sum in (2.7) is finite, so (2.7) always
defines a strictly coherent `r = R` satisfying (2.2) and (2.3). -/
theorem eq27_exists {p q Q : α → ℝ} (hp : SC p) (hq : SC q) (hQ : SC Q) :
    ∃ r, SC r ∧ (∀ a b, bfa r Q a b = bfa q p a b) ∧ ∀ a b, bfa r q a b = bfa Q p a b := by
  obtain ⟨b⟩ : Nonempty α := by
    by_contra h0; rw [not_nonempty_iff] at h0; have := hp.2; simp at this
  have hw : ∀ a, 0 < q a * Q a / p a := fun a => div_pos (mul_pos (hq.1 a) (hQ.1 a)) (hp.1 a)
  have hS : 0 < ∑ a', q a' * Q a' / p a' := sum_pos (fun a _ => hw a) ⟨b, mem_univ b⟩
  refine ⟨fun a => (q a * Q a / p a) / ∑ a', q a' * Q a' / p a',
    ⟨fun a => div_pos (hw a) hS, by rw [← sum_div, div_self hS.ne']⟩, fun a a' => ?_,
    fun a a' => ?_⟩ <;>
  · unfold bfa
    have := (hp.1 a).ne'; have := (hp.1 a').ne'; have := (hq.1 a).ne'; have := (hq.1 a').ne'
    have := (hQ.1 a).ne'; have := (hQ.1 a').ne'; have := hS.ne'
    field_simp

/-! ## Section 3: observation-based revision -/

/-- Probability kinematics (3.1) on a partition `E` of the atoms, written at atoms:
`q(A) = q(E_i) p(A) / p(E_i)` for `A ⊆ E_i`, which is (3.1), and equivalent to the rigidity
condition (3.2) and to (3.3). -/
def IsPK (q p : α → ℝ) (E : α → ι) : Prop :=
  ∀ a, q a = pr q (cell E (E a)) * p a / pr p (cell E (E a))

theorem pr_eq_mul_of_forall {q p : α → ℝ} {A : Finset α} {c : ℝ}
    (h : ∀ a ∈ A, q a = c * p a) : pr q A = c * pr p A := by
  unfold pr; rw [mul_sum]; exact sum_congr rfl h

theorem pr_pos {p : α → ℝ} (hp : SC p) {A : Finset α} (hA : A.Nonempty) : 0 < pr p A :=
  sum_pos (fun a _ => hp.1 a) hA

/-- (3.3): `q(A)/p(A) = q(E_i)/p(E_i)` for atoms `A ⊆ E_i`. -/
theorem eq33 {q p : α → ℝ} {E : α → ι} (hp : SC p) (h : IsPK q p E) (a : α) :
    pia q p a = pr q (cell E (E a)) / pr p (cell E (E a)) := by
  unfold pia; rw [h a]; have := (hp.1 a).ne'; field_simp

theorem bfa_of_PK {q p : α → ℝ} {E : α → ι} (hp : SC p) (h : IsPK q p E) (a b : α) :
    bfa q p a b = bf q p (cell E (E a)) (cell E (E b)) := by
  rw [eq14, eq33 hp h, eq33 hp h]; unfold bf; rw [div_div_div_comm]

/-- **Theorem 3.1** (Wagner 2003, p. 353).  In schema (3.4), with `q` from `p` by probability
kinematics on `E`, a revision `r` of `Q` satisfies the atomic Bayes factor identities (3.5)
iff `r` comes from `Q` by probability kinematics on `E` and (3.6)
`β^r_Q(E_i : E_k) = β^q_p(E_i : E_k)`. -/
theorem thm31 {p q Q r : α → ℝ} {E : α → ι} (hp : SC p) (hq : SC q) (hQ : SC Q) (hr : SC r)
    (hE : ∀ i, (cell E i).Nonempty) (hqE : IsPK q p E) :
    (∀ a b, bfa r Q a b = bfa q p a b) ↔
      IsPK r Q E ∧ ∀ i k, bf r Q (cell E i) (cell E k) = bf q p (cell E i) (cell E k) := by
  constructor
  · intro h35
    obtain ⟨b⟩ : Nonempty α := by
      by_contra h0; rw [not_nonempty_iff] at h0; have := hp.2; simp at this
    have h26 := (remark21 hp hq hQ hr b).1 h35
    set c := pia r Q b / pia q p b
    -- r(A) = c κ_i Q(A) on E_i, with κ_i = q(E_i)/p(E_i)
    have hform : ∀ a, r a = (c * (pr q (cell E (E a)) / pr p (cell E (E a)))) * Q a := by
      intro a; have h1 := h26 a; rw [eq33 hp hqE a] at h1; unfold pia at h1
      have := (hQ.1 a).ne'; field_simp at h1 ⊢; linarith
    have hcell : ∀ i, pr r (cell E i) = (c * (pr q (cell E i) / pr p (cell E i))) * pr Q (cell E i) := by
      intro i; exact pr_eq_mul_of_forall fun a ha => by rw [hform a, mem_cell.1 ha]
    have hpk : IsPK r Q E := by
      intro a; rw [hcell (E a), hform a]
      have := (pr_pos hQ (hE (E a))).ne'; field_simp
    refine ⟨hpk, fun i k => ?_⟩
    obtain ⟨a, ha⟩ := hE i; obtain ⟨b', hb'⟩ := hE k
    rw [← mem_cell.1 ha, ← mem_cell.1 hb', ← bfa_of_PK hQ hpk, ← bfa_of_PK hp hqE, h35]
  · rintro ⟨hpk, h36⟩ a b
    -- (3.7)
    rw [bfa_of_PK hQ hpk, h36, ← bfa_of_PK hp hqE]

/-- **Theorem 3.2** (Wagner 2003, p. 354): the Field/Wagner two-partition theorem, derived from
Theorem 2.1 via Theorem 3.1.  Schema (3.10): `p →F Q →E r` and `p →E q →F R`.  If
(3.11) `β^r_Q(E_{i₁}:E_{i₂}) = β^q_p(E_{i₁}:E_{i₂})` and
(3.12) `β^R_q(F_{j₁}:F_{j₂}) = β^Q_p(F_{j₁}:F_{j₂})`, then `r = R`.  Wagner proves it for an
arbitrary σ-algebra by passing to the purely atomic algebra generated by `E ∪ F ∪ {G}`; on a
finite space the full algebra is itself purely atomic and that step is not needed.  All five
probabilities are strictly coherent, as throughout the paper. -/
theorem thm32 {p q Q r R : α → ℝ} {E : α → ι} {F : α → κ} (hp : SC p) (hq : SC q) (hQ : SC Q)
    (hr : SC r) (hR : SC R) (hE : ∀ i, (cell E i).Nonempty) (hF : ∀ j, (cell F j).Nonempty)
    (hQF : IsPK Q p F) (hrE : IsPK r Q E) (hqE : IsPK q p E) (hRF : IsPK R q F)
    (h311 : ∀ i₁ i₂, bf r Q (cell E i₁) (cell E i₂) = bf q p (cell E i₁) (cell E i₂))
    (h312 : ∀ j₁ j₂, bf R q (cell F j₁) (cell F j₂) = bf Q p (cell F j₁) (cell F j₂)) :
    r = R :=
  thm21 hp hq hQ hr hR ((thm31 hp hq hQ hr hE hqE).2 ⟨hrE, h311⟩)
    ((thm31 hp hQ hq hR hF hQF).2 ⟨hRF, h312⟩)

/-- **Remark 3.2**: any strictly coherent `q` comes from any strictly coherent `p` by
probability kinematics on the partition of all atoms. -/
theorem remark32 {p q : α → ℝ} (hp : SC p) : IsPK q p id := by
  intro a
  have hc : cell (id : α → α) a = {a} := by ext b; simp
  simp only [id, hc] at *; unfold pr; simp only [sum_singleton]
  have := (hp.1 a).ne'; field_simp

/-! ## Section 4: explanation-based revision, Theorem 4.1

The algebra generated by a hypothesis `H` and evidence `E` has atoms `HE, HĒ, H̄E, H̄Ē`; here
they are `(0,0), (0,1), (1,0), (1,1)` in `Fin 2 × Fin 2` (first coordinate `H`, second `E`). -/

def evH : Finset (Fin 2 × Fin 2) := univ.filter (·.1 = 0)
def evHbar : Finset (Fin 2 × Fin 2) := univ.filter (·.1 = 1)
def evE : Finset (Fin 2 × Fin 2) := univ.filter (·.2 = 0)
def evEbar : Finset (Fin 2 × Fin 2) := univ.filter (·.2 = 1)

/-- (1.3) the conditional Bayes factor `β^q_p(A : B | C)`. -/
noncomputable def condBF (q p : α → ℝ) (A B C : Finset α) : ℝ :=
  ((pr q (A ∩ C) / pr q C) / (pr q (B ∩ C) / pr q C)) /
    ((pr p (A ∩ C) / pr p C) / (pr p (B ∩ C) / pr p C))

theorem condBF_atoms {q p : α → ℝ} (hq : SC q) (hp : SC p) {A B C : Finset α} {a b : α}
    (hA : A ∩ C = {a}) (hB : B ∩ C = {b}) (hC : C.Nonempty) :
    condBF q p A B C = bfa q p a b := by
  have hq1 : pr q {a} = q a := sum_singleton _ _
  have hq2 : pr q {b} = q b := sum_singleton _ _
  have hp1 : pr p {a} = p a := sum_singleton _ _
  have hp2 : pr p {b} = p b := sum_singleton _ _
  unfold condBF bfa; rw [hA, hB, hq1, hq2, hp1, hp2,
    div_div_div_cancel_right₀ (pr_pos hq hC).ne', div_div_div_cancel_right₀ (pr_pos hp hC).ne']

theorem bfa_eq_iff {p q Q R : α → ℝ} (hp : SC p) (hq : SC q) (hQ : SC Q) (hR : SC R) (a b : α) :
    bfa R q a b = bfa Q p a b ↔
      pia R q a / pia Q p a = pia R q b / pia Q p b := by
  rw [eq14, eq14]
  have h1 : ∀ x, 0 < pia R q x := fun x => div_pos (hR.1 x) (hq.1 x)
  have h2 : ∀ x, 0 < pia Q p x := fun x => div_pos (hQ.1 x) (hp.1 x)
  rw [div_eq_div_iff (h1 b).ne' (h2 b).ne', div_eq_div_iff (h2 a).ne' (h2 b).ne']
  constructor <;> intro h <;> linarith

/-- **Theorem 4.1** (Wagner 2003, pp. 356-357).  In schema (4.4), `R` satisfies the atomic
Bayes factor identities (4.5) `β^R_q(A:B) = β^Q_p(A:B)` iff it satisfies the three conditional
Bayes factor identities (4.6) `β^R_q(E:Ē|H) = β^Q_p(E:Ē|H)`, (4.7) the same given `H̄`, and
(4.8) `β^R_q(H:H̄|E) = β^Q_p(H:H̄|E)`. -/
theorem thm41 {p q Q R : Fin 2 × Fin 2 → ℝ} (hp : SC p) (hq : SC q) (hQ : SC Q) (hR : SC R) :
    (∀ a b, bfa R q a b = bfa Q p a b) ↔
      condBF R q evE evEbar evH = condBF Q p evE evEbar evH ∧
        condBF R q evE evEbar evHbar = condBF Q p evE evEbar evHbar ∧
          condBF R q evH evHbar evE = condBF Q p evH evHbar evE := by
  have e1 : evE ∩ evH = {(0, 0)} := by decide
  have e2 : evEbar ∩ evH = {(0, 1)} := by decide
  have e3 : evE ∩ evHbar = {(1, 0)} := by decide
  have e4 : evEbar ∩ evHbar = {(1, 1)} := by decide
  have e5 : evH ∩ evE = {(0, 0)} := by decide
  have e6 : evHbar ∩ evE = {(1, 0)} := by decide
  have nH : evH.Nonempty := ⟨(0, 0), by decide⟩
  have nHb : evHbar.Nonempty := ⟨(1, 0), by decide⟩
  have nE : evE.Nonempty := ⟨(0, 0), by decide⟩
  rw [condBF_atoms hR hq e1 e2 nH, condBF_atoms hQ hp e1 e2 nH,
    condBF_atoms hR hq e3 e4 nHb, condBF_atoms hQ hp e3 e4 nHb,
    condBF_atoms hR hq e5 e6 nE, condBF_atoms hQ hp e5 e6 nE]
  constructor
  · intro h; exact ⟨h _ _, h _ _, h _ _⟩
  · rintro ⟨h1, h2, h3⟩
    set ρ := fun x => pia R q x / pia Q p x
    have r1 := (bfa_eq_iff hp hq hQ hR _ _).1 h1
    have r2 := (bfa_eq_iff hp hq hQ hR _ _).1 h2
    have r3 := (bfa_eq_iff hp hq hQ hR _ _).1 h3
    have hconst : ∀ x, ρ x = ρ (0, 0) := by
      rintro ⟨i, j⟩; fin_cases i <;> fin_cases j
      · rfl
      · exact r1.symm
      · exact r3.symm
      · exact (r2.symm.trans r3.symm)
    intro a b
    rw [bfa_eq_iff hp hq hQ hR]; exact (hconst a).trans (hconst b).symm

/-! ## Section 5: three indices of probability change -/

/-- The difference `δ^q_p(A) = d^q_p(A) := q(A) - p(A)`. -/
def dI (q p : α → ℝ) (a : α) : ℝ := q a - p a
/-- The normalized difference `D^q_p(A) := (q(A) - p(A))/p(A)`. -/
noncomputable def DI (q p : α → ℝ) (a : α) : ℝ := (q a - p a) / p a

/-- "Since `D^q_p(A) = π^q_p(A) - 1`, the indices `D` and `π` clearly stand or fall together." -/
theorem DI_eq {q p : α → ℝ} {a : α} (h : p a ≠ 0) : DI q p a = pia q p a - 1 := by
  unfold DI pia; field_simp

/-- Criterion I for `ν = d`: Theorem 2.1 holds with (5.1)-(5.2) in place of (2.2)-(2.3). -/
theorem critI_d {p q Q r R : α → ℝ} (h51 : ∀ a, dI r Q a = dI q p a)
    (h52 : ∀ a, dI R q a = dI Q p a) : r = R := by
  funext a; have := h51 a; have := h52 a; unfold dI at *; linarith

/-- Criterion I for `ν = π`. -/
theorem critI_pi {p q Q r R : α → ℝ} (hp : SC p) (hq : SC q) (hQ : SC Q)
    (h51 : ∀ a, pia r Q a = pia q p a) (h52 : ∀ a, pia R q a = pia Q p a) : r = R := by
  funext a; have h1 := h51 a; have h2 := h52 a; unfold pia at h1 h2
  have := (hp.1 a).ne'; have := (hq.1 a).ne'; have := (hQ.1 a).ne'
  field_simp at h1 h2; nlinarith [hp.1 a]

/-- Criterion II holds for `ν = π`: if `q` comes from `p` by kinematics on `E` and `r` satisfies
(5.1) with `ν = π`, then `r` comes from `Q` by kinematics on `E`. -/
theorem critII_pi {p q Q r : α → ℝ} {E : α → ι} (hp : SC p) (hQ : SC Q)
    (hE : ∀ i, (cell E i).Nonempty) (hqE : IsPK q p E) (h51 : ∀ a, pia r Q a = pia q p a) :
    IsPK r Q E := by
  have hform : ∀ a, r a = (pr q (cell E (E a)) / pr p (cell E (E a))) * Q a := by
    intro a; have h1 := h51 a; rw [eq33 hp hqE] at h1; unfold pia at h1
    have := (hQ.1 a).ne'; field_simp at h1 ⊢; linarith
  have hcell : ∀ i, pr r (cell E i) = (pr q (cell E i) / pr p (cell E i)) * pr Q (cell E i) := by
    intro i; exact pr_eq_mul_of_forall fun a ha => by rw [hform a, mem_cell.1 ha]
  intro a; rw [hcell (E a), hform a]
  have := (pr_pos hQ (hE (E a))).ne'; field_simp

/-- Criterion III for `ν = d`: an atom with `Q(A) > 1 - d^q_p(A)` precludes any probability
`r` satisfying (5.1) with `ν = d`. -/
theorem critIII_d {p q Q : α → ℝ} {a : α} (ha : Q a > 1 - dI q p a) :
    ¬ ∃ r : α → ℝ, (∀ b, 0 ≤ r b) ∧ ∑ b, r b = 1 ∧ ∀ b, dI r Q b = dI q p b := by
  rintro ⟨r, hr0, hr1, h⟩
  have hle : r a ≤ 1 := hr1 ▸ single_le_sum (fun b _ => hr0 b) (mem_univ a)
  have := h a; unfold dI at this ha; linarith

/-- Criterion III for `ν = π`: an atom with `Q(A) > 1/π^q_p(A)` precludes any probability `r`
satisfying (5.1) with `ν = π`. -/
theorem critIII_pi {p q Q : α → ℝ} (hp : SC p) (hq : SC q) (hQ : SC Q) {a : α}
    (ha : Q a > 1 / pia q p a) :
    ¬ ∃ r : α → ℝ, (∀ b, 0 ≤ r b) ∧ ∑ b, r b = 1 ∧ ∀ b, pia r Q b = pia q p b := by
  rintro ⟨r, hr0, hr1, h⟩
  have hle : r a ≤ 1 := hr1 ▸ single_le_sum (fun b _ => hr0 b) (mem_univ a)
  have h1 := h a; unfold pia at h1 ha
  have := hp.1 a; have := hq.1 a; have := hQ.1 a
  rw [one_div, inv_div, gt_iff_lt, div_lt_iff₀ (hq.1 a)] at ha
  have hr : r a = Q a * q a / p a := by field_simp at h1 ⊢; linarith
  rw [hr, div_le_iff₀ (hp.1 a)] at hle; linarith

/-- **"The point of absurdity"** (p. 361 and note 5): when there are just two atoms, unless
`Q = p` there is no `r` satisfying (5.1) for `ν = π`.  The hypothesis `q ≠ p` (some learning
occurred) is implicit in Wagner's note 5, which divides by `β/α - (1-β)/(1-α)`; see
`absurdity_needs_learning` for what happens when `q = p`. -/
theorem pi_absurdity {p q Q r : Fin 2 → ℝ} (hp : SC p) (hq : SC q) (hQ : SC Q) (hqp : q ≠ p)
    (hr1 : ∑ b, r b = 1) (h : ∀ b, pia r Q b = pia q p b) : Q = p := by
  have hp1 := hp.2; have hq1 := hq.2; have hQ1 := hQ.2
  simp only [Fin.sum_univ_two] at hp1 hq1 hQ1 hr1
  have h0 := h 0; have h1 := h 1; unfold pia at h0 h1
  have := (hp.1 0).ne'; have := (hp.1 1).ne'; have := (hQ.1 0).ne'; have := (hQ.1 1).ne'
  have e0 : r 0 * p 0 = q 0 * Q 0 := by field_simp at h0; linarith
  have e1 : r 1 * p 1 = q 1 * Q 1 := by field_simp at h1; linarith
  have hq0 : q 0 ≠ p 0 := by
    intro h00; apply hqp; funext b; fin_cases b
    · exact h00
    · show q 1 = p 1; linarith
  -- Q₀ (q₀ - p₀) = p₀ (q₀ - p₀)
  have key : (Q 0 - p 0) * (q 0 - p 0) = 0 := by
    have hp1' : p 1 = 1 - p 0 := by linarith
    have hq1' : q 1 = 1 - q 0 := by linarith
    have hQ1' : Q 1 = 1 - Q 0 := by linarith
    have hr1' : r 1 = 1 - r 0 := by linarith
    rw [hp1', hq1', hQ1', hr1'] at e1
    linear_combination (-p 0) * e1 + (p 0 - 1) * e0
  have hQ0 : Q 0 = p 0 := by
    rcases mul_eq_zero.1 key with h' | h'
    · linarith
    · exact absurd (by linarith) hq0
  funext b; fin_cases b
  · exact hQ0
  · show Q 1 = p 1; linarith

/-- Without learning (`q = p`), `r = Q` satisfies (5.1) for `ν = π` whatever `Q` is. -/
theorem absurdity_needs_learning {p Q : α → ℝ} (hp : SC p) (hQ : SC Q) :
    ∀ b, pia Q Q b = pia p p b := by
  intro b; unfold pia; rw [div_self (hQ.1 b).ne', div_self (hp.1 b).ne']

/-- Section 5, p. 361 / Theorem 5.1: with finitely many atoms the incompatibility of priors
with Bayes-factor learning "never materializes": for any strictly coherent `p` and any
positive `(β_A)`, there is a strictly coherent `q` with `β^q_p(A : B) = β_A / β_B`, namely
(5.5) `q(A) = β_A p(A) / Σ β p`. -/
theorem finite_never_materializes {p : α → ℝ} (hp : SC p) {β : α → ℝ} (hβ : ∀ a, 0 < β a) :
    ∃ q, SC q ∧ ∀ a b, bfa q p a b = β a / β b := by
  obtain ⟨b⟩ : Nonempty α := by
    by_contra h0; rw [not_nonempty_iff] at h0; have := hp.2; simp at this
  have hS : 0 < ∑ a', β a' * p a' :=
    sum_pos (fun a _ => mul_pos (hβ a) (hp.1 a)) ⟨b, mem_univ b⟩
  refine ⟨fun a => β a * p a / ∑ a', β a' * p a',
    ⟨fun a => div_pos (mul_pos (hβ a) (hp.1 a)) hS, by rw [← sum_div, div_self hS.ne']⟩,
    fun a a' => ?_⟩
  unfold bfa
  have := (hp.1 a).ne'; have := (hp.1 a').ne'; have := (hβ a').ne'; have := hS.ne'
  field_simp

/-! ### Note 4: the difference index fails Criterion II

Atoms in the order `HE, H̄E, HĒ, H̄Ē`; the partition `{E, Ē}` labels them `0, 0, 1, 1`. -/

def Epart : Fin 4 → Fin 2 := ![0, 0, 1, 1]
noncomputable def n4p : Fin 4 → ℝ := ![0.4, 0.1, 0.1, 0.4]
noncomputable def n4q : Fin 4 → ℝ := ![0.64, 0.16, 0.04, 0.16]
noncomputable def n4p' : Fin 4 → ℝ := ![0.2, 0.2, 0.3, 0.3]
noncomputable def n4q' : Fin 4 → ℝ := ![0.44, 0.26, 0.24, 0.06]

theorem pr_Epart (x : Fin 4 → ℝ) :
    pr x (cell Epart 0) = x 0 + x 1 ∧ pr x (cell Epart 1) = x 2 + x 3 := by
  unfold pr cell; simp [sum_filter, Fin.sum_univ_four, Epart]

/-- Note 4: `q` comes from `p` by probability kinematics on `{E, Ē}`. -/
theorem note4_q_PK : IsPK n4q n4p Epart := by
  intro a; fin_cases a <;>
    simp [pr, cell, sum_filter, Fin.sum_univ_four, Epart, n4q, n4p] <;> norm_num

/-- Note 4: `q' - p' = q - p` on every atom. -/
theorem note4_same_d : ∀ a, dI n4q' n4p' a = dI n4q n4p a := by
  intro a; fin_cases a <;> simp [dI, n4q', n4p', n4q, n4p] <;> norm_num

/-- Note 4: `q'(H|E) = 22/35 ≈ .6286` while `p'(H|E) = .5`, and `q(H|E) = .8 = p(H|E)`,
`q(H|Ē) = .2 = p(H|Ē)`. -/
theorem note4_conditionals :
    n4q' 0 / (n4q' 0 + n4q' 1) = 22 / 35 ∧ n4p' 0 / (n4p' 0 + n4p' 1) = 1 / 2 ∧
      |(22 / 35 : ℝ) - 0.6286| < 0.00005 ∧
      n4q 0 / (n4q 0 + n4q 1) = 0.8 ∧ n4p 0 / (n4p 0 + n4p 1) = 0.8 ∧
      n4q 2 / (n4q 2 + n4q 3) = 0.2 ∧ n4p 2 / (n4p 2 + n4p 3) = 0.2 := by
  simp [n4q', n4p', n4q, n4p]; norm_num [abs_lt]

/-- Note 4: `q'` does not come from `p'` by probability kinematics on `{E, Ē}`, although
`q' - p' = q - p` and `q` comes from `p` that way.  So identical learning measured by `d` does
not prompt a kinematical revision on the same partition. -/
theorem note4_d_fails_critII :
    IsPK n4q n4p Epart ∧ (∀ a, dI n4q' n4p' a = dI n4q n4p a) ∧ ¬ IsPK n4q' n4p' Epart := by
  refine ⟨note4_q_PK, note4_same_d, fun h => ?_⟩
  have h0 := h 0
  simp [pr, cell, sum_filter, Fin.sum_univ_four, Epart, n4q', n4p'] at h0; norm_num at h0

end Literature.Wagner2003
