

if (isClass("NigeriaNormaliser")){
  print ("Warning !!! previous definition of NigeriaNormaliser would be overwritten.")
}

## all exported functions are declared here
setClass("NigeriaNormaliser", representation(diary_columns_mapping="function", diary_info_columns_2010="function",
                                             get_lsms_weekrecall_info_columns="function",get_lsms_weekrecall_fields_mapping="function",
                                             item_codes_2010="function"
))


ngr_normaliser<-function() {
  
  diary_info_columns_2010<-function(){
    return(c("hhid","item","lwp_unit", "lwp","tlwp_unit", "gift_unit","gift","own_unit","own", "tlwp", "cost"))
  }
  
  diary_columns_mapping<-function(year){
    if (year == 2010){
      s = data.frame(iesname=NULL,name=NULL)
      s= rbind(s,data.frame(iesname="hhid",name="hhid"))
      s= rbind(s,data.frame(iesname="s7bq1",name="is_consumed"))
      s= rbind(s,data.frame(iesname="item_cd",name="item"))
      s= rbind(s,data.frame(iesname="s7bq4",name="cost")) # this is populated only if there is consumption form items purchased in last 7 days
      s= rbind(s,data.frame(iesname="s7bq2b",name="lwp_unit"))
      s= rbind(s,data.frame(iesname="s7bq2a",name="lwp"))
      s= rbind(s,data.frame(iesname="s7bq3b",name="tlwp_unit"))
      s= rbind(s,data.frame(iesname="s7bq3a",name="tlwp"))
      
      s= rbind(s,data.frame(iesname="s7bq5b",name="own_unit"))
      s= rbind(s,data.frame(iesname="s7bq5a",name="own"))
      s= rbind(s,data.frame(iesname="s7bq6b",name="gift_unit"))
      s= rbind(s,data.frame(iesname="s7bq6a",name="gift"))
      
      return(s)
    }
    stop(paste("Year:",year,"not supported"))
  }
  
  get_lsms_weekrecall_info_columns <-function(year){
    if (year == 2010){
      return(c("hhid","region","district", "zone","item","ea","cost","is_urban"))
    }
    
    stop(paste("Year:",year,"not supported"))
  }
  
  #generated using:
  #write(paste("r=rbind(r,data.frame(longname='",r$longname,"', shortname='",r$shortname,"', code=",as.integer(r$itemcode),"))",sep=""),'c:/temp/t.txt')
  item_codes_2010 <- function(){
    r=data.frame(item=NULL,code=NULL,stringsAsFactors = FALSE)
    r=rbind(r,data.frame(longname='Guinea corn/sorghum', shortname='corn', code=10010))
    r=rbind(r,data.frame(longname='Millet ', shortname='millet', code=10011))
    r=rbind(r,data.frame(longname='Maize ', shortname='maize_grain', code=10012))
    r=rbind(r,data.frame(longname='Rice  local', shortname='rice_local', code=10013))
    r=rbind(r,data.frame(longname='Rice imported', shortname='rice_imported', code=10014))
    r=rbind(r,data.frame(longname='Bread', shortname='bread', code=10015))
    r=rbind(r,data.frame(longname='Maize flour', shortname='maize_flour', code=10016))
    r=rbind(r,data.frame(longname='Yam flour', shortname='yam_flour', code=10017))
    r=rbind(r,data.frame(longname='Cassava  flour', shortname='cassava_flour', code=10018))
    r=rbind(r,data.frame(longname='Wheat flour', shortname='wheat_flour', code=10019))
    r=rbind(r,data.frame(longname='Other  grains and flour', shortname='other_grains', code=10020))
    r=rbind(r,data.frame(longname='Cassava roots', shortname='cassava_fresh', code=10030))
    r=rbind(r,data.frame(longname='Yam roots', shortname='yam_fresh', code=10031))
    r=rbind(r,data.frame(longname='Gari white', shortname='gari_white', code=10032))
    r=rbind(r,data.frame(longname='Gari yellow', shortname='gari_yellow', code=10033))
    r=rbind(r,data.frame(longname='Cocoyam', shortname='cocoyam', code=10034))
    r=rbind(r,data.frame(longname='Plantains', shortname='plantains', code=10035))
    r=rbind(r,data.frame(longname='Sweet potatoes', shortname='sweet_potato', code=10036))
    r=rbind(r,data.frame(longname='Potatoes', shortname='potato', code=10037))
    r=rbind(r,data.frame(longname='Other roots and tuber', shortname='roots_other', code=10038))
    r=rbind(r,data.frame(longname='Soya beans', shortname='soyabeans', code=10040))
    r=rbind(r,data.frame(longname='Brown beans', shortname='brown_beans', code=10041))
    r=rbind(r,data.frame(longname='White beans', shortname='white_beans', code=10042))
    r=rbind(r,data.frame(longname='Groundnuts', shortname='peanuts', code=10043))
    r=rbind(r,data.frame(longname='Other nuts/seeds/pulses', shortname='nuts_others', code=10044))
    r=rbind(r,data.frame(longname='Palm oil', shortname='palm_oil', code=10050))
    r=rbind(r,data.frame(longname='Butter/ Margarine', shortname='butter_margarine', code=10051))
    r=rbind(r,data.frame(longname='Groundnuts Oil', shortname='peanut_oil', code=10052))
    r=rbind(r,data.frame(longname='Other oil and Fat', shortname='oil_others', code=10053))
    r=rbind(r,data.frame(longname='Bananas', shortname='bananas', code=10060))
    r=rbind(r,data.frame(longname='Orange/tangerine', shortname='citrus', code=10061))
    r=rbind(r,data.frame(longname='Mangoes', shortname='mangoes', code=10062))
    r=rbind(r,data.frame(longname='Avocado pear', shortname='avocado_pear', code=10063))
    r=rbind(r,data.frame(longname='Pineapples', shortname='pineapples', code=10064))
    r=rbind(r,data.frame(longname='Fruit canned', shortname='fruit_canned', code=10065))
    r=rbind(r,data.frame(longname='Other fruits', shortname='other_fruits', code=10066))
    r=rbind(r,data.frame(longname='Tomatoes', shortname='tomatoes', code=10070))
    r=rbind(r,data.frame(longname='Tomato puree (canned)', shortname='tomatoes_puree', code=10071))
    r=rbind(r,data.frame(longname='Onions', shortname='onions', code=10072))
    r=rbind(r,data.frame(longname='Garden eggs/egg plant', shortname='eggplant', code=10073))
    r=rbind(r,data.frame(longname='Okra fresh', shortname='okra_fresh', code=10074))
    r=rbind(r,data.frame(longname='Okra dried', shortname='okra_dried', code=10075))
    r=rbind(r,data.frame(longname='Pepper', shortname='pepper', code=10076))
    r=rbind(r,data.frame(longname='Leaves (Cocoyam Spinach etc.)', shortname='fresh_leaves', code=10077))
    r=rbind(r,data.frame(longname='Other vegetables (fresh or ', shortname='vegetables_others', code=10078))
    r=rbind(r,data.frame(longname='Chicken', shortname='chicken', code=10080))
    r=rbind(r,data.frame(longname='Duck', shortname='duck', code=10081))
    r=rbind(r,data.frame(longname='Other domestic poultry', shortname='poultry_others', code=10082))
    r=rbind(r,data.frame(longname='Agricultural eggs', shortname='eggs', code=10083))
    r=rbind(r,data.frame(longname='Local eggs', shortname='eggs', code=10084))
    r=rbind(r,data.frame(longname='Other eggs (not chicken)', shortname='eggs_others', code=10085))
    r=rbind(r,data.frame(longname='Beef ', shortname='beef', code=10090))
    r=rbind(r,data.frame(longname='Mutton', shortname='mutton', code=10091))
    r=rbind(r,data.frame(longname='Pork', shortname='pork', code=10092))
    r=rbind(r,data.frame(longname='Goat', shortname='goat', code=10093))
    r=rbind(r,data.frame(longname='Wild game meat', shortname='game', code=10094))
    r=rbind(r,data.frame(longname='Canned beef/corned beef', shortname='beef_corned', code=10095))
    r=rbind(r,data.frame(longname='Other meat (excl. poultry)', shortname='meat_others', code=10096))
    r=rbind(r,data.frame(longname='Fish fresh', shortname='fresh_fish', code=10100))
    r=rbind(r,data.frame(longname='Fish frozen', shortname='frozen_fish', code=10101))
    r=rbind(r,data.frame(longname='Fish smoked', shortname='smoked_fish', code=10102))
    r=rbind(r,data.frame(longname='Fish dried', shortname='dried_fish', code=10103))
    r=rbind(r,data.frame(longname='Snails ', shortname='snails', code=10104))
    r=rbind(r,data.frame(longname='Seafood (lobster crab prawns ', shortname='seafoods', code=10105))
    r=rbind(r,data.frame(longname='Canned fish/seafood', shortname='canned_seafood', code=10106))
    r=rbind(r,data.frame(longname='Other fish or seafood', shortname='fish_others', code=10107))
    r=rbind(r,data.frame(longname='Fresh milk', shortname='fresh_milk', code=10110))
    r=rbind(r,data.frame(longname='Milk powder', shortname='milk_powder', code=10111))
    r=rbind(r,data.frame(longname='Baby milk powder', shortname='babymilk', code=10112))
    r=rbind(r,data.frame(longname='Milk tinned (unsweetened)', shortname='canned_milk', code=10113))
    r=rbind(r,data.frame(longname='Other milk products ', shortname='milk_others', code=10114))
    r=rbind(r,data.frame(longname='Coffee', shortname='coffee', code=10120))
    r=rbind(r,data.frame(longname='Chocolate drinks (including Milo)', shortname='choco_drinks', code=10121))
    r=rbind(r,data.frame(longname='Tea', shortname='tea', code=10122))
    r=rbind(r,data.frame(longname='Sugar', shortname='sugar', code=10130))
    r=rbind(r,data.frame(longname='Jams', shortname='jams', code=10131))
    r=rbind(r,data.frame(longname='Honey', shortname='honey', code=10132))
    r=rbind(r,data.frame(longname='Other sweets and confectionary', shortname='sweets_others', code=10133))
    r=rbind(r,data.frame(longname='Condiments (salt spices pepper ', shortname='condiments', code=10140))
    r=rbind(r,data.frame(longname='Bottled water', shortname='water_bottled', code=10150))
    r=rbind(r,data.frame(longname='Sachet water', shortname='water_sachet', code=10151))
    r=rbind(r,data.frame(longname='Malt drinks', shortname='malt_drinks', code=10152))
    r=rbind(r,data.frame(longname='Soft drinks (Coca Cola spirit etc)', shortname='soft_drinks', code=10153))
    r=rbind(r,data.frame(longname='Fruit juice canned/Pack', shortname='peanut_pack', code=10154))
    r=rbind(r,data.frame(longname='Other non?alcoholic drinks', shortname='soft_drinks_others', code=10155))
    r=rbind(r,data.frame(longname='Beer (local and imported)', shortname='local_beer', code=10160))
    r=rbind(r,data.frame(longname='Palm wine', shortname='palm_wine', code=10161))
    r=rbind(r,data.frame(longname='Pito', shortname='pito', code=10162))
    r=rbind(r,data.frame(longname='Gin', shortname='gin', code=10163))
    r=rbind(r,data.frame(longname='Other alcoholic beverages', shortname='alcoholic_others', code=10164))
    r=rbind(r,data.frame(longname='Cigarettes or tobacco', shortname='cigarettes', code=101))
    r=rbind(r,data.frame(longname='Matches', shortname='matches', code=102))
    r=rbind(r,data.frame(longname='Newspaper and magazines ', shortname='newspapers', code=103))
    r=rbind(r,data.frame(longname='Public transport (bus rail boat etc excludding educational expenses)', shortname='public_transport', code=104))
    r=rbind(r,data.frame(longname='Kerosene', shortname='kerosene', code=301))
    r=rbind(r,data.frame(longname='Palm Kernel Oil', shortname='palm_kernel_oil', code=302))
    r=rbind(r,data.frame(longname='Gas (for lighting/cooking)', shortname='gas', code=303))
    r=rbind(r,data.frame(longname='Other liquid cooking fuel', shortname='liquid_fuel', code=304))
    r=rbind(r,data.frame(longname='Electricity including electricity vouchers', shortname='electricity', code=305))
    r=rbind(r,data.frame(longname='Candle', shortname='candle', code=306))
    r=rbind(r,data.frame(longname='Firewood', shortname='firewood', code=307))
    r=rbind(r,data.frame(longname='Charcoal', shortname='charcoal', code=308))
    r=rbind(r,data.frame(longname='Petrol', shortname='petrol', code=309))
    r=rbind(r,data.frame(longname='Diesel', shortname='diesel', code=310))
    r=rbind(r,data.frame(longname='Light bulbs/globes', shortname='electric_bulb', code=311))
    r=rbind(r,data.frame(longname='Water', shortname='water', code=312))
    r=rbind(r,data.frame(longname='Soap and Washing powder', shortname='soap', code=313))
    r=rbind(r,data.frame(longname='Toilet paper', shortname='toilet_paper', code=314))
    r=rbind(r,data.frame(longname='Personal care goods (razor blades cosmetics)', shortname='cosmetics', code=315))
    r=rbind(r,data.frame(longname='Vitamin suplements', shortname='vitamin', code=316))
    r=rbind(r,data.frame(longname='Insecticides disinfectant and cleaners', shortname='insecticides', code=317))
    r=rbind(r,data.frame(longname='Postal (inlc. Stamps courier)', shortname='fresh_postal', code=318))
    r=rbind(r,data.frame(longname='Recharge cards', shortname='phone_recharge', code=319))
    r=rbind(r,data.frame(longname='Landline charges', shortname='landline_charge', code=320))
    r=rbind(r,data.frame(longname='Internet Services', shortname='internet', code=321))
    r=rbind(r,data.frame(longname='Recreational (Cinemas video/DVD rental', shortname='cinema_dvd', code=322))
    r=rbind(r,data.frame(longname='Motor vehicle service repair or parts', shortname='motor_repair', code=323))
    r=rbind(r,data.frame(longname='Bicycle service repair or parts', shortname='bicycle_repair', code=324))
    r=rbind(r,data.frame(longname='Wages paid to staff/maid/lawnsboy', shortname='wages', code=325))
    r=rbind(r,data.frame(longname='Mortgage ? regular payment to purchase', shortname='mortgage', code=326))
    r=rbind(r,data.frame(longname='Repairs & maintenance to dwelling', shortname='maintenance_house', code=327))
    r=rbind(r,data.frame(longname='Repairs to household and personal items', shortname='maintenance_household', code=328))
    r=rbind(r,data.frame(longname='House Rent', shortname='house_rent', code=329))
    r=rbind(r,data.frame(longname='Infant clothing', shortname='clothes_infant', code=401))
    r=rbind(r,data.frame(longname='Baby nappies/diapers', shortname='clothes_baby', code=402))
    r=rbind(r,data.frame(longname='Boys Tailored clothes', shortname='clothes_boys_tailored', code=403))
    r=rbind(r,data.frame(longname='Boys dress (ready made)', shortname='clothes_boys_made', code=404))
    r=rbind(r,data.frame(longname='Girls Tailored clothes', shortname='clothes_girls_tailored', code=405))
    r=rbind(r,data.frame(longname='Girls dress (ready made)', shortname='clothes_girls_made', code=406))
    r=rbind(r,data.frame(longname='Men Tailored clothes', shortname='clothes_men_tailored', code=407))
    r=rbind(r,data.frame(longname='Men dress (ready made)', shortname='clothes_men_made', code=408))
    r=rbind(r,data.frame(longname='Women Tailored clothes', shortname='women_clothes_tailored', code=409))
    r=rbind(r,data.frame(longname='Women dress (ready made)', shortname='women_clothes_made', code=410))
    r=rbind(r,data.frame(longname='Ankara George materials', shortname='ankara_george_clothes', code=411))
    r=rbind(r,data.frame(longname='Other clothing materials', shortname='clothes_others', code=412))
    r=rbind(r,data.frame(longname='Boys shoes', shortname='shoes_boys', code=413))
    r=rbind(r,data.frame(longname='Mens shoes', shortname='shoes_men', code=414))
    r=rbind(r,data.frame(longname='Girls shoes', shortname='shoes_girls', code=415))
    r=rbind(r,data.frame(longname='Ladys shoes', shortname='shoes_women', code=416))
    r=rbind(r,data.frame(longname='Tailoring charges', shortname='tailoring_charge', code=417))
    r=rbind(r,data.frame(longname='laundry and dry cleaning', shortname='laundry_charge', code=418))
    r=rbind(r,data.frame(longname='Bowls glassware plates silverware etc.', shortname='bowls', code=419))
    r=rbind(r,data.frame(longname='Cooking utensils (cookpots stirring spoons and wisks etc.)', shortname='cooking_utensils', code=420))
    r=rbind(r,data.frame(longname='Cleaning utensils (brooms brushes etc.)', shortname='cleaning_utensils', code=421))
    r=rbind(r,data.frame(longname='Torch / flashlight', shortname='torch', code=422))
    r=rbind(r,data.frame(longname='Umbrella and raincoat', shortname='rainwear', code=423))
    r=rbind(r,data.frame(longname='Paraffin lamp (hurricane or pressure)', shortname='lamp', code=424))
    r=rbind(r,data.frame(longname='Stationery items (not for school)', shortname='stationery_notschool', code=425))
    r=rbind(r,data.frame(longname='Books (not for school)', shortname='books_notschool', code=426))
    r=rbind(r,data.frame(longname='House decorations', shortname='house_decorations', code=427))
    r=rbind(r,data.frame(longname='Nights lodging in rest house or hotel', shortname='lodging_charges', code=428))
    r=rbind(r,data.frame(longname='Health expenditures (excluding insurance)', shortname='health_expenditure', code=430))
    r=rbind(r,data.frame(longname='Donations to church mosque other religious group', shortname='donations', code=429))
    r=rbind(r,data.frame(longname='Carpet rugs drapes curtains', shortname='carpets_rugs', code=501))
    r=rbind(r,data.frame(longname='Linen towels sheets blankets', shortname='linen', code=502))
    r=rbind(r,data.frame(longname='Mat sleeping or for drying maize flour', shortname='mat', code=503))
    r=rbind(r,data.frame(longname='Mosquito net', shortname='mosquito_net', code=504))
    r=rbind(r,data.frame(longname='Mattress', shortname='mattress', code=505))
    r=rbind(r,data.frame(longname='Sports & hobby equipment musical', shortname='sports_hobby', code=506))
    r=rbind(r,data.frame(longname='Film film processing camera', shortname='films', code=507))
    r=rbind(r,data.frame(longname='Builiding items (cement bricks timber iron)', shortname='building_material', code=508))
    r=rbind(r,data.frame(longname='Council rates', shortname='council_rates', code=509))
    r=rbind(r,data.frame(longname='Health insurance', shortname='health_insurance', code=510))
    r=rbind(r,data.frame(longname='Auto insurance', shortname='auto_insurance', code=511))
    r=rbind(r,data.frame(longname='Home insurance', shortname='home_insurance', code=512))
    r=rbind(r,data.frame(longname='Life insurance', shortname='life_insurance', code=513))
    r=rbind(r,data.frame(longname='Fines or legal fees', shortname='fines', code=514))
    r=rbind(r,data.frame(longname='Dowry costs', shortname='dowry', code=515))
    r=rbind(r,data.frame(longname='Marriage ceremony costs', shortname='marriage_ceremony_costs', code=516))
    r=rbind(r,data.frame(longname='Funeral costs', shortname='funeral_costs', code=517))
    r=rbind(r,data.frame(longname='Woodpoles bamboo', shortname='woodpoles_bamboo', code=518))
    r=rbind(r,data.frame(longname='Grass for thatching roof or other use', shortname='grass', code=519))
    
    
    return(r)
  }
  
  get_lsms_weekrecall_fields_mapping <- function(year){
    if (year == 2010){
      s = data.frame(iesname=NULL,name=NULL)
      s= rbind(s,data.frame(iesname="hhid",name="hhid"))
      s= rbind(s,data.frame(iesname="state",name="region"))
      s= rbind(s,data.frame(iesname="lga",name="district"))
      s= rbind(s,data.frame(iesname="sector",name="is_urban"))
      s= rbind(s,data.frame(iesname="ea",name="ea"))
      s= rbind(s,data.frame(iesname="item_cd",name="item"))
      s= rbind(s,data.frame(iesname="s8q2",name="cost"))
      return(s)
    }
    
    
    stop(paste("Year:",year,"not supported"))
  }
  
  
  return(new("NigeriaNormaliser",diary_columns_mapping=diary_columns_mapping, 
             diary_info_columns_2010=diary_info_columns_2010,get_lsms_weekrecall_info_columns=get_lsms_weekrecall_info_columns,
             get_lsms_weekrecall_fields_mapping=get_lsms_weekrecall_fields_mapping,item_codes_2010=item_codes_2010) )
  
}