name = "EntryContestAnalytic"
defaultTargets = ["EntryContestAnalytic"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "14871d5175e8011a94c78e54b431080aabeeab00"

[[lean_lib]]
name = "EntryContestAnalytic"
roots = ["StepIdentity", "EntryContestModel"]

[[lean_lib]]
name = "EntryContest"
srcDir = ".."
roots = ["EntryContest"]
