#!/usr/bin/env python3
"""Render the corrections (entries E in corrections.py) as a LaTeX master plan:
BEFORE and AFTER typeset side by side, then Why and Evidence."""
import re, sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import corrections_entries as C
C.discipline_check()


def esc(t):
    t = t.replace("\\", "\\textbackslash{}")
    for a, b in [("&", "\\&"), ("%", "\\%"), ("#", "\\#"), ("_", "\\_"), ("{", "\\{"), ("}", "\\}"),
                 ("^", "\\^{}"), ("~", "\\~{}")]:
        t = t.replace(a, b)
    return t.replace("\\textbackslash\\{\\}", "\\textbackslash{}")


def prose(t):
    """Markdown-ish explanation text to LaTeX: keep $...$, `code` -> texttt, "q" -> ``q''."""
    out = []
    for k, part in enumerate(re.split(r"(\$[^$]*\$|`[^`]*`)", t)):
        if part.startswith("$") and part.endswith("$") and len(part) > 1:
            out.append(part)
        elif part.startswith("`") and part.endswith("`") and len(part) > 1:
            out.append("\\texttt{" + esc(part[1:-1]) + "}")
        else:
            p = esc(part).replace("->", "$\\to$")
            p = re.sub(r'"([^"]*)"', r"``\1''", p)
            p = re.sub(r"\*\*([^*]*)\*\*", r"\\textbf{\1}", p)
            p = re.sub(r"\*([^*]*)\*", r"\\emph{\1}", p)
            out.append(p)
    return "".join(out)


def latex_cell(t):
    t = " ".join(t.split())
    if t.startswith("%"):
        return "\\textit{(sentence deleted)}"
    return t


rows = []
for eid, title, pairs, purpose, verif in C.E:
    rows.append(f"\\entryhead{{{eid}}}{{{prose(title)}}}")
    for k, (s, e, after) in enumerate(pairs, 1):
        before = C.cut(s, e)
        n = f"{k}/{len(pairs)}" if len(pairs) > 1 else ""
        rows.append(f"{n} & {latex_cell(before)} & {latex_cell(after)} \\\\ \\hline")
    rows.append(f"\\multicolumn{{3}}{{|p{{\\fullw}}|}}{{\\textbf{{Why.}} {prose(purpose)}}} \\\\")
    rows.append(f"\\multicolumn{{3}}{{|p{{\\fullw}}|}}{{\\textbf{{Evidence.}} {prose(verif)}}} \\\\ \\hline\\hline")

D = [
    ("0.A", "Abstract", "Superseded by the author's rewrite and C.1."),
    ("1.A, 1.B, 1.D, 1.E", "Introduction", "Superseded by the author's rewrite; what survives is corrected in C.2-C.8. The ORD sentence of 1.E is still unapplied and presupposes 5.B."),
    ("1.A2", "Two-channel prelude", "Applied by the author; corrected by C.4."),
    ("1.C", "Why sequence matters beyond one judgement", "Needs audit P4 (\"prior beliefs about the groups\") and D13 (BIR's impartial type) before applying."),
    ("2.A, 2.C", "What an impression is; soft means 0<q<1", "Still applicable as written."),
    ("2.B", "Worked example", "Still applicable; every number is in verify\\_example.py."),
    ("3.A", "Jeffrey-commutativity literature", "Needs D1/P3 (Doring normative, Hawthorne psychological), P2 (Doring's remedy is one Jeffrey update), M21 (\"two ends of his taxonomy\"; NL denominator), M24 (D-Z on the paper's side)."),
    ("3.B", "Asch", "Needs P13 (\"no prior association is elicited\", not \"the joint is never elicited\"); Table 7 numbers all correct."),
    ("3.C", "Heckman", "Needs P17a (\"no sample size repairs\" is the paper's inference); \"nothing guarantees\" is p. 109."),
    ("3.D", "Bohren-Imas-Rosenberg", "Needs P17b (attenuation along histories; tau\\_q $\\to$ 0); pages are working-paper pages."),
    ("5.B", "Propositions ORD and ADJ", "Mathematics verified. Prose needs P10/P11: the one-sided construction is Hogarth-Einhorn's Eq. 8; what is new is its two-attribute Jeffrey embedding. Needed for the omega defined in Setup (C.9). Optional Epstein (2006, eq. 12) citation."),
    ("6.A", "Rival mechanisms", "Needs P10 (Hogarth-Einhorn direction), P14 (six stimulus terms, eighteen response traits), P9 (Hawthorne's objection reaches the two-basis case)."),
    ("6.B", "Two channels; rubric prediction", "Carries the interior-omega numbers C.5 points to; position-channel wording needs the C.4 change."),
    ("B.A", "Bibliography", "Hawthorne2004 added; Heckman1998, Doring1999, Garber1980, Bohren2019 still to add when 3.A-3.D land; Jeffrey2004 and BenjaminBodohCreedRabin2019 if C.4/C.6/C.10 are approved."),
]
drows = "\n".join(f"{a} & {b} & {prose(c) if '$' not in c and chr(92) not in c else c} \\\\ \\hline" for a, b, c in D)

tex = r"""%% manuscript_corrections.tex -- master plan of corrections to PAPER_B_MANUSCRIPT.tex.
%% GENERATED by notes/tools/make_corrections_tex.py from notes/tools/corrections_entries.py
%% (BEFORE text cut from the committed manuscript by script). Edit the entries file,
%% then run: python3 notes/tools/make_corrections_tex.py notes/manuscript_corrections.tex
\documentclass[10pt]{article}
\usepackage[a4paper,landscape,margin=1.4cm]{geometry}
\usepackage{amsmath,amssymb,dsfont}
\usepackage{longtable,array}
\usepackage[authoryear,round]{natbib}
\usepackage[T1]{fontenc}
\newcommand{\PB}{P^{\mathrm{B}}}
\newcommand{\PJ}{P^{\mathrm{J}}}
\newcommand{\Pbar}{\overline{P}}
\newcommand{\assoc}{\operatorname{assoc}}
\newcommand{\sgn}{\operatorname{sgn}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\bigO}{\mathcal{O}}
\newcommand{\vv}{v}
\newcommand{\anchor}[1]{}
\renewcommand{\ref}[1]{\textsc{#1}}
\renewcommand{\footnote}[1]{ \textit{[Footnote: #1]}}
\newlength{\fullw}\setlength{\fullw}{25.9cm}
\newcommand{\entryhead}[2]{\multicolumn{3}{|l|}{\rule{0pt}{2.6ex}\large\textbf{#1}\quad #2} \\ \hline}
\setlength{\parindent}{0pt}
\title{Paper B: corrections to the manuscript (master plan)}
\author{}
\date{Against the author's draft committed at e7b997e3, 30 September 2026}
\begin{document}
\maketitle
\vspace{-1.5em}
\noindent Each row sets the current manuscript text (left) against the proposed replacement (right),
both typeset as they would appear. BEFORE text is cut from the committed manuscript by script, so it
matches the manuscript exactly. Under each entry, \textbf{Why} gives the error and \textbf{Evidence} the
Lean or sympy record or page that settles it (audit items refer to \texttt{notes/citation\_audit.md}).
Entry C.15 (inside C.11.9) reconciles Section 3 with \texttt{notes/positioning\_economics.tex}; the abstract (C.1) leads with the identification point for the same reason. Cross-references print as their label (e.g.\ \textsc{prop:IMM}); footnotes print inline. \textbf{Nothing
here is applied.} The author approves entries by number; approved entries are applied to the
manuscript, compiled and committed. Every AFTER text passes the mechanical checks of \texttt{notes/writing\_discipline.md} (no colons, no dashes doing a sentence's work, ``sequence'' for reading order, the fixed adoption terminology, length within 80--120\% of the draft except for deletions, citation fixes and the removed duplicate); the generator refuses to build otherwise.

\section*{Section C: corrections to the current draft}
{\small
\begin{longtable}{|p{0.9cm}|p{12.2cm}|p{12.2cm}|}
\hline
\textbf{Part} & \textbf{BEFORE (current manuscript)} & \textbf{AFTER (proposed)} \\ \hline\hline
\endhead
""" + "\n".join(rows) + r"""
\end{longtable}
}

\section*{C.12: bibliography entries the AFTER texts need}
\texttt{Hawthorne2004} and \texttt{ZhaoOsherson2010} are already in \texttt{bibliography.bib}.
If C.4's optional sentence, C.6, C.10 or C.15 are approved, four more are needed (Jeffrey 2004, Benjamin et al.\ 2019, Heckman 1998, Bohren et al.\ 2019); they are in
\texttt{notes/manuscript\_corrections\_extra.bib} so that this document renders them, and move to
\texttt{bibliography.bib} on approval. The Drive copy of Jeffrey (2004) is the November 2002 draft,
so C.6 and C.10 cite the chapter only.

\section*{Section D: status of the older plan entries (notes/manuscript\_change\_plan.md)}
{\small
\begin{longtable}{|p{2.6cm}|p{5.2cm}|p{17.4cm}|}
\hline
\textbf{Entry} & \textbf{Subject} & \textbf{Status and what it needs} \\ \hline\endhead
""" + drows + r"""
\end{longtable}
}

\bibliographystyle{plainnat}
\bibliography{../bibliography,manuscript_corrections_extra}
\end{document}
"""
open(sys.argv[1] if len(sys.argv) > 1 else os.path.join(C.REPO, "notes", "manuscript_corrections.tex"), "w").write(tex)
print("rows:", len(rows))
