"""
Bikhchandani, Hirshleifer & Welch (1992), JPE 100(5):992-1026 -- numeric claims.

Checks, in exact rational / symbolic arithmetic:
  (1) Brute-force Bayesian agents (Sec. IIA, p.996): every agent computes the exact
      posterior from the likelihood of the observed action history under the
      equilibrium rule, with the paper's tie-break (indifferent -> coin flip).
      The resulting rule coincides with the counting rule d = #adopt - #reject:
      follow the signal when d = 0, adopt-on-H / flip-on-L when d = 1 (and
      symmetrically), and ignore the signal once |d| >= 2 (the cascade).
      Checked for p in {3/5, 3/4, 9/10} and every history up to 10 agents.
  (2) Eq. (1) (p.997) and eqs. (2)-(3) (p.998): the closed forms for up / no /
      DOWN cascade after n = 2m agents, unconditional and given V = 1, against the
      brute-force distribution (numeric p) and the per-agent chain (symbolic p).
  (3) Footnote 11 arithmetic and the p.998 claim that for p = 1/2 + eps the
      probability of no cascade after 10 agents is below 0.1 percent.
  (4) Fig. 1 (p.998): the limit correct-cascade probability p(p+1)/(2(1-p+p^2))
      is increasing in p on (1/2, 1).
  (5) Table 2, "no public information" columns (p.1008) and the p.1007 text
      ("if p = .75 ... .81"): compared with the n -> infinity limit of eq. (3).
      The published columns are NOT the exact eq. (3) values; they agree to within
      0.006 (largest gap at p = .85).  The check records the gaps.
  (6) Result 4 (p.1015) and its proof (A5)-(A12) (pp.1020-1023): (A6)/(A7), the
      closed form of (A10) and its value .488 at p = .9, the simplification of
      (A11) and its value .0935, and the "87 percent higher" claim.
  (7) Result 2 (p.1005) and its proof, Tables A1-A5 (pp.1019-1021): the ex ante
      expected profits .0425 (no release) and .03114 (release).  The conclusion
      holds; several published entries are arithmetic slips (listed below).
Exit status 0 iff every check passes (including that the published slips are
exactly the documented ones).
"""
import sys
from fractions import Fraction as Fr
import itertools
import sympy as sp

ok = True


def check(name, cond, detail=""):
    global ok
    print(("PASS " if cond else "FAIL ") + name + (("  -- " + detail) if detail else ""))
    if not cond:
        ok = False


# ---------------------------------------------------------------------------
# (1) brute-force Bayesian agents
# ---------------------------------------------------------------------------
def sig_lik(p, v, s):
    """Pr(X = s | V = v); s = 1 is H, s = 0 is L (Table 1)."""
    return p if s == v else 1 - p


def bayes_action_probs(p, L1, L0, s):
    """Pr(adopt) for an agent with public likelihoods (L1, L0) and signal s.
    Prior 1/2, C = 1/2: adopt iff E[V] = Pr(V=1) > 1/2, flip a coin at 1/2."""
    a = L1 * sig_lik(p, 1, s)
    b = L0 * sig_lik(p, 0, s)
    if a > b:
        return Fr(1)
    if a < b:
        return Fr(0)
    return Fr(1, 2)


def counting_rule(d, s):
    """The counting characterisation: Pr(adopt) as a function of d and s."""
    if d >= 2:
        return Fr(1)
    if d <= -2:
        return Fr(0)
    if d == 0:
        return Fr(1) if s == 1 else Fr(0)
    if d == 1:
        return Fr(1) if s == 1 else Fr(1, 2)
    # d == -1
    return Fr(1, 2) if s == 1 else Fr(0)


def brute_force(p, N):
    """All action histories of length <= N with their likelihoods under V=1, V=0,
    generated by exact Bayesian agents.  Returns list of dicts by length."""
    layers = [{(): (Fr(1), Fr(1))}]
    rule_ok = True
    for n in range(N):
        nxt = {}
        for h, (L1, L0) in layers[-1].items():
            if L1 == 0 and L0 == 0:
                continue
            d = sum(1 if a else -1 for a in h)
            pa = {}
            for s in (0, 1):
                q = bayes_action_probs(p, L1, L0, s)
                if q != counting_rule(d, s):
                    rule_ok = False
                pa[s] = q
            for a in (1, 0):
                m1 = sum(sig_lik(p, 1, s) * (pa[s] if a else 1 - pa[s]) for s in (0, 1))
                m0 = sum(sig_lik(p, 0, s) * (pa[s] if a else 1 - pa[s]) for s in (0, 1))
                if m1 == 0 and m0 == 0:
                    continue
                nxt[h + (a,)] = (L1 * m1, L0 * m0)
        layers.append(nxt)
    return layers, rule_ok


def classify(h):
    """up / down / none: a cascade has started iff |d| reached 2."""
    d = 0
    for a in h:
        d += 1 if a else -1
        if d >= 2:
            return "up"
        if d <= -2:
            return "down"
    return "none"


def eq1(p, n):
    r = (p - p * p) ** (n // 2)
    return ((1 - r) / 2, r, (1 - r) / 2)


def eq3(p, n):
    r = (p - p * p) ** (n // 2)
    den = 2 * (1 - p + p * p)
    return (p * (p + 1) * (1 - r) / den, r, (p - 2) * (p - 1) * (1 - r) / den)


print("(1)-(2) brute-force Bayesian agents vs counting rule and eqs. (1)-(3)")
for p in (Fr(3, 5), Fr(3, 4), Fr(9, 10)):
    layers, rule_ok = brute_force(p, 10)
    check(f"p={p}: Bayes-optimal rule == counting rule on all histories <= 10", rule_ok)
    # cascade action uninformative: once |d| >= 2 the continuation adds factor 1
    unin = all(
        layers[n + 1].get(h + ((1,) if classify(h) == "up" else (0,)), None) == (L1, L0)
        for n in range(1, 9)
        for h, (L1, L0) in layers[n].items()
        if classify(h) != "none" and (L1, L0) != (0, 0)
    )
    check(f"p={p}: in a cascade the next action leaves both likelihoods unchanged", unin)
    for n in (2, 4, 6, 8, 10):
        tot = {"up": [Fr(0), Fr(0)], "none": [Fr(0), Fr(0)], "down": [Fr(0), Fr(0)]}
        for h, (L1, L0) in layers[n].items():
            c = classify(h)
            tot[c][0] += L1
            tot[c][1] += L0
        unc = tuple((tot[k][0] + tot[k][1]) / 2 for k in ("up", "none", "down"))
        cond = tuple(tot[k][0] for k in ("up", "none", "down"))
        check(f"p={p}, n={n}: eq.(1) unconditional", unc == eq1(p, n))
        check(f"p={p}, n={n}: eqs.(2)/(3) given V=1", cond == eq3(p, n))

# order of signals matters at the population level: same multiset, opposite cascades
def run(signals):
    d = 0
    for s in signals:
        q = counting_rule(d, s)
        assert q in (0, 1), "coin not needed on these paths"
        d += 1 if q == 1 else -1
    return "up" if d >= 2 else "down" if d <= -2 else "none"


check("signals H,H,L,L -> UP cascade; L,L,H,H -> DOWN cascade (same multiset)",
      run([1, 1, 0, 0]) == "up" and run([0, 0, 1, 1]) == "down")

# symbolic: per-agent chain (states -2..2, cascades absorbing) vs closed forms
P = sp.symbols("p", positive=True)


def chain_step(dist, v):
    H = P if v == 1 else 1 - P
    L = 1 - H
    new = {k: 0 for k in (-2, -1, 0, 1, 2)}
    new[2] += dist[2]
    new[-2] += dist[-2]
    new[1] += dist[0] * H
    new[-1] += dist[0] * L
    new[2] += dist[1] * (H + L / 2)
    new[0] += dist[1] * (L / 2)
    new[0] += dist[-1] * (H / 2)
    new[-2] += dist[-1] * (L + H / 2)
    return new


for v in (1, 0):
    dist = {-2: 0, -1: 0, 0: 1, 1: 0, 2: 0}
    for n in range(1, 11):
        dist = chain_step(dist, v)
        if n % 2 == 0 and v == 1:
            f = eq3(P, n)
            res = [sp.simplify(dist[2] - f[0]), sp.simplify(dist[0] - f[1]),
                   sp.simplify(dist[-2] - f[2]), sp.simplify(dist[1]), sp.simplify(dist[-1])]
            check(f"symbolic p, n={n}: chain given V=1 == eq.(3)", all(r == 0 for r in res))
        if n == 2 and v == 1:
            check("eq.(2): after two, given V=1",
                  sp.simplify(dist[2] - P * (P + 1) / 2) == 0
                  and sp.simplify(dist[0] - P * (1 - P)) == 0
                  and sp.simplify(dist[-2] - (P - 2) * (P - 1) / 2) == 0)

# ---------------------------------------------------------------------------
# (3) footnote 11 and the "0.1 percent" claim
# ---------------------------------------------------------------------------
print("\n(3) footnote 11; p = 1/2 + eps after 10 agents")
fn11 = sp.Rational(1, 2) * P * (1 - P) + sp.Rational(1, 2) * P * (1 - P)
check("fn 11: 1/2 p(1-p) + 1/2 p(1-p) = p(1-p)", sp.simplify(fn11 - P * (1 - P)) == 0)
check("eq.(1) after two: (1-p+p^2)/2 = (1 - (p-p^2))/2",
      sp.simplify((1 - P + P**2) / 2 - (1 - (P - P**2)) / 2) == 0)
# p - p^2 <= 1/4 with equality at 1/2, so no-cascade after 10 <= (1/4)^5
bound = sp.Rational(1, 4) ** 5
check("(p-p^2)^5 <= (1/4)^5 = 1/1024 < 1/1000",
      bound == sp.Rational(1, 1024) and bound < sp.Rational(1, 1000),
      f"(1/4)^5 = {float(bound):.6f}")

# ---------------------------------------------------------------------------
# (4) Fig. 1 monotonicity
# ---------------------------------------------------------------------------
print("\n(4) Fig. 1: limit correct-cascade probability increasing in p")
corr = P * (P + 1) / (2 * (1 - P + P**2))
dcorr = sp.factor(sp.diff(corr, P))
# derivative = (1 + 2p - 2p^2)... check sign on (1/2,1) by numerator factor
num, den = sp.fraction(sp.together(sp.diff(corr, P)))
check("d/dp limit correct-cascade > 0 on (1/2,1)",
      all(sp.N(num.subs(P, sp.Rational(k, 100))) * sp.N(den.subs(P, sp.Rational(k, 100))) > 0
          for k in range(51, 100)),
      f"derivative = {dcorr}")
check("limit correct-cascade at p -> 1/2 is 1/2 and at p -> 1 is 1",
      sp.limit(corr, P, sp.Rational(1, 2)) == sp.Rational(1, 2) and sp.limit(corr, P, 1) == 1)

# ---------------------------------------------------------------------------
# (5) Table 2, no-public-information columns
# ---------------------------------------------------------------------------
print("\n(5) Table 2 (p.1008), no public information, vs eq.(3) limit")
table2 = {  # p: (Up (1), Down (2), Expectation of difference (3))
    Fr(55, 100): (Fr("0.5645"), Fr("0.4355"), Fr("0.262")),
    Fr(65, 100): (Fr("0.6950"), Fr("0.3050"), Fr("0.783")),
    Fr(75, 100): (Fr("0.8100"), Fr("0.1900"), Fr("1.242")),
    Fr(85, 100): (Fr("0.9065"), Fr("0.0935"), Fr("1.623")),
    Fr(95, 100): (Fr("0.9724"), Fr("0.0276"), Fr("1.890")),
}
maxgap = 0
for p, (up, dn, ed) in table2.items():
    exact_up = p * (p + 1) / (2 * (1 - p + p * p))  # (p-p^2)^500 is < 1e-300
    gap = abs(float(up - exact_up))
    maxgap = max(maxgap, gap)
    print(f"   p={float(p):.2f}: table Up={float(up):.4f}  eq.(3) limit={float(exact_up):.4f}"
          f"  gap={gap:.4f}   2(Up-Down) exact={2*float(2*exact_up-1):.3f}  table col(3)={float(ed):.3f}")
    check(f"Table 2 p={float(p):.2f}: Up + Down = 1", up + dn == 1)
check("Table 2 col (1) within 0.006 of eq.(3) limit (not exact: largest gap at p=.85)",
      0.005 < maxgap < 0.006, f"max gap {maxgap:.4f}")
# fn 22 (p.1006) says Sec. III.A.3 uses the Sec. IIB tie-break (indifferent adopts).
# Under that rule the UP probability given V=1 is p/(1-p+p^2) (first H starts an UP
# cascade at once); Table 2 is nowhere near it, so it uses the Sec. IIA coin flip.
far = all(abs(float(up - p / (1 - p + p * p))) > 0.02 for p, (up, _, _) in table2.items() if p < Fr(95, 100))
check("Table 2 col (1) is NOT the adopt-when-indifferent (fn 22) value p/(1-p+p^2) for p <= .85", far)
e75 = Fr(3, 4) * Fr(7, 4) / (2 * (1 - Fr(3, 4) + Fr(9, 16)))
check("p.1007 text: p=.75 no public info -> '.81' (eq.(3) limit .8077 rounds to .81)",
      round(float(e75), 2) == 0.81, f"{float(e75):.4f} = {e75}")

# ---------------------------------------------------------------------------
# (6) Result 4 and its proof
# ---------------------------------------------------------------------------
print("\n(6) Result 4 (A5)-(A12)")
A = P * (P + 1) / (2 * (P**2 - P + 1))          # Pr(V=1 | UP started in period 2n)
B = (2 - P) * (1 - P) / (2 * (P**2 - P + 1))    # Pr(V=0 | UP started in period 2n)
# (A6)/(A7) from eq.(3) terms: up-at-pair-k likelihoods under V=1 and V=0
lik_up_V1 = P * (P + 1) / 2
lik_up_V0 = (2 - P) * (1 - P) / 2               # = Pr(DOWN at a pair | V=1) by symmetry
check("(A6): Bayes from eq.(2)/(3) terms gives p(p+1)/(2(p^2-p+1))",
      sp.simplify(lik_up_V1 / (lik_up_V1 + lik_up_V0) - A) == 0)
check("(A6)+(A7) sum to 1", sp.simplify(A + B - 1) == 0)
check("(A6) > 1/2 on (1/2,1): A - 1/2 = (2p-1)/(2(p^2-p+1))",
      sp.simplify(A - sp.Rational(1, 2) - (2 * P - 1) / (2 * (P**2 - P + 1))) == 0)
w95, w05 = sp.Rational(95, 100), sp.Rational(5, 100)
num = A * w95 * (1 - P) + B * w05 * (1 - P)
den = num + A * w05 * P + B * w95 * P
EWupL = sp.simplify(num / den)
closed = (1 - P) * (2 + 16 * P + 20 * P**2) / (2 + 52 * P - 52 * P**2)
check("(A10): E[W|up,L] = (1-p)(2+16p+20p^2)/(2+52p-52p^2)", sp.simplify(EWupL - closed) == 0)
v10 = closed.subs(P, sp.Rational(9, 10))
check("(A10) at p=.9 is .488 < 1/2", round(float(v10), 3) == 0.488 and v10 < sp.Rational(1, 2),
      f"{v10} = {float(v10):.5f}")
check("(A8): Pr(W=1|up) = .9 A + .05 > 1/2 at p=.9",
      sp.Rational(9, 10) * A.subs(P, sp.Rational(9, 10)) + w05 > sp.Rational(1, 2))
a11_first = sp.Rational(9, 10) * (P * (P + 1) * (1 - P)**2 + (2 - P) * (1 - P) * P**2) / (2 * (P**2 - P + 1))
a11_simpl = sp.Rational(9, 10) * P * (1 - P) * (1 + 2 * P - 2 * P**2) / (2 * (P**2 - P + 1))
check("(A11): p(p+1)(1-p)^2+(2-p)(1-p)p^2 = p(1-p)(1+2p-2p^2)", sp.simplify(a11_first - a11_simpl) == 0)
a11 = a11_simpl + w05 * ((1 - P)**2 + P**2)
v11 = a11.subs(P, sp.Rational(9, 10))
check("(A11) at p=.9 equals .0935 (to 4 dp)", round(float(v11), 4) == 0.0935, f"{v11} = {float(v11):.6f}")
# E[W|up,L,H] = E[W|up]: an L and an H signal cancel given W
check("E[W|up,L,H] = E[W|up] (L and H likelihoods cancel)",
      sp.simplify((A * w95 + B * w05) * P * (1 - P) /
                  ((A * w95 + B * w05) * P * (1 - P) + (A * w05 + B * w95) * P * (1 - P))
                  - (A * w95 + B * w05)) == 0)
check("'87 percent higher': .0935/.05 = 1.87", sp.Rational(935, 10000) / w05 == sp.Rational(187, 100))

# ---------------------------------------------------------------------------
# (7) Result 2, Tables A1-A5
# ---------------------------------------------------------------------------
print("\n(7) Result 2, Tables A1-A5")
P0 = {1: Fr(4, 10), 2: Fr(55, 100), 3: Fr(5, 100)}
P1 = {1: Fr(2, 10), 2: Fr(7, 10), 3: Fr(1, 10)}
C = Fr(555, 1000)
check("Table A1 rows are distributions", sum(P0.values()) == 1 and sum(P1.values()) == 1)
check("Table A1 satisfies MLRP (Assumption 1): P1/P0 increasing",
      P1[1] / P0[1] < P1[2] / P0[2] < P1[3] / P0[3])


def post(l1, l0):
    return l1 / (l1 + l0)


# A2
A2_pub = {1: (Fr("0.3"), Fr("0.3333")), 2: (Fr("0.625"), Fr("0.56")), 3: (Fr("0.075"), Fr("0.6667"))}
adopt1 = {}
for x in (1, 2, 3):
    u, e = (P1[x] + P0[x]) / 2, post(P1[x], P0[x])
    adopt1[x] = e >= C
    check(f"A2 x{x}", u == A2_pub[x][0] and abs(e - A2_pub[x][1]) < Fr(1, 10000))
# A3
A3_pub = {("R", 1): (".1000", ".2000"), ("R", 2): (".1800", ".3839"), ("R", 3): (".0200", ".5000"),
          ("A", 1): (".2000", ".4000"), ("A", 2): (".4450", ".6292"), ("A", 3): (".0550", ".7273")}
prof0 = Fr(0)
slips = []
for (D, x), (u_pub, e_pub) in A3_pub.items():
    l1 = sum(P1[y] for y in (1, 2, 3) if adopt1[y] == (D == "A")) * P1[x] / 2
    l0 = sum(P0[y] for y in (1, 2, 3) if adopt1[y] == (D == "A")) * P0[x] / 2
    e = post(l1, l0)
    if e >= C:
        prof0 += (l1 + l0) * (e - C)
    if l1 + l0 != Fr(u_pub):
        slips.append(("A3", D, x, "prob", u_pub, float(l1 + l0)))
    if abs(e - Fr(e_pub)) >= Fr(1, 10000):
        slips.append(("A3", D, x, "E", e_pub, round(float(e), 4)))
check("Result 2: ex ante profit without release = .0425 exactly", prof0 == Fr(425, 10000), str(prof0))
# A4, A5
PS1 = {"H": Fr(51, 100), "L": Fr(49, 100)}
PS0 = {"H": Fr(49, 100), "L": Fr(51, 100)}
ad = {}
A4_pub = {("L", 1): (".151", ".3245"), ("L", 2): (".31175", ".55012"), ("L", 3): (".03725", ".657718"),
          ("H", 1): (".149", ".34228"), ("H", 2): (".31325", ".5698"), ("H", 3): (".03775", ".6755")}
for (S, x), (u_pub, e_pub) in A4_pub.items():
    l1, l0 = PS1[S] * P1[x] / 2, PS0[S] * P0[x] / 2
    e = post(l1, l0)
    ad[(S, x)] = e >= C
    check(f"A4 {S},x{x}", l1 + l0 == Fr(u_pub) and abs(e - Fr(e_pub)) < Fr(1, 10000))
check("A4: release makes individual 1 reject on (L, x2)", ad[("L", 2)] is False and adopt1[2] is True)
A5_pub = {("L", "A", 1): (".01", ".49"), ("L", "A", 2): (".0242", ".71"), ("L", "A", 3): (".0031", ".794"),
          ("L", "R", 1): (".14176", ".313"), ("L", "R", 2): (".2847", ".537"), ("L", "R", 3): (".0339", ".6454"),
          ("H", "A", 1): (".0996", ".4096"), ("H", "A", 2): (".22365", ".638"), ("H", "A", 3): (".02775", ".735"),
          ("H", "R", 1): (".0494", ".2065"), ("H", "R", 2): (".0896", ".3984"), ("H", "R", 3): (".01", ".5100")}
prof1 = Fr(0)
for (S, D, x), (u_pub, e_pub) in A5_pub.items():
    l1 = PS1[S] * sum(P1[y] for y in (1, 2, 3) if ad[(S, y)] == (D == "A")) * P1[x] / 2
    l0 = PS0[S] * sum(P0[y] for y in (1, 2, 3) if ad[(S, y)] == (D == "A")) * P0[x] / 2
    e = post(l1, l0)
    if e >= C:
        prof1 += (l1 + l0) * (e - C)
    dp = len(u_pub) - 1  # published decimals
    if round(float(l1 + l0), dp) != float(u_pub):
        slips.append(("A5", S + D, x, "prob", u_pub, float(l1 + l0)))
    if round(float(e), len(e_pub) - 1) != float(e_pub):
        slips.append(("A5", S + D, x, "E", e_pub, round(float(e), 4)))
print(f"   exact profit with release = {prof1} = {float(prof1):.6f}  (published .03114)")
check("Result 2 conclusion: profit with release < without (.0312 < .0425)", prof1 < prof0)
pub_sum = sum(Fr(u) for (u, _) in A5_pub.values())
check("A5 published column (1) does not sum to 1 (it sums to .99766)", pub_sum == Fr("0.99766"))
pub_formula = (Fr(".0242") * (Fr(".71") - C) + Fr(".0031") * (Fr(".794") - C) + Fr(".0339") * (Fr(".6454") - C)
               + Fr(".22365") * (Fr(".638") - C) + Fr(".02775") * (Fr(".735") - C))
check("published .03114 is the p.1020 formula evaluated on the rounded/slipped table entries",
      round(float(pub_formula), 5) == 0.03112 or round(float(pub_formula), 4) == 0.0311, f"{float(pub_formula):.6f}")
print("   published-table slips found (table, cell, row, quantity, published, exact):")
for s in slips:
    print("     ", s)
expected_slips = {("A3", "R", 2, "E"), ("A5", "LR", 1, "prob"),
                  ("A5", "LR", 2, "prob"), ("A5", "LR", 3, "prob")}
check("slips are exactly the documented ones", {s[:4] for s in slips} == expected_slips)

print("\nAll checks passed." if ok else "\nSOME CHECKS FAILED.")
sys.exit(0 if ok else 1)
